docs/manual/gettingstarted/GettingStarted.md
Fixed activator command for creating a new Lagom project
=> Fixed activator command for creating a new Lagom project

docs/manual/gettingstarted/Installation.md
* [x ] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [x ] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [x ] Have you [squashed your commits](https://www.playframework.com/documentation/2.5.x/WorkingWithGit#Squashing-commits)?
* [x ] Have you updated the documentation?
Fixes the installation instructions for brew base installation of activator
Fixes the docs.
n/a
n/a
Template must be called with typesafe-prefix
=> Update installation guide for brew

docs/manual/concepts/ES_CQRS.md, docs/manual/gettingstarted/Installation.md
=> fix typos in docs

docs/manual/welcome/WhatDoesLagomMean.md
Fixes typo in WhatDoesLagomMean doc.
Fixes a typo.
N/A
N/A
=> Fix typo in docs: WhatDoesLagomMean.

docs/manual/guide/cluster/PersistentEntity.md
=> Fix typo in docs

docs/manual/guide/production/ConductR.md
- Updated sbt plugin version
- Added a section that describes how to install the conductr-cli
- Changed "helloworld" project to "my-service" (more general)
=> Update ConductR documentation

docs/manual/guide/devmode/detailedTopics/ServicePort.md, docs/manual/guide/devmode/detailedTopics/index.toc
Fixes typo
Fix typo: remove ' from services' ports
-
-
=> fix typo: remove ' from services' ports

docs/manual/guide/devmode/detailedTopics/CassandraServer.md
=> Embedded Cassandra server logging documentation

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/Servers.scala, dev/service-locator/src/main/scala/com/lightbend/lagom/gateway/ServiceGateway.scala
=> Meaningful message when service locator/gateway port is already in use

docs/manual/guide/cluster/code/docs/home/persistence/Post.java
=> Fixes : Typology issue

docs/manual/gettingstarted/IDEs.md
sbteclipse version 3.0.1 doesn't exist.
=> Currently required sbteclipse version is 3.0.0

docs/manual/guide/production/ConductR.md
Updates and simplifies the ConductR documentation based on sbt-conductr 2.0.1.
=> ConductR documentation based on sbt-conductr 2.0.1

build.sbt, docs/build.sbt, docs/manual/concepts/Technologies.md, docs/manual/guide/advanced/Akka.md, docs/manual/guide/cluster/Cluster.md, docs/manual/guide/cluster/PersistentEntity.md, docs/manual/guide/cluster/PubSub.md, docs/manual/guide/cluster/ReadSide.md, docs/manual/guide/logging/SettingsLogger.md, docs/manual/guide/production/ReactivePlatform.md, docs/manual/guide/services/ServiceDescriptors.md, docs/manual/guide/services/Test.md
* akka-persistence-cassandra 0.12
* akka 2.4.4
* RP 16s01p05
=> update akka-persistence-cassandra and akka versions

persistence/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraSessionImpl.scala
* When the inital connect failed e.g. because Cassandra was not started yet
the prepared statements were cached as failed futures and would never reconnect.
* Solution is to remove failed from cache
Fixes #91
=> don't cache failed prepared statements, #91

docs/manual/guide/cluster/Cluster.md, docs/manual/guide/cluster/PersistentEntity.md, docs/manual/guide/cluster/PubSub.md, docs/manual/guide/cluster/ReadSide.md, docs/manual/guide/services/Test.md
Fixes #xxxx
In this way, it is more efficiente to follow step by step the documentation without dependency errors
=> Move dependency chapter on top of pages

docs/manual/gettingstarted/GettingStarted.md
Documented rationale for having two services in the project's seed
=> Documented rationale for having two services in the project's seed

docs/manual/gettingstarted/Installation.md
Documentation to avoid OOM in Activator
Related PRs:
* https://github.com/lagom/activator-lagom-java-chirper/pull/17
* https://github.com/lagom/activator-lagom-java/pull/12
=> Documentation to avoid OOM in Activator - Fix #32

api/src/main/java/com/lightbend/lagom/javadsl/api/CircuitBreaker.java, api/src/main/java/com/lightbend/lagom/javadsl/api/ConfigurationServiceLocator.java, api/src/main/java/com/lightbend/lagom/javadsl/api/Descriptor.java, api/src/main/java/com/lightbend/lagom/javadsl/api/ServiceLocator.java, api/src/main/scala/com/lightbend/lagom/internal/api/ServiceReader.scala, build.sbt, client/src/main/java/com/lightbend/lagom/javadsl/client/CircuitBreakingServiceLocator.java, client/src/main/scala/com/lightbend/lagom/internal/client/CircuitBreakerMetricsProviderImpl.scala, client/src/main/scala/com/lightbend/lagom/internal/client/CircuitBreakers.scala, client/src/main/scala/com/lightbend/lagom/internal/client/ServiceClientImplementor.scala, dev/service-registry-client/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryModule.scala, docs/manual/guide/services/code/docs/services/HelloServiceWithCircuitBreaker.java, integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java, service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockService.java, testkit/src/main/scala/com/lightbend/lagom/internal/testkit/TestServiceLocator.scala
=> Moved circuit breakers to service locators

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/Servers.scala
* [ X] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [ X] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ X] Have you [squashed your commits](https://github.com/lagom/lagom/tree/master/WorkingWithGit.md)?
* [ X] Have you added copyright headers to new files?
* [ X] Have you updated the documentation?
* [ X] Have you added tests for any changed functionality?
Fixes #xxxx
Services and server are now stopped in async manner. Each component is stopped in Future. All Futures are synchronized by one Await block.
=> Fix : Stopping runAll  task takes too much time (#66)

README.md
Fixes #xxxx
Improve quality of README.md by fixing spelling and italicize translation, which is a common convention.
1. Spelling - change "potention" to "potential"
2. italicize translation of the word "lagom" for emphasis
=> Update README.me with spell correction, emphasis

docs/manual/guide/services/ServiceImplementation.md
Correcting the first paragraph in the Working with streams section.
=> ServiceImplementation grammar cleanup

docs/manual/guide/production/ConductRSbt.md
n/a
Update ConductR readme to reference `sbt-conductr` version `2.1.9`.
n/a
n/a
=> Update ConductR instructions to use sbt-conductr 2.1.9

.travis.yml, dev/maven-plugin/src/maven-test/external-project/pom.xml, dev/maven-plugin/src/maven-test/start-all/pom.xml, project/SbtMavenPlugin.scala
The travis settings.xml is unnecessary and causes issues. See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
=> Remove ./m2/settings.xml when running on travis

docs/manual/concepts/Technologies.md, docs/manual/welcome/LagomDesignPhilosophy.md
- Adds several missing links to projects we depend on
- Links to documentation for Java 8 features we require
- Fixes the broken link to the CompletionStage Javadoc
=> Update links in documentation

build.sbt, dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLocalServer.scala
Fixes #182.
0.8.0 is not binary compatible with 0.7.0.
=> Downgraded scala-java8-compat to 0.7.0

docs/manual/guide/cluster/ReadSide.md
=> Responsibility

kafka-broker/src/test/scala/com/lightbend/lagom/internal/broker/kafka/KafkaApiSpec.scala
I think the reason the Kafka spec fails is that there are no guarantees, or at least no guarantees within the timeframe that we're asserting, that when a message doesn't get committed, Kafka will republish it to a consumer in a timely manner.
Initially this test always failed on CI, I made it pass more often than not by
sending a handful of messages to the topic before waiting to receive the message. Given that this made it more reliable, it seems sending messages helps to trigger Kafka to resend an uncommitted message. So this change keeps on sending a message every time an assertion that the message has been received fails, until it eventually is received. Hopefully this will further improve the reliability of this test.
=> Attempt to make KafkaSpce more reliable

kafka-broker/src/test/scala/com/lightbend/lagom/internal/broker/kafka/KafkaApiSpec.scala
The old spec was not just checking that Lagom reresumed consuming messages when an error occured, it was checking that Kafka redelivered them. The problem is, it seems sometimes Kafka can take a long time to redeliver them, which meant things were failing in CI.
This new test simply tests that when the stream fails, Lagom will reresume consuming it.
=> Really fix Kafka spec

client/src/main/scala/com/lightbend/lagom/internal/client/ServiceClientImplementor.scala, service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockService.java, service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockServiceImpl.java, service-integration-tests/src/test/scala/com/lightbend/lagom/it/MockServiceSpec.scala
I did some refactoring of the method in a separate commit... it might be easier to review each commit separately. Let me know if you'd like me to squash these together before merging.
Fixes #184
=> Allow missing content type

docs/manual/guide/production/ConductRSbt.md
n/a
Update ConductR instructions to use sbt-conductr 2.1.10
n/a
n/a
=> Update ConductR instructions to use sbt-conductr 2.1.10

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
This should prevent hanging in tests.
Fixes #199.
=> Force kill servers if they don't shut down cleanly

build.sbt
=> Update Akka to 2.4.11

docs/manual/guide/production/ConductRSbt.md
=> Update sbt-conductr version to 2.1.13

docs/manual/guide/production/ConductRSbt.md
=> Update sbt-conductr to 2.1.13

docs/manual/guide/cluster/PersistentEntityRDBMS.md
=> Invalid source reference to jdb in docs fixed

persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraSession.scala
As per title.
I believe this is a small oversight/typo?
=> Fix select statement delegation

docs/manual/guide/production/ConductRSbt.md
Fixes some file path issues with sbt-conductr when creating bundles from Windows.
=> Latest sbt-conductr

docs/manual/concepts/Technologies.md, docs/manual/guide/advanced/Akka.md, docs/manual/guide/cluster/Cluster.md, docs/manual/guide/cluster/PersistentEntity.md, docs/manual/guide/cluster/PubSub.md, docs/manual/guide/cluster/ReadSideCassandra.md, docs/manual/guide/logging/SettingsLogger.md, docs/manual/guide/production/ReactivePlatform.md, docs/manual/guide/services/ServiceDescriptors.md, docs/manual/guide/services/Test.md
Note that this is for the 1.2 release. I'll do same in master.
=> Update links to SBR and Akka docs

docs/manual/concepts/Technologies.md, docs/manual/guide/cluster/Cluster.md, docs/manual/guide/production/ReactivePlatform.md
(cherry picked from commit 286ccee80348bfb089f805f3dce7c9cad72e244f)
=> update links to SBR docs

dev/maven-plugin/src/maven-test/start-all/integration-test/src/test/java/sample/integration/StartAllIT.java, dev/maven-plugin/src/maven-test/start-all/integration-test/src/test/resources/application.conf
=> Increase the timeout in StartAllIT

docs/manual/guide/cluster/ReadSideRDBMS.md
Fixes; mention of Cassandra in documentation page about RDMS
Fix mention
-
-
=> Cassandra still mentioned in page about RDMS

docs/manual/guide/build/LagomBuild.md, docs/manual/guide/build/code/lagom-build.sbt
Fixes invalid version on snippet and typo.
=> Minor docs fixes

docs/manual/guide/production/ConductRSbt.md
=> Update sbt-conductr version to 2.1.16

docs/manual/guide/services/ServiceDescriptors.md
=> Document implicit HTTP method mapping

docs/manual/java/guide/services/HeaderFilters.md, docs/manual/java/guide/services/code/docs/services/EchoService.java, docs/manual/java/guide/services/index.toc, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/security/UserAgentHeaderFilter.java
Adds a section on `Implementing Services` to document `HeaderFilter` usage, implementation and composition.
=> Documents Header Filter

docs/manual/java/appendix/JVMMemoryOnDev.md, docs/manual/java/appendix/index.toc, docs/manual/java/gettingstarted/GettingStartedMaven.md, docs/manual/java/gettingstarted/GettingStartedSbt.md
Fixes #195 
Adds a page in the appendix.
=> Documents how to increase mem in sbt and Maven

docs/manual/java/gettingstarted/IDEs.md
https://github.com/lagom/lagom/issues/267
Tweak to the docs.
=> Really minor docs fix for https://github.com/lagom/lagom/issues/267

service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
This change yields a 4x performance improvement for a service call that does nothing but returns a String (hello world). The problem is that Akka streams materialization is very slow. When there is no request body (eg, for GET requests), there is no need to materialize a stream to handle it, and so this change avoids materialization in that case.
=> Avoid stream materialization on requests with no body

docs/build.sbt, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogCommand.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogEvent.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogState.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/PostSpec.scala, play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/Serializers.scala, play-json/src/test/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializerSpec.scala
Predefined Option serializer for the default play-json Scala serialization module
=> Prepackaged option serializer

docs/manual/guide/production/ConductRSbt.md
=> Bump sbt-conductr to 2.1.17

docs/manual/java/guide/broker/KafkaClient.md, docs/manual/java/guide/broker/code/build-kafka.sbt
This is a Request For Comments. Please review and comment at will. (not backported on purpose)
Fixes #290
=> [RFC] Docs: introduces lagom kafka client module

docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
Tries to fix #213 (can't reproduce locally and since test is flaky we'll have to code review the patch)
=> Adds a polling to eventually detect the DB is ready and proceed

docs/manual/java/guide/services/Test.md, docs/manual/java/guide/services/code/docs/services/test/EnablePersistence.java, testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
=> Fixes docs: cluster and Cassandra are disabled by default since 1.2.x (master)

.jvmopts, .travis-jvmopts
Also removes the temporarily disabled HTTPS for sbt repositories.
=> Increase the heap to 1024M in development and CI

build.sbt
Also updates akka-persistence-cassandra to 0.22.
Fixes #314.
=> Update Akka to 2.4.14

build.sbt, service/core/client/src/main/scala/com/lightbend/lagom/internal/client/WebSocketClient.scala, service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
Requires a few compatability fixes for the new versions of Netty and AsyncHttpClient.
=> Update Play to 2.5.10

build.sbt, cluster/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/cluster/ClusterComponents.scala, docs/build.sbt, docs/manual/scala/guide/services/TestingServices.md, docs/manual/scala/guide/services/code/TestingServices.scala, docs/manual/scala/guide/services/code/testing-services.sbt, docs/manual/scala/guide/services/index.toc, docs/src/test/resources/application.conf, service/scaladsl/integration-tests/src/test/resources/application.conf, service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/ScaladslErrorHandlingSpec.scala, service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/ScaladslMockServiceSpec.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala, testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
Also ported ServicesTest testkit helper to Scala.
=> Added testing services docs

docs/build.sbt, docs/manual/java/concepts/Immutable.md, docs/manual/java/concepts/code/docs/home/immutable/LombokUser.java, docs/manual/java/concepts/code/lagom-immutables.sbt
Added details and examples on using Lombok on `Concepts` / `Immutability`.  See #315 
Didn't work on any of the following
=> Documents using Lombok as alternative to immutables

build.sbt, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala, persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaPersistenceModule.java, persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImpl.java, persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/jpa/JpaSession.java, persistence-jpa/javadsl/src/main/resources/reference.conf, persistence-jpa/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/Retry.scala, persistence-jpa/javadsl/src/test/resources/META-INF/persistence.xml, persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImplSpec.scala, persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/RetrySpec.scala, persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/TestJpaEntity.scala
Documentation for the web site will follow in an upcoming PR.
- #168
- TimMoore/activator-lagom-java-chirper-jpa#1
=> [WIP] JpaSession interface and implementation

docs/manual/scala/guide/services/ServiceImplementation.md
Fixes https://github.com/lagom/online-auction-scala/issues/6
poke @tommpy
=> Typo in ServiceImplementation.md

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceRegistryActor.scala
=> Adds WARN messages in dev mode if ambiguous ACLs is resolved on Service Registry.

.jvmopts
I have been getting GC limit exceeded errors again running compile/test locally.
=> Increase the sbt heap to 1536M

docs/manual/scala/gettingstarted/GettingStarted.md
Fixed typo from 'steram' to 'stream'
=> Small typo fix

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
Adds a println when Kafka ends prematurely (not caused by a user interaction).
Fixes #382 
*TODO*
=> [WIP] Improve feedback wrt Kafka/Cassandra aliveness in Dev mode

docs/.jvmopts, docs/README.md
Added a README file with the sbt commands for building the docs.
=> Doc updates

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/CircuitBreaker.java
Fixes https://github.com/lagom/lagom/issues/380
Describes what a circuit breaker is in the context of distributed systems.
I saw numerous references to circuit breaker. Googling `lagom circuit breaker` returned me no results to describe what a circuit breaker was.
Fixes https://github.com/lagom/lagom/issues/380
=> Expanded Javadoc for CircuitBreaker

docs/manual/scala/gettingstarted/GettingStarted.md
I've found the auction very useful and so I think it's worth advertising up front so I added a link in getting started. There may be better places but this seemed an appropriate place
Fixes #397
Points reader to nice big example
Because I didn't find the auction for a while and it would have helped earlier.
=> added reference to auction

.gitignore, .travis.yml, bin/scriptLib, bin/test, bin/test-code-style, bin/test-documentation, bin/test-maven, bin/test-sbt, build.sbt, persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceModule.scala, project/plugins.sbt
Fixes #362.
Also redid the way that tests are run, using scripts that can do a lot more than is feasible in the travis.yml file, since I had to do this anyway for the code style test.
=> Added code style test and mima to travis

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/ConfigurationServiceLocator.java
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=511252
I'll push to get it fixed in Eclipse, but in the meantime this will help me load Lagom into Eclipse so that I can more easily contribute to it.
=> Explicitly specify type parameter to work around Eclipse bug 511252

service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaSubscriberActor.scala
=> Ensure errors occuring when a topic subscription errors get logged

docs/manual/common/guide/devmode/CassandraServer.md, docs/manual/common/guide/devmode/KafkaServer.md, docs/manual/common/guide/devmode/code/build-cassandra-opts3.sbt
=> Fixes wrong docs: connect to an external cassandra

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md, docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
Fixes [#447](https://github.com/lagom/lagom/issues/447)
Change to correct URL link.
PS. Already signed the CLA.
=> Fix - change to correct URL.

.github/ISSUE_TEMPLATE.md
- Updated the issue template to refer to correct Lagom versions
- I also updated the Oracle JDK ref to something more recent, just to promote people using the latest version.
See above
=> Updated the issue template to refer to correct Lagom versions

service/scaladsl/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslServiceClientInvoker.scala, service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ServiceAclResolverSpec.scala
=> Ensured Scala ACL resolver honours REST method

persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImpl.java
=> Fix JPA offset update statement binding in PostgreSQL

dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
=> Configures Cassandra keyspace to a normalized service name

persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala, persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala, persistence/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/NamedEntity.java, persistence/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistrySpec.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistrySpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/NamedEntity.scala
=> Bugfix: Overriden entityName in PersistentEntity should be used on refFor.

persistence-jdbc/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/JdbcOffsetStore.scala, persistence-jdbc/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
Fixes #449
Back-ported from #474 / 86225a019ef03c6c5586e009484de73c63588853
=> [1.2.x] Allow disabling JDBC offset table auto-creation

docs/manual/scala/guide/production/ConductR.md, docs/manual/scala/guide/production/code/ConductR.scala, docs/manual/scala/guide/services/ServiceImplementation.md, docs/manual/scala/guide/services/code/ServiceImplementation.scala
=> Documented describeServices

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
This is a simplified backport of b917804.
=> [1.2.x] Fix lagomExternalProject

CONTRIBUTING.md
=> Requires scaladsl and suggests packaging and project names

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceImpl.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceTest.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-api/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/cassandra-config/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/it/__service2ClassName__IT.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
Removed unused imports and added schemas to the pom.xml files.
=> Fixed eclipse warnings for Maven archetype

project/Doc.scala
=> [WIP] Enable JS inclusion on javadocs post JDK 1.8.0_121

docs/manual/java/releases/index.toc
=> order desc so the default is the current release

docs/manual/scala/guide/broker/KafkaClient.md
=> Documents usage of LagomKafkaComponents (and Client)

build.sbt
=> Update Akka to 2.4.17

docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
=> Increase timeouts in CqrsIntegrationTest

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
This now uses the standard Connection.getSchema method (available since Java 7) but continues to fall back on vendor-specific implementations if it returns null (which is the case for some versions of H2 and the MySQL driver, at least).
Also passes the current schema to the getTables search, as the default is to pass "", which is specified as: "retrieves those without a schema". This typically means that it returns tables in the database default schema, which might not be the current schema.
Fixes #498
=> Fix current schema detection

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
This is a follow up from #570 
After cherry-picking the change to the 1.2.x branch, the build of the branch [failed](https://travis-ci.org/lagom/lagom/jobs/207181017) with this error in the logs:
```
Exception in thread "DefaultDS-1" java.lang.AbstractMethodError: org.h2.jdbc.JdbcConnection.getSchema()Ljava/lang/String;
at com.zaxxer.hikari.pool.HikariProxyConnection.getSchema(HikariProxyConnection.java)
at com.lightbend.lagom.internal.persistence.jdbc.SlickProvider$$anonfun$getCurrentSchema$1.apply(SlickProvider.scala:168)
at com.lightbend.lagom.internal.persistence.jdbc.SlickProvider$$anonfun$getCurrentSchema$1.apply(SlickProvider.scala:168)
at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
at …
```
=> Handle AbstractMethodError from older JDBC drivers

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/GreetingMessage.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__State.java, dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLauncher.scala, dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLocalServer.scala, dev/maven-plugin/src/maven-test/start-all/helloworld-api/src/main/java/sample/helloworld/api/GreetingMessage.java, dev/maven-plugin/src/maven-test/start-all/helloworld-impl/src/main/java/sample/helloworld/impl/HelloCommand.java, dev/maven-plugin/src/maven-test/start-all/helloworld-impl/src/main/java/sample/helloworld/impl/HelloEvent.java, dev/maven-plugin/src/maven-test/start-all/helloworld-impl/src/main/java/sample/helloworld/impl/WorldState.java, dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/RegisteredService.java, persistence-cassandra/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraContactPoint.java, service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/status/CircuitBreakerStatus.java, service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/status/Latency.java
* Corrected minor spelling mistakes.
* Removed unnecessary if conditions.
=> [MINOR] Code refactored with unnecessary if conditions

build.sbt, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml, dev/maven-plugin/src/maven-test/external-project/pom.xml, dev/maven-plugin/src/maven-test/start-all/hellostream-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all/helloworld-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all/pom.xml, project/Dependencies.scala
=> Created Maven dependency management pom

docs/manual/guide/cluster/PubSub.md
=> [1.2.x] Fix docs: add disclaimer, remove kafka ref

build.sbt, dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
=> Remove unused archetype properties

api-tools/src/main/scala/com/lightbend/lagom/internal/api/tools/ServiceDetector.scala, api-tools/src/test/java/com/lightbend/lagom/api/tools/tests/javadsl/AclService.java, api-tools/src/test/java/com/lightbend/lagom/api/tools/tests/javadsl/AclServiceImpl.java, api-tools/src/test/java/com/lightbend/lagom/api/tools/tests/javadsl/NoAclService.java, api-tools/src/test/java/com/lightbend/lagom/api/tools/tests/javadsl/NoAclServiceImpl.java, api-tools/src/test/java/com/lightbend/lagom/api/tools/tests/javadsl/StubServiceModule.java, api-tools/src/test/resources/application.conf, api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/AclService.scala, api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/NoAclService.scala, api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/StubServiceLoader.scala, api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/UndescribedService.scala, api-tools/src/test/scala/com/lightbend/lagom/internal/api/tools/ServiceDetectorSpec.scala, build.sbt
Increases coverage of ServiceDiscovery in LagomScala
=> Adds test for ServiceDiscovery in LagomScala

dev/maven-plugin/src/main/maven/plugin.xml, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
=> Deprecate the Cassandra keyspace build config

service/javadsl/client/src/main/java/com/lightbend/lagom/javadsl/client/ServiceClientGuiceSupport.java, service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/ServiceGuiceSupport.java
=> Documents Service (Client) Guice Support

docs/manual/java/gettingstarted/WhatsNext.md
Fixes #615
Needs forward porting to `master` (I got to `1.3.x` via lagomframework.com direct access to fix docs issues)
=> FIX: Linking is case-sensitive

docs/manual/java/guide/broker/KafkaClient.md
=> Explained kafka lookup in service locator [docs/ java]

docs/manual/scala/guide/broker/KafkaClient.md
=> Explained kafka lookup in service locator [docs/ scala]

docs/manual/java/guide/broker/code/docs/javadsl/mb/AnotherServiceTest.java
…pelling
Fixes
- Removes incorrect word **weill**
- Updates the comment and makes it meaningful
This PR removes an incorrect word and updates the comment in code to a meaningful sentence.
To make it more clear for the user to understand.
No references.
=> Updated comment in code to make it meaningful and removed incorrect word

bin/test-code-style, build.sbt, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ClassLoaders.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/MavenFacade.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala, dev/maven-plugin/src/maven-test/external-project/pom.xml, dev/maven-plugin/src/maven-test/start-all/hellostream-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all/helloworld-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all/pom.xml, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala, project/Dependencies.scala
This backports #528 and #530 to 1.3.x.
Please don't squash this PR, the individual commits were cherry picked from individual commits on master, and are good to retain.
=> Backport dependency refactor and whitelist

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/GreetingMessage.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__State.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
#592 (Include Lombok in the template Java projects - Maven)
=> Replace Immutable with Lombok in the Maven Java projects

docs/manual/java/guide/build/IntellijMaven.md
#675 had too many commit. This PR is fixing that situation.
I think it needs backporting to 1.3.x.
=> Clarified that users need to check the prereqs in IntelliJ settings

project/Dependencies.scala, service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala, service/javadsl/kafka/client/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriberSpec.scala, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala, service/scaladsl/kafka/client/src/test/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriberSpec.scala
Fixes #694
I added a couple of tests but the value those add is close to none and they required me to edit the dependency list.
=> Fixes consumer group creation for kafka subscribers.

docs/manual/common/guide/production/code/conductr.sbt, docs/manual/java/gettingstarted/GettingStartedSbt.md, docs/manual/java/releases/Migration13.md, docs/manual/scala/gettingstarted/IntroGetStarted.md, docs/manual/scala/releases/Migration13.md
=> Update Lagom and ConductR versions in the docs

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceRegistryActor.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/discovery/impl/ServiceRegistryImplSpec.scala
This change allows unmanaged services to be registered using http and https URLs that don't specify the port. In addition, it also allows URLs which don't specify a port and for which no well known port can be calculated, but only when no ACLs are registered in conjunction with that service (since the port is only needed by the service gateway to proxy requests, and so if there's no ACLs, the service gateway doesn't need it).
=> Support well known ports in the service registry

docs/manual/java/guide/broker/code/docs/javadsl/mb/AnotherServiceTest.java, docs/manual/scala/guide/broker/code/docs/scaladsl/mb/AnotherServiceSpec.scala
=> Improves sample tests to prevent flaky-ness

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
=> Removes unnecessary, hardcoded execution context

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
=> Ignores lagomCassandraPort when embedded C* is disabled

service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
=> Fixed default header checking for WebSockets

docs/manual/common/concepts/ComponentTechnologies.md, docs/manual/common/guide/production/ReactivePlatform.md, docs/manual/java/guide/cluster/Cluster.md, docs/manual/scala/guide/cluster/Cluster.md
Fixes #229
Should be backported to 1.3.x
cc: @eed3si9n, @beritou, @WadeWaldron
=> Update RP docs and links to SBR

bin/test-code-style, build.sbt, persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-jdbc/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala, persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala, persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickClusteredPersistentEntitySpec.scala, project/plugins.sbt, pubsub/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/pubsub/ClusteredPubSubSpec.scala, pubsub/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/pubsub/STMultiNodeSpec.scala, pubsub/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/pubsub/ClusteredPubSubSpec.scala
=> Fixes both header and formatting for multi-jvm. Enables check on CI.

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
=> Fix deprecation warnings in the sbt plugin

docs/manual/scala/guide/broker/code/docs/scaladsl/mb/HelloServiceImpl.scala
=> Use appropriate offset in topic build op

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/__service1ClassName__Event.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/__service1ClassName__Service.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Entity.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceImpl.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__State.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__EntityTest.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-api/src/main/java/__packageInPathFormat__/__service2Name__/api/__service2ClassName__Service.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/pom.xml, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Module.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Repository.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__ServiceImpl.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Subscriber.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/resources/application.conf, dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/it/__service2ClassName__IT.java
This PR aligns the maven-archetype-java with lagom-java.g8
=> align maven archetype with lagom-java.g8

docs/manual/java/guide/broker/MessageBrokerApi.md, docs/manual/scala/guide/broker/MessageBrokerApi.md
Fixes: 
- redundant/confusing wording.
=> Doc Fix: Update MessageBrokerApi.md

service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
Use play's actor system provider which creates the system and registers a shutdown hook on the appLifecycle
=> Register a shutdown hook for ActorSytem in scaladsl lagom client

dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLauncher.scala, dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLocalServer.scala, project/Dependencies.scala
This is WIP to stabilize `1.3.x`.
=> Fix 1.3.x branch build failures

docs/manual/common/concepts/InternalAndExternalCommunication.md
=> fix link broken due to capitalisation

service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
Experience some timeouts on local test related with connection timeout. This PR increases it from 1 to 5 sec.
=> Increases Zookeeper Client session and connection timeout for tests

.travis.yml
See https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
=> adds "group: edge"

.travis.yml, bin/test-code-style, build.sbt, project/plugins.sbt, project/whitesource.sbt
See https://github.com/lagom/lagom/pull/820
This is not a backport but a completely new development. 
(in hindsight, I think backporting would have been _almost_ possible)
=> Integrate whitesource stable 13x

docs/manual/common/guide/production/code/conductr.sbt
=> Bumps sbt conductr version in docs.

service/javadsl/client/src/main/scala/com/lightbend/lagom/internal/javadsl/client/JavadslServiceClientImplementor.scala
Fixes #863 
Map the call  `descriptor` on a service to the instance of the descriptor
=> Map Descriptor in ServiceClientInvocationHandler

persistence-cassandra/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSide.java
=> Add method completedStatements with varargs

service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/Producer.scala
Replaces #874 
Tests are in #878 to ease backporting.
I believe this could also solve #872, but haven't been able to confirm this yet.
=> Restart topic producer on failure

dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
Fixes #883 
Changed the injected LoggerProxy to be the MavenLoggerProxy so that injection works.
=> fixed maven plugin RunMojo

service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
Fix for https://github.com/lagom/lagom/issues/534
Fix for https://github.com/lagom/lagom/issues/534
It's just the given workaround implemented in the Lagom app loader.
https://github.com/lagom/lagom/issues/534
=> Fix https://github.com/lagom/lagom/issues/534

docs/manual/scala/guide/broker/code/docs/scaladsl/mb/AnotherServiceSpec.scala
Fixes #876 
fix #876 for sample code in doc broker testing may not succeed eventually
Old code use async specs in `eventually` to assert in a `Future`. However, `eventually` only detects raised exceptions to retry.  If a future fails at the first time, `eventually` receive no exception and won't retry the code even though future might succeed later.
So changing it to `whenReady` is more logical in this case. It will throw an exception if future fails, and `eventually` will retry until it succeeds or timeouts.
See #876
=> fix #876 for sample code in doc broker testing may not succeed eventually

docs/manual/common/guide/logging/code/log4j2-lagom-default.xml, docs/manual/common/guide/logging/code/log4j2-lagom-dev.xml, docs/manual/java/guide/logging/code/build-log-lang.sbt, docs/manual/scala/guide/logging/code/build-log-lang.sbt, log4j2/src/main/resources/log4j2-lagom-default.xml, log4j2/src/main/resources/log4j2-lagom-dev.xml, log4j2/src/main/scala/com/lightbend/lagom/internal/log4j2/Log4j2LoggerConfigurator.scala, project/Dependencies.scala
=> Fixes log4j2 configuration files and documentation

docs/manual/common/guide/logging/code/log4j2-lagom-default.xml, docs/manual/common/guide/logging/code/log4j2-lagom-dev.xml, docs/manual/java/guide/logging/code/build-log-lang.sbt, docs/manual/scala/guide/logging/code/build-log-lang.sbt, log4j2/src/main/resources/log4j2-lagom-default.xml, log4j2/src/main/resources/log4j2-lagom-dev.xml, log4j2/src/main/scala/com/lightbend/lagom/internal/log4j2/Log4j2LoggerConfigurator.scala, project/Dependencies.scala
This is a 'cherrypick' from cf0e43c269e230bd8fb4571e1cf89b07f49bcf4b + the necessary changes to make it work against play 2.5.x
=> Fixes Log4jLoggerConfigurator

project/Dependencies.scala
=> update akka version to 2.4.20

testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
I continued @TimMoore train of thought introduced in the description of #869 and managed to contain the types issue he described.
Fixes #869
=> Stop servers before completing the Async tests

docs/manual/common/guide/logging/code/log4j2-lagom-default.xml, docs/manual/common/guide/logging/code/log4j2-lagom-dev.xml, docs/manual/common/guide/logging/code/logback-lagom-default.xml, docs/manual/common/guide/logging/code/logback-lagom-dev.xml, log4j2/src/main/resources/log4j2-lagom-default.xml, log4j2/src/main/resources/log4j2-lagom-dev.xml, logback/src/main/resources/logback-lagom-default.xml, logback/src/main/resources/logback-lagom-dev.xml
* Changes log level for Prod and Dev. 
* adds rolling appender for Prod environment. 
The log4j configuration is also changed, but I didn't add a rolling file appender for it. Still looking for a good setting (and wondering if we still need to support it again as nobody seems to be using it).
Resolves #923
=> Improved logging settings - defaulting to INFO instead of WARN

jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java, project/Dependencies.scala
=> update akka version to 2.5.4

docs/manual/java/guide/production/ConductR.md, docs/manual/scala/guide/production/ConductR.md
...includes a direct link to the new getting started experience in order to really streamline things.
=> Reflect the new free version of ConductR

docs/build.sbt, project/Dependencies.scala
=> Bumps play to 2.6.3

docs/manual/common/guide/logging/SettingsLogger.md, docs/manual/common/guide/logging/code/log4j2-lagom-default.xml, docs/manual/common/guide/logging/code/log4j2-lagom-dev.xml, docs/manual/common/guide/logging/code/logback-lagom-default.xml, docs/manual/common/guide/logging/code/logback-lagom-dev.xml, log4j2/src/main/resources/log4j2-lagom-default.xml, log4j2/src/main/resources/log4j2-lagom-dev.xml, logback/src/main/resources/logback-lagom-default.xml, logback/src/main/resources/logback-lagom-dev.xml, project/Dependencies.scala
This PR fixes #938 on master branch by updating logback version. 
This should not be backported to 1.3.x unless we are up to update the version there as well. 
For 1.3.x I will send another PR. We can later decide for backporting or the specific PR.
=> fix ClassNotFoundException for SizeAndTimeBasedRollingPolicy (master)

dev/maven-plugin/src/main/maven/plugin.xml, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
=> akka-http based ServiceGateway as default 

docs/manual/scala/guide/cluster/Serialization.md, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/Registry.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/RegistryWithCompression.scala, play-json/src/main/resources/reference.conf
=> Adds docs on compression for scaladsl JSON serialization

project/Dependencies.scala
=> upgrades AkkaStreamKafkaVersion and KafkaVersion 

docs/manual/scala/guide/services/DependencyInjection.md
The ApplicationLoader's name is HelloApplicationLoader but the play configuration refers to HelloLoader
Fixes #xxxx
=> Fixed inconsistency in code example

docs/manual/java/guide/build/LagomBuild.md
I guess the hello-stream implementation uses the hello-api to call the hello service and not itself.
Fixes #xxxx
=> Corrected service name

project/Dependencies.scala, project/plugins.sbt
=> Bumps Logback to 1.1.7 (with a ripple effect)

docs/build.sbt
This is a leftover of #1011 that completes the fix of #1008 .
=> Updates dependencies on docs (play akka and scala)

CODE_OF_CONDUCT.md
This CoC is copy/pasted from Play.
@marcospereira mentinoed they added that recently and since Hacktoberfest is around the corner it sounded like a good idea.
=> Adds a CoC (copied from Play FW)

project/Dependencies.scala
This is a manual forward port of some refactors applied in #1011
=> Extract slf4j, exclude it from transitive deps and depend on it explicitly

docs/manual/common/guide/devmode/KafkaServer.md, docs/manual/java/guide/advanced/IntegratingNonLagom.md, logback/src/main/scala/com/lightbend/lagom/internal/logback/LogbackLoggerConfigurator.scala, service/scaladsl/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslClientMacroImpl.scala
Removed the scalastyle warnings, grammatical errors and spelling mistakes
=> Removed scalastyle warnings, grammatical errors and spelling mistakes

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
This PR adds try / finally block around the execution and closing of create table statement
=> wrap sql statement call in try / finally block

docs/build.sbt, project/Dependencies.scala
=> [1.3.x] Update Play to 2.5.18

docs/manual/java/releases/Migration14.md, docs/manual/scala/releases/Migration14.md, persistence/core/src/main/resources/reference.conf, persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterStartupTaskSerializer.scala, persistence/core/src/test/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterStartupTaskSerializerSpec.scala
=> Added serializer for ClusterStartupTaskActor.Execute

project/Dependencies.scala
=> [1.3.x] Update Akka Persistence Cassandra to 0.30

project/Dependencies.scala
Hi Lagom team, it's been awhile :) How are you ? 
Upgrades AkkaStreamKafkaVersion and KafkaVersion
Kafka 0.11 brings some interesting functionnalities and I don't want to wait for Lagom 1.4
Inspired by https://github.com/lagom/lagom/issues/962 PR
=> Upgrades AkkaStreamKafkaVersion and KafkaVersion for Lagom 1.3

project/Dependencies.scala
Align the Lagom logback version with the Play one.
This "non alignment" could generate this kind of exception: `Exception in thread "main" java.lang.NoSuchMethodError: ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty()V`
A documentation of this error and its solution could be find here: https://jira.qos.ch/browse/LOGBACK-1269
=> Align the Lagom logback version with the Play one.

build.sbt
* [ Y ] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [ Y ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ Y ] Have you [squashed your commits](https://github.com/lagom/lagom/tree/master/WorkingWithGit.md)?
* [ NA ] Have you added copyright headers to new files?
* [ NA ] Have you updated the documentation?
* [ NA ] Have you added tests for any changed functionality?
Fixes #1013 
Ensures .gitignore file is copied to the Maven archetype
N/A
N/A
=> Ensures .gitignore file is copied to the Maven archetype

build.sbt, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/deser/PathParamSerializers.java, service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/PathParamSerializers.scala, service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala, service/javadsl/api/src/test/java/com/lightbend/lagom/api/mock/BlogService.java, service/javadsl/api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/PathParamSerializer.scala, service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ServiceSupportSpec.scala
Fixes #643 
This PR adds support for deriving instances of PathParamSerializer for any Traversable type
https://github.com/lagom/lagom/issues/643#issuecomment-292074384
=> PathParamSerializer derived instances for traversables

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ClassLoaders.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ConsoleHelper.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/PortAssigner.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala, macro-testkit/src/main/scala/com/lightbend/lagom/macrotestkit/ShouldNotTypecheck.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/EventStreamElement.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRef.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/ReadSideProcessor.scala, play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializer.scala, pubsub/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubRef.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/HeaderFilter.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/MessageHeader.scala
=> Removed Scala style errors

build.sbt, persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala, persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceComponents.scala
=> Break inheritance between Read and Write sides for scaladsl JDBC persistence

docs/manual/common/concepts/ComponentTechnologies.md, docs/manual/common/concepts/ServiceDiscovery.md, docs/manual/java/guide/cluster/Cluster.md, docs/manual/java/guide/production/ConductR.md, docs/manual/java/guide/production/ProductionOverview.md, docs/manual/scala/guide/advanced/IntegratingNonLagom.md, docs/manual/scala/guide/cluster/Cluster.md, docs/manual/scala/guide/production/ConductR.md, docs/manual/scala/guide/production/ProductionOverview.md
=> Remove conductR from overview docs

build.sbt, persistence-jdbc/core/src/main/resources/play/reference-overrides.conf, persistence-jdbc/core/src/main/resources/reference.conf, persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbProvider.scala, persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala, persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala, persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala, persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala, persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala, persistence-jpa/javadsl/src/main/resources/reference.conf
=> Configure HikariCP to use values aligned with hardcoded values in Slick

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md, docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md, persistence-jdbc/core/src/main/resources/reference.conf
=> adds missing documentation about fine-tunning Slick AsyncExecution

persistence-cassandra/core/src/main/resources/play/reference-overrides.conf, project/Dependencies.scala
- Update Akka Persistence Cassandra to 0.59
- Disable meta-in-events-by-tag-view
Fixes #1107
- https://github.com/akka/akka-persistence-cassandra#migrations-from-054-to-059
- https://github.com/akka/akka-persistence-cassandra/pull/270
- https://github.com/akka/akka-persistence-cassandra/issues/269
=> Fix the "Undefined column name meta_ser_id" error

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md, docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
Minor rewording as suggest by @ignasi35 on PR #1116
=> minor rewording on documentation

dev/service-registry/service-locator/src/main/resources/application.conf
=> Disables Timeouts and retries in AkkHttp-based Service GW

docs/manual/java/releases/Migration14.md, docs/manual/scala/releases/Migration14.md, project/Dependencies.scala
=> updates akka-persistence-jdbc plugin to version 3.1.0

docs/manual/java/releases/Migration14.md, docs/manual/scala/releases/Migration14.md
=> updates Migration guide for 1.4.0-RC1

version.sbt
Set version to `1.4.0-SNAPSHOT`. 
May become `1.4.0` GA or `1.4.0-RC2`.
=> 1.4.0-SNAPSHOT on 1.4.x branch

version.sbt
=> 1.5.0-SNAPSHOT

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala, dev/cassandra-server/src/main/scala/com/lightbend/lagom/internal/cassandra/CassandraLauncher.scala, dev/maven-plugin/src/main/maven/plugin.xml, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, docs/manual/common/guide/devmode/CassandraServer.md, docs/manual/common/guide/devmode/KafkaServer.md, docs/manual/common/guide/devmode/code/build-cassandra-opts.sbt, docs/manual/common/guide/devmode/code/build-cassandra-opts2.sbt, docs/manual/common/guide/devmode/code/build-cassandra-opts3.sbt, docs/manual/common/guide/devmode/code/build-kafka-opts.sbt, docs/manual/common/guide/devmode/code/build-kafka-opts2.sbt
=> Adds support for alternative Cassandra YAML config 

project/Dependencies.scala, testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala, testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/ServiceTestSpec.scala, testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala
=> Clean up ServiceTest temporary files

service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala, service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStreamedServiceRouterSpec.scala, service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStrictServiceRouterSpec.scala
This can be used by tooling such as Cinnamon (Lightbend Telemetry) to capture endpoint metadata.
=> Add HandlerDef to the Play request headers

.travis.yml
Counterpart to #1190, but for 1.4.x.
=> [1.4.x] Update Whitesource project

service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala, service/javadsl/api/src/test/java/com/lightbend/lagom/api/mock/BlogService.java, service/javadsl/api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala
Fixes #1184
Note this issue only affected javadsl.
=> Adds UUID PathParamSerializer to list of detauls in javadsl

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/deser/ExceptionMessage.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportErrorCode.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportException.java, service/javadsl/api/src/test/scala/com/lightbend/lagom/javadsl/api/transport/TransportExceptionSpec.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/ExceptionSerializer.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/Exceptions.scala, service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
=> Fixes default exception deserialization

service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java, service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaTopicFactory.java
Fixes #1205 and adds a ref to #1255 for further work.
I wanted to keep this bugfix small.
=> Removes wrong prefix in config loading

dev/maven-plugin/src/main/maven/plugin.xml
Fixes #627
Not really a blocker.
Please, backport to `1.4.x` and `1.3.x`
=> Fixes maven plugin types

service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServerMacroImpl.scala
Fixes #1185 as desribed in https://github.com/scala/bug/issues/10691
I added no tests because it's an edgy case.
=> Adds support for empty Service traits in scala

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/resources/application.conf, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/resources/application.conf, docs/manual/java/releases/Migration14.md, docs/manual/scala/releases/Migration14.md
Fixes #1239
Please backport to `1.4.x`
=> Adds more akka-misc serializers on the Migration guides and Mvn archetype

bin/test-documentation, docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
=> Increase timeouts for CqrsIntegrationTest

docs/manual/common/concepts/ComponentTechnologies.md
=> Update name & link for commercial monitoring product

service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaMetadataKeys.java, service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala, service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/KafkaMetadataKeys.scala, service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
=> Adds Kafka message timestamps to Metadata

docs/manual/java/guide/cluster/PersistentEntity.md, docs/manual/scala/guide/cluster/PersistentEntity.md
Fixes #1300
Improves docs wrt persistent entity execution guarantees when a command is processed.
=> Details the execution steps when a command arrives

project/Dependencies.scala
Fixes #1280 
Unblocks #1283
Should fix #1223 
We must backport to `1.4.x`
=> Bumps Play 2.6.13 (and related transitive deps)

docs/manual/scala/guide/cluster/ReadSideSlick.md, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogEventProcessor.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/SlickBlogApplicationLoader.scala
#1105 
Adds documentation for `SlickPersistentComponents` to slick read side support page. Note that I wasn't able to test compilation of these changes locally due to an issue with my computer's CommandLineTools :(
=> Add mention of SlickPersistentComponents. #1105

docs/manual/java/guide/services/MessageSerializers.md
Noticed this typo while reviewing the message serializers doc
=> Fix withMessageSerializer API reference

dev/maven-plugin/src/maven-test/start-all-2.11/helloworld-impl/src/test/java/sample/helloworld/impl/HelloWorldTest.java, dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-impl/src/test/java/sample/helloworld/impl/HelloWorldTest.java, docs/manual/java/guide/cluster/code/docs/home/persistence/Post4Test.java, docs/manual/java/guide/cluster/code/docs/home/persistence/PostTest.java, docs/manual/java/guide/cluster/code/docs/home/serialization/EventMigrationTest.java, docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java, jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java, pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java
Fixes #1282 
It attempts to replace all usages of `JavaTestKit` by `TestKit` without breaking unit tests 
Scala newbie trying to tackle a first PR in Java/Scala project to get started
Depends on #1342
=> Moving to TestKit since JavaTestKit is deprecated

docs/manual/java/releases/Migration14.md, docs/manual/scala/releases/Migration14.md
Updated the description of the downtime upgrade to clarify that this is only required once, not on a continual basis.
Fixes https://github.com/lagom/lagom/issues/1338
Clarifies documentation.
=> Updated Upgrade description in Migration14.md

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
Fixing a small typo in Scaladoc of LagomPlugin, Temr "Java" was used instead of "Scala".
=> Small typo LagomJava -> LagomScala

persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraOffsetStore.scala, persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraReadSideImpl.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/TestEntityReadSide.scala, persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStore.scala, persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala, persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala, persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala, pubsub/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/pubsub/ClusteredPubSubSpec.scala, pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java, pubsub/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/pubsub/ClusteredPubSubSpec.scala, pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala, service/javadsl/server/src/main/java/com/lightbend/lagom/internal/server/status/MetricsServiceImpl.java, testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriverCompatSpec.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriverCompatSpec.scala
Most of them required just an API call replacement or small syntax changes.
=> Remove some compilation warnings

build.sbt, docs/manual/java/gettingstarted/JavaPrereqs.md, docs/manual/java/releases/Migration14.md, docs/manual/scala/gettingstarted/Installation.md, docs/manual/scala/releases/Migration14.md, docs/project/build.properties, project/build.properties
=> Update sbt versions to 0.13.17 and 1.1.6

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala, dev/maven-plugin/src/main/maven/plugin.xml, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala, dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceLocatorServer.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala, docs/manual/common/guide/devmode/DevEnvironment.md, docs/manual/common/guide/devmode/code/build-service-locator.sbt, docs/manual/common/guide/devmode/index.toc, docs/manual/java/guide/devmode/ConfiguringServicesInDevelopment.md, docs/manual/java/guide/devmode/ServiceLocator.md, docs/manual/java/guide/devmode/code/build-services-ports.sbt, docs/manual/java/guide/devmode/code/configuring-devmode-services.sbt, docs/manual/scala/guide/devmode/ConfiguringServicesInDevelopment.md, docs/manual/scala/guide/devmode/ServiceLocator.md, docs/manual/scala/guide/devmode/code/configuring-devmode-services.sbt
This PR changes the binding of services and the service gateway from 0.0.0.0 to 127.0.0.1. This fixes a number of issues including all referenced in #166.
=> Change default binding from 0.0.0.0 to 127.0.0.1 for services and gateway.

build.sbt, cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala, cluster/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/cluster/JoinCluster.scala, cluster/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/cluster/ClusterComponents.scala, persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala, project/Dependencies.scala
=> Log a warning when `lagom.cluster.self-join` is enabled.

docs/manual/scala/guide/services/code/ServiceClients.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomServer.scala
=> deprecates LagomServerComponents#bindService.

dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/Method.java, dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceAcl.java, dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryService.java, dev/service-registry/client-javadsl/src/test/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryServiceSerializationTest.java, dev/service-registry/play-integration-javadsl/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala, dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/discovery/impl/ServiceRegistryImplSpec.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala, docs/manual/java/guide/cluster/code/docs/home/persistence/BlogEvent.java, project/Dependencies.scala, testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/PublishEvent.java
=> Jackson prepartions for Play 2.7

docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/Post2.scala
=> fix typo : one bracket is missing in documentation

docs/build.sbt
This completes https://github.com/lagom/lagom/pull/1445 (`master`) which was merged prematurely.
=> Update akka 2.5.14 in master docs/build.sbt

project/plugins.sbt
Done in preparation for #1455.
=> Update sbt-bintray in preparation for sbt 1.x

project/plugins.sbt
Done in preparation for #1455.
=> Update sbt-sonatype in preparation for sbt 1.x

project/plugins.sbt
Done in preparation for https://github.com/lagom/lagom/pull/1455.
=> Update sbt-multi-jvm in preparation for sbt 1.x

project/plugins.sbt
Done in preparation for https://github.com/lagom/lagom/pull/1455.
=> Update sbt-dependency-graph in preparation for sbt 1.x

project/plugins.sbt
Done in preparation for #1455.
=> Update sbt-release in preparation for sbt 1.x

service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java, service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
Fixes #412.
The reproduce case presented by @ignasi35 was confirmed to work after this fix.
=> allow missing application.conf for ServiceClients.

project/plugins.sbt, project/project/buildinfo.sbt
Done in preparation for #1455.
=> Update sbt-buildinfo in preparation for sbt 1.x

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
=> Increases timeouts by 40% to avoid flakiness in travis

build.sbt
https://github.com/lagom/lagom/pull/1493 almost fixed the issue. The `kafka-server` and `cassandra-server` projects in `build.sbt` were still not properly setup.
=> Fix build to also setup pulbish for server projects

docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
Now based on the standard Lagom TestServer.
=> Refactor CqrsIntegrationTest

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
=> Tell ConductR users to contact Lightbend for help when updating to 1.5

dev/service-registry/service-locator/src/main/java/com/lightbend/lagom/registry/impl/ServiceRegistryImpl.java, service/scaladsl/integration-tests/src/test/resources/application.conf, service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala, service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationSpec.scala, testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
=> Fix play deprecation warnings

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceRegistryActor.scala
=> Improves portName support

project/Dependencies.scala
=> upgrade cassadra plugin version (0.61)

docs/manual/java/guide/services/ServiceDescriptors.md, docs/manual/scala/guide/services/ServiceDescriptors.md
* [yes] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [yes] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [Not Applicable] Have you added copyright headers to new files?
* [yes] Have you updated the documentation?
* [Not Applicable] Have you added tests for any changed functionality?
Fixes #xxxx
Documentation needs to be correct in one place.
There was some problem with one sentence so I corrected that.
=> Modified ServiceDescriptors.md of both Java and Scala

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
Follow-up on https://github.com/lagom/lagom/pull/1535#discussion_r211819472
This PR explains to the migrating users how to update their project's sbt version.
I followed Tim's wording.
No other relevant issues / PRs / mailing lists discussions.
=> Detail how to update sbt version

docs/manual/scala/guide/broker/code/docs/scaladsl/mb/HelloService.scala
* [yes] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [yes] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [not applicable] Have you added copyright headers to new files?
* [yes] Have you updated the documentation?
* [not applicable] Have you added tests for any changed functionality?
There was one extra space in the code example(Hello Service). So, there should be no space because it generates a Scalastyle warning.
Fixes #xxxx
=> Removed scalastyle from HelloService

docs/manual/common/concepts/BuildConcepts.md
=> Fixed sentence

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ConsoleHelper.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/LagomKeys.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
=> List all ports bound for each service

docs/manual/common/guide/devmode/DevEnvironment.md, docs/manual/java/gettingstarted/GettingStartedMaven.md, docs/manual/java/gettingstarted/GettingStartedSbt.md, docs/manual/java/guide/build/MultipleBuilds.md, docs/manual/java/guide/devmode/ConfiguringServicesInDevelopment.md, docs/manual/java/guide/devmode/code/configuring-devmode-services.sbt, docs/manual/scala/gettingstarted/IntroGetStarted.md, docs/manual/scala/guide/build/MultipleBuilds.md
=> Document SSL support in dev mode

docs/build.sbt, project/Dependencies.scala
Fixes #1562 
This PR updates the akka version.
=> Updated akka version to 2.5.16

dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/project/Build.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/project/plugins.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/api/FooService.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/impl/FooServiceImpl.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/java/impl/Module.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/src/main/resources/application.conf, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/test
=> Adds a scripted tests asserting HTTPS availability in dev mode

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
Fixes https://github.com/lagom/lagom/pull/1112#discussion_r214725340
=> Fix slow getLocalHost warning message

build.sbt, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/PortAssigner.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala, dev/build-tool-support/src/test/scala/com/lightbend/lagom/dev/PortAssignerSpec.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala, dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala, dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/test, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/test, dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala, dev/service-registry/play-integration-javadsl/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala, dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
=> Make SSL opt-in

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
Fixes https://github.com/lagom/lagom/pull/1428#issuecomment-403729260
=> Note TestUtil deprecation in 1.5 migration

build.sbt, project/Dependencies.scala
* [yes] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [yes] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [not applicable] Have you added copyright headers to new files?
* [not applicable] Have you updated the documentation?
* [not applicable] Have you added tests for any changed functionality?
Fixes #xxxx
For code clean Modified Dependencies.scala
For code clean Modified Dependencies.scala
code clean up in Dependencies.scala
=> Code clean up create versions object and modify version vals issue 1559#

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
=> Allow multi-mbeans per JVM in Dev Mode

service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
When backporting it to 1.4.x we realised that the stop method was not safe enough. We fix it in 1.4.x, but need to forward port it in master as well.
=> Fix the StandaloneLagomClientFactory.stop()

bin/scriptLib, bin/test-2.11, bin/test-maven, bin/test-sbt-0.13, bin/test-sbt-1.0, docs/build.sbt
=> Fix cron job build scripts

docs/manual/common/guide/devmode/RunningServices.md
I noticed a double negative in the first sentence and an unnecessary comma in the last. Then, I tried to cut down on the wordiness and improve clarity.
Minor documentation fix
=> Improve readability

persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/AggregateEventTag.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/AggregateEventTag.scala
=> Fix AggregateEventTag#allTags docs

build.sbt, docs/manual/scala/guide/broker/MessageBrokerTesting.md, project/Dependencies.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ProducerStubSpec.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/services/FakeServices.scala
=> Improves internal tests and docs for sub/prod unit tests

dev/maven-plugin/src/maven-test/start-all-2.11/integration-test/src/test/java/sample/integration/StartAllIT.java, dev/maven-plugin/src/maven-test/start-all-2.12/integration-test/src/test/java/sample/integration/StartAllIT.java, docs/manual/java/guide/broker/KafkaClient.md, docs/manual/scala/guide/broker/KafkaClient.md, project/Dependencies.scala, service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaSubscriberActor.scala, service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/Producer.scala, service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala
Fixes #1626
I was not able to run the full test suite on my machine therefore I am interested to see what Travis will say about this.
=> Upgrade to Alpakka Kafka 1.0-M1

dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/package.scala, dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala, dev/service-registry/play-integration-javadsl/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala, dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
=> Deduplicate extracting play server URIs from config

bin/test-2.12, bin/test-sbt-1.0, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt, dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala, docs/build.sbt, project/Dependencies.scala
=> Bumps play, akka and scala for 1.4.9

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
This commit also adds a conditional reload of the App when the cause
for shutdown is not a `Play.stop`. This change is unrelated to the
the implementation of Dev.Mode in Play.
Fixes #1657
This was introduced in #1453 when we forgot to copy/paste the code that binds both shutdown sequences:
https://github.com/lagom/lagom/pull/1660/files#diff-b0570315055c9029853b183c2943bf7aR275
Related to https://github.com/lagom/lagom/pull/1660/files#diff-b0570315055c9029853b183c2943bf7aR275
=> Stop the App when the server is stopped in Dev Mode.

dev/service-registry/service-locator/src/main/java/com/lightbend/lagom/registry/impl/ServiceRegistryImpl.java, docs/build.sbt, docs/manual/java/guide/advanced/code/docs/home/actor/WorkerService2Impl.java, docs/manual/java/guide/advanced/code/docs/home/actor/WorkerServiceImpl.java, persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java, persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java, project/Dependencies.scala
Use Akka 2.5.19.
Will impact #1670.
=> Update to use Akka 2.5.19

bin/test-2.12, bin/test-sbt-1.0, dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt, dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala, docs/build.sbt, docs/manual/java/guide/build/code/lagom-build.sbt, docs/manual/java/guide/build/code/multiple-builds.sbt, docs/manual/java/releases/Migration14.md, docs/manual/scala/guide/build/code/lagom-build.sbt, docs/manual/scala/guide/build/code/multiple-builds.sbt, docs/manual/scala/releases/Migration14.md, project/Dependencies.scala
To be backported to the branch for upcoming 1.5.x and the branch for stable 1.4.x.
=> Upgrade to Scala 2.12.8

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
Fixes #1688
I'm not sure this is the best way to fix the issue, if not, feel free to close it.
=> fix JDBC auto-creation of multiple module does not work

dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/DevModeServiceDiscovery.scala, dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/DevModeServiceDiscoverySpec.scala, docs/build.sbt, project/Dependencies.scala
Some code was adapted because there is some small API changes in Akka Discovery between 2.5.19 and 2.5.20.
=> Upgrades to Akka 2.5.20

project/Dependencies.scala
Update Play to version 2.7.0 and also other transitive dependencies.
=> Update to Play 2.7.0 and dependencies

docs/manual/common/guide/devmode/DevEnvironment.md
=> Updates JSON snippet in service API

cluster/core/src/main/resources/reference.conf, cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala, dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala, docs/manual/java/guide/cluster/Cluster.md, docs/manual/scala/guide/cluster/Cluster.md, docs/src/test/scala/com/lightbend/lagom/docs/ServiceSupport.scala, persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala, persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModuleSpec.scala, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala, project/Dependencies.scala, service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ProducerStubSpec.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/TopicPublishingSpec.scala
=> Adds support for Akka Cluster Bootstrap

project/Dependencies.scala
Needs backporting to 1.5.x and 1.4.x.
=> Don't fail whitelist validation in cron

docs/build.sbt, persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcReadSideImpl.scala, project/Dependencies.scala, pubsub/javadsl/src/main/scala/com/lightbend/lagom/javadsl/pubsub/PubSubRef.scala, service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/JavadslErrorHandlingSpec.scala, service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
=> Bumps Akka version to 2.5.21

service/core/client/src/main/scala/com/lightbend/lagom/internal/client/ClientServiceCallInvoker.scala
=> Honour HeaderFilters

project/Dependencies.scala
Updates to the latest Alpakka Kafka which will become final in a week if no issues are found.
=> Update to the latest Alpakka Kafka

akka-management/core/src/main/resources/reference.conf, docs/manual/java/guide/cluster/Cluster.md, docs/manual/scala/guide/cluster/Cluster.md, project/Dependencies.scala
Update Akka Management to version 1.0.0-RC3.
See milestone here: https://github.com/akka/akka-management/milestone/25?closed=1
=>  Update Akka Manangement to 1.0.0-RC3 

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceImpl.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__EntityTest.java
Cleanup the maven archetype (remove use of deprecated API and organize imports)
see https://github.com/playframework/play-meta/issues/13
=> Maven archetype cleanup

docs/manual/java/guide/services/AdditionalRouters.md, docs/manual/java/guide/services/code/docs/services/AdditionalRouters.java, docs/manual/java/guide/services/index.toc, docs/manual/scala/guide/services/AdditionalRouters.md, docs/manual/scala/guide/services/code/AdditionalRouters.scala, docs/manual/scala/guide/services/index.toc
=> Additional routers documentation

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
Updates the versions and release notes links on the introduction paragraph.
=> Reviews links and versions on Migration15

project/Dependencies.scala
Update to the just released final version.
=> Update to Alpakka Kafka 1.0

cluster/core/src/main/resources/play/reference-overrides.conf, docs/manual/common/guide/production/EnterpriseSuite.md
=> Renamed LB Reactive Platform to LB Platform in docs

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
=> Adds mention and link to alpakka kafka changes

docs/manual/common/releases/Highlights15.md, docs/manual/java/releases/Highlights15.md, docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Highlights15.md, docs/manual/scala/releases/Migration15.md
Fixes #1770
Moves `TLS Support` and `Cluster Formation`.
Adds `gRPC` and `Additional Routers`.
=> Move new features to Highlight. Add additionalRouters and gRPC

project/Dependencies.scala
=> Force dependency to evict guava 16.0.1

docs/manual/java/guide/devmode/ServiceLocator.md
Fixes a typo error in docs.
Fix a typo
=> added a missing space character

project/plugins.sbt
=> Update to sbt-whitesource v0.1.14

docs/manual/java/guide/production/ProductionOverview.md, docs/manual/scala/guide/production/ProductionOverview.md
Minor change on `ProductionOverview` to add a checklist of sorts.
=> Adds a checklist of sorts to ProductionOverview

project/Dependencies.scala
Bump Akka HTTP
(and fixes typo)
=> Bump Akka HTTP 10.1.8

docs/manual/common/concepts/ComponentTechnologies.md, docs/manual/common/concepts/ScalableDeployment.md, docs/manual/common/guide/production/LightbendPlatform.md, docs/manual/java/guide/cluster/Cluster.md, docs/manual/java/guide/production/index.toc, docs/manual/scala/guide/cluster/Cluster.md, docs/manual/scala/guide/production/index.toc
https://github.com/lagom/lagom/issues/1771#issuecomment-473150217
Updates Lightbend product references to reflect recent changes.
=> Update Lightbend product references

.travis.yml, bin/test-2.11, bin/test-2.12, bin/test-sbt-0.13, bin/test-sbt-1.0, build.sbt, docs/build.sbt, docs/manual/common/guide/devmode/code/dev-environment.sbt, docs/project/build.properties, docs/project/plugins.sbt, project/Dependencies.scala, project/Protobuf.scala, project/SbtMavenPlugin.scala, project/build.properties, project/plugins.sbt
=> Use sbt 1 to build Lagom itself

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
* [X ] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [X ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ X] Have you added copyright headers to new files?
* [ X] Have you updated the documentation?
* [ X] Have you added tests for any changed functionality?
Documentation is more explicit about including dependancy to build.sbt 
The documentation is not more clear on the steps needed to migrate your 1.4 lagom project to 1.5 with regards to service location.
=> Added service locator dependency info

bin/test-code-style
=> Only run versionSyncCheck if NOT a cron job

bin/test-2.11, bin/test-2.12, build.sbt, docs/build.sbt, docs/manual/common/guide/devmode/code/dev-environment.sbt, docs/project/build.properties, docs/project/plugins.sbt, project/Dependencies.scala, project/Protobuf.scala, project/SbtMavenPlugin.scala, project/build.properties, project/plugins.sbt
This PR backports #1819 to 1.5.x branch.
=> [1.5.x]: Use sbt 1 to build Lagom itself (#1819)

docs/manual/common/guide/production/LightbendPlatform.md, docs/manual/java/releases/Highlights15.md, docs/manual/scala/releases/Highlights15.md
Follow up from #1834, supersedes #1837 and gets a couple more instances.
=> Update reactive-platform --> lightbend-platform

macro-testkit/src/main/scala/com/lightbend/lagom/macrotestkit/ShouldNotTypecheck.scala, service/javadsl/api/src/main/scala/com/lightbend/lagom/javadsl/api/ScalaServiceSupport.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/Service.scala, service/scaladsl/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslClientMacroImpl.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServerMacroImpl.scala
=> Make use of Scala 2.11+'s macro bundles

.github/settings.yml, .mergify.yml
Same as https://github.com/playframework/playframework/pull/9197
=> Let mergify takes care of backports

docs/build.sbt, persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcReadSideImpl.scala, project/Dependencies.scala, pubsub/javadsl/src/main/scala/com/lightbend/lagom/javadsl/pubsub/PubSubRef.scala, service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/JavadslErrorHandlingSpec.scala, service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
Relates to https://github.com/lagom/lagom-akka-discovery-service-locator/pull/80
=> [1.4.x] Upgrade Akka to 2.5.22

service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java, service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaTopicFactory.java, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/KafkaTopicFactory.scala, service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/LagomKafkaClientComponents.scala
=> Use injected/cake config instead of the one from actor system

.jvmopts, .travis-jvmopts, bin/scriptLib
We have OOM errors when building nightly, and we aren't having the same problem in Travis anymore. So let's use the same configuration at both places.
=> Use the same JVM for sbt locally and in travis

project/Dependencies.scala
Upgrade Alpakka Kafka to 1.0.2 (from 1.0.1)
=> Alpakka Kafka 1.0.2

docs/manual/java/guide/production/code/akka-discovery-dependency.sbt, docs/manual/scala/guide/production/code/akka-discovery-dependency.sbt
Supersedes #1897
We only need to change it in the docs for 1.5.x
PR #1901 will fix the issue on master and we don't need to touch the docs there
=> Fix documentation on how to include akka discovery integration

docs/manual/java/guide/services/code/docs/services/AdditionalRouters.java, docs/project/plugins.sbt, project/plugins.sbt, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/ServiceInfo.java, service/javadsl/client/src/main/java/com/lightbend/lagom/javadsl/client/ConfigurationServiceLocator.java, testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/ProducerStubTest.java
=> Update/sbt java formatter 0.4.4

persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImpl.java
=> [1.4.x]: JpaReadSide. ORA-00932: inconsistent datatypes

dev/maven-plugin/src/maven-test/external-project-2.12/api/pom.xml, dev/maven-plugin/src/maven-test/external-project-2.12/impl/pom.xml, dev/maven-plugin/src/maven-test/external-project-2.12/integration-test/pom.xml, dev/maven-plugin/src/maven-test/external-project-2.12/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/hellostream-api/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/hellostream-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-api/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/integration-test/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/pom.xml
Fixes https://github.com/playframework/play-meta/issues/78
=> Add Akka snapshots repo to maven tests

docs/manual/java/guide/cluster/PersistentEntity.md, docs/manual/scala/guide/cluster/PersistentEntity.md
Backport of #1864, since we want these changes to appear in the 1.5.x documentation
=> [1.5.x] Adds Couchbase and SQLServer. Lowers C* recommendation

cluster/core/src/main/resources/play/reference-overrides.conf, dev/reloadable-server/src/main/resources/reference.conf, docs/manual/scala/releases/Migration16.md, docs/src/test/scala/docs/home/actor/ActorServiceSpec.scala, persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala, pubsub/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/pubsub/ClusteredPubSubSpec.scala, pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java, pubsub/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/pubsub/ClusteredPubSubSpec.scala, pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala, testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
=> Akka 2.6.0-M1 small fixes

dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/playProj/app/controllers/Application.scala, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceLocatorServer.scala, docs/build.sbt, project/Dependencies.scala
Depends on #1904.
This also brings Akka 2.6.0-M2.
=> Play 2.8.0-M1

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/a/api/src/main/scala/api/FooService.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/a/impl/src/main/resources/application.conf, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/a/impl/src/main/scala/impl/FooLoader.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/a/impl/src/main/scala/impl/FooServiceImpl.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/project/Build.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/project/plugins.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/test
=> Fix akka.discovery.method in dev-mode

CONTRIBUTING.md, bin/local-pr-validation.sh
Depends on #1984.
Also, see https://github.com/playframework/playframework/pull/9374.
=> Add script to do basic validations locally

docs/build.sbt, docs/project/CrossJava.scala
Fixes #1994
refs: https://github.com/playframework/playframework/pull/9395
=> Fix Docs build for cross java compilation

docs/manual/common/guide/production/LightbendPlatform.md
This reflects the new naming scheme for these products.
=> Update Akka Add-ons to Enhancements

.travis.yml, api-tools/src/main/scala/com/lightbend/lagom/internal/api/tools/ServiceDetector.scala, bin/test-2.1x, dev/maven-plugin/src/maven-test/external-project-2.12/pom.xml, dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala, jackson/src/test/java/com/lightbend/lagom/serialization/JacksonSerializerFactoryTest.java, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, project/Dependencies.scala, project/SbtMavenPlugin.scala, service/core/client/src/main/scala/com/lightbend/lagom/internal/client/ClientServiceCallInvoker.scala, service/core/client/src/main/scala/com/lightbend/lagom/internal/client/WebSocketClient.scala, service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala, service/javadsl/client/src/main/scala/com/lightbend/lagom/internal/javadsl/client/JavadslServiceApiBridge.scala, service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/Descriptor.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/Service.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/PathParamSerializer.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/HeaderFilter.scala, service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/mocks/MockService.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala, service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/status/MetricsService.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/services/FakeServices.scala
Fast-tracked out of https://github.com/lagom/lagom/pull/1454, so that that can be a smaller PR.
=> Changes related to Scala 2.13, w/o adding 2.13

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/resources/application.conf, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/resources/application.conf, docs/manual/java/releases/Migration16.md, docs/manual/scala/releases/Migration16.md, persistence/core/src/main/resources/play/reference-overrides.conf
=> Set ddata as default

persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterDistribution.scala
This is now [default behavior in Akka Cluster Sharding](https://github.com/akka/akka/pull/24669).
=> Remove unnecessary role validation

docs/manual/java/guide/cluster/ReadSideCassandra.md, docs/manual/scala/guide/cluster/ReadSideCassandra.md
xternal links caused `301` which we don't accept.
=> Fix external links

build.sbt, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
=> Fix flaky CassandraClusteredPersistentEntitySpec

docs/manual/common/gettingstarted/LagomExamples.md, docs/manual/common/guide/production/LightbendPlatform.md, docs/manual/java/guide/cluster/PersistentEntity.md, docs/manual/scala/guide/cluster/PersistentEntity.md
=> Remove reference to archived sample applications

docs/manual/common/gettingstarted/LagomExamples.md, docs/manual/common/guide/production/LightbendPlatform.md, docs/manual/java/guide/cluster/PersistentEntity.md, docs/manual/scala/guide/cluster/PersistentEntity.md
Backports #1944. Should also include #2115 before merging.
=> [1.5.x]: Change most live references to lagom-recipes to lagom-samples

docs/build.sbt, persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/testkit/AbstractEmbeddedPersistentActorSpec.scala, project/Dependencies.scala, pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/Notification.java, pubsub/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/pubsub/ClusteredPubSubSpec.scala, pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/Notification.scala, pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala
https://discuss.lightbend.com/t/akka-2-6-0-m5-released/4714
=> Update to use Akka 2.6.0-M5

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/project/plugins.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/test, dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/test
=> Replace DynamicProjectAdder with sbt.AutoPlugin's extraProjects

persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala, projection/core/src/main/resources/reference.conf, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerCoordinator.scala, projection/core/src/main/scala/com/lightbend/lagom/projection/State.scala, projection/core/src/test/scala/com/lightbend/lagom/internal/cluster/projections/ProjectionStateSpec.scala, service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/TopicProducerActor.scala
Fixes #2120
Also fixes some low-hanging fruits
Resolves #2122
Resolves #2126
=> Adds flag to enable/disable projection auto-start

build.sbt
Some artifacts had `crossScalaVersions` with `2.12` and `2.13`.
=> Maven subprojects should not cross publish

.circleci/config.yml, build.sbt, cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusterDistributionSpec.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/project/build.properties, persistence-cassandra/javadsl/src/multi-jvm/resources/logback.xml, persistence-cassandra/scaladsl/src/multi-jvm/resources/logback.xml
Starting an experiment with Circle CI.
=> Add Circle CI configuration

.circleci/config.yml
Multi-JVM was running multiple times for different jobs.
=> Isolate multi-jvm job for jdk11

docs/manual/java/releases/Migration16.md, docs/manual/scala/releases/Migration16.md
See https://github.com/lagom/lagom-samples/pull/90#issuecomment-523462516
=> Sbt 1.2.8 is now required (1.1.0 won't load)

.travis.yml
=> Use adopt@1.11.0-4 in TravisCI

.circleci/config.yml
=> Fix circleCI jabba jdk11 resolution

cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusterDistributionSpec.scala
Sometimes `ClusterDistributionSpec` fails because `JVM-x` completes and shuts down before `JVM-y` had the chance to run their local assertions. This can cause entities to re-shuffle so assertions in `JVM-y` don't hold. It can also cause other low-level Akka Cluster issues producing exception/timeout/failures in `JVM-y` leading to test failures.
If we hold the node termination with a barrier we may mitigate this issue. 
This PR doesn't aim to solve all causes for `ClusterDistributionSpec` flakiness.
=> Don't shutdown a node until other nodes have completed their assertions

testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ReadSideTestDriver.java
Fixes #2140 
Unblocks https://github.com/lagom/lagom-samples/pull/60
=> Align ReadSideTestDriver Java implementation with scaladsl (non-blocking)

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala, projection/core/src/main/resources/reference.conf, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionConfig.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerConfig.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerCoordinator.scala
Built on top of #2229
Fixes #2130
=> Make projections configurable

.circleci/config.yml, bin/test-sbt
=> Publish all version of server-containers

.circleci/config.yml, bin/test-sbt, build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/build.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/api/HelloService.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloCommand.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloEntity.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloEvent.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloModule.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloServiceImpl.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/HelloState.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/readsides/AbstractReadSideProcessor.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/readsides/StartedProcessor.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/java/com/example/hello/impl/readsides/StoppedProcessor.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/main/resources/application.conf, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/test/java/com/example/hello/impl/HelloServiceTest.java, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello/src/test/resources/logback.xml, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/project/Build.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/project/plugins.sbt, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/test
=> Lagom projection scripted tests (javadsl)

docs/manual/java/guide/cluster/Projections.md, docs/manual/java/guide/cluster/index.toc, docs/manual/java/releases/Migration16.md, docs/manual/scala/guide/cluster/Projections.md, docs/manual/scala/guide/cluster/index.toc, docs/manual/scala/guide/services/ScalaComponents.md, docs/manual/scala/releases/Migration16.md
=> Ref docs for Projections

cluster/core/src/main/java/com/lightbend/lagom/internal/cluster/protobuf/msg/ClusterMessages.java, docs/build.sbt, docs/manual/java/guide/cluster/code/docs/home/persistence/Post4Test.java, docs/manual/scala/guide/advanced/code/IntegratingNonLagom.scala, persistence/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/protobuf/msg/PersistenceMessages.java, persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/protobuf/PersistenceMessageSerializer.scala, persistence/scaladsl/src/main/java/com/lightbend/lagom/internal/scaladsl/persistence/protobuf/msg/PersistenceMessages.java, persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/protobuf/PersistenceMessageSerializer.scala, project/AkkaSnapshotRepositories.scala, project/Dependencies.scala, project/Doc.scala, project/Protobuf.scala, project/plugins.sbt, projection/core/src/main/java/com/lightbend/lagom/internal/projection/protobuf/msg/ProjectionMessages.java
Supersedes #2267 but since I'm not sure this is correct I'm sending as a separate PR.
=> Bump Play and Akka to latest Milestones (remove old protobuf v2)

build.sbt, project/Doc.scala, projection/core/src/main/resources/reference.conf, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala, projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerCoordinator.scala, projection/core/src/main/scala/com/lightbend/lagom/projection/ProjectionSerializable.scala, projection/core/src/main/scala/com/lightbend/lagom/projection/State.scala, projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala, projection/core/src/test/scala/com/lightbend/lagom/internal/cluster/projections/ProjectionStateSpec.scala, projection/javadsl/src/main/java/com/lightbend/lagom/javadsl/projection/Projections.java, projection/javadsl/src/main/scala/com/lightbend/lagom/javadsl/projection/ProjectionRegistryModule.scala, projection/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/projection/ProjectionComponents.scala, projection/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/projection/Projections.scala
Fixes #2048 
... and randomly documents some areas f the internal API too :-)
=> API docs for projections

.travis.yml
See https://github.com/playframework/playframework/pull/9688
=> Fix Travis: Update AdoptOpenJDK

docs/manual/common/concepts/ComponentTechnologies.md, docs/manual/common/guide/logging/SettingsLogger.md, docs/manual/java/guide/logging/Logging.md, docs/manual/scala/guide/logging/Logging.md
These sites are phasing out SSL.
=> Switch Logback and SLF4J links to http

docs/manual/scala/guide/cluster/DomainModelling.md, docs/manual/scala/guide/cluster/PersistentEntity.md, docs/manual/scala/guide/cluster/index.toc
=> [WIP] Domain modelling with Akka Persistence Typed

project/Dependencies.scala
=> Adds a transitive dep to akka testkit typed to Lagom's persistence-tk

dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
* fix off-by-one in attempt counting
* cache seen stacktraces so they're only printed once
* use time units for thread sleeps
* split input task impls out
=> Improve ScriptedTools

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Aggregate.java, dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__AggregateTest.java
see https://github.com/lagom/lagom-java.g8/pull/70#discussion_r338443244
=> Remove unnecessary argument

docs/manual/scala/guide/cluster/DomainModelling.md
This is the first intro to CQRS Aggregates with Akka Persistence Typed
I would like to finish this first part, get feedback and then finalize and merge. 
The page has a tutorial style. We have already two pages explaining the theory of ES and CQRS (that I think we should improve later) and the advantages of Event Sourcing. 
In this page, I would like to guide the users in building a CQRS Aggregate using Akka Persistence Typed.
=> Encoding a CQRS Aggregate

docs/manual/scala/guide/cluster/DomainModelling.md
* remove trait Accepted
* remove references to CartState
* added more explicit commands and events: AddItem, RemoveItem, AdjustItemQuantity
This PR implements most of the suggestions that @WadeWaldron did on #2358.
=> Some improvements on Domain Modelling docs

docs/manual/java/gettingstarted/UnderstandHello.md, docs/manual/java/gettingstarted/code/docs/javadsl/gettingstarted/helloservice/GreetingMessage.java, docs/manual/java/gettingstarted/code/docs/javadsl/gettingstarted/helloservice/HelloAggregate.java, docs/manual/java/gettingstarted/code/docs/javadsl/gettingstarted/helloservice/HelloCommand.java, docs/manual/java/gettingstarted/code/docs/javadsl/gettingstarted/helloservice/HelloService.java, docs/manual/java/gettingstarted/code/docs/javadsl/gettingstarted/helloservice/HelloServiceImpl.java, docs/manual/scala/gettingstarted/UnderstandHelloScala.md, docs/manual/scala/gettingstarted/code/GettingStarted.scala
=> Updates docs: Intro to HelloWorld using Typed Persistence

docs/manual/scala/guide/cluster/DomainModelling.md
This is incomplete, feel free to pick it on Monday and finalize.
=> Adds ClusterSharding section

build.sbt, dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala, docs/build.sbt, docs/manual/java/guide/cluster/Serialization.md, docs/manual/java/releases/Migration16.md, docs/project/plugins.sbt, jackson/src/main/resources/play/reference-overrides.conf, jackson/src/main/resources/reference.conf, jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java, project/Dependencies.scala, project/plugins.sbt
=> Update Akka 2.6 RC2 + Play 2.8 RC1

dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/resources/application.conf, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartLoader.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartLoader.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala, docs/manual/java/releases/Migration16.md, docs/manual/scala/guide/cluster/MigratingToAkkaPersistenceTyped.md, docs/manual/scala/releases/Migration16.md, docs/project/plugins.sbt
=> [docs] Migration Guide from classic Lagom Persistence to Akka Typed

project/Dependencies.scala
=> Bumps Akka management

project/Dependencies.scala
=> Add explicit dependency to reslve Akka snapshots

build.sbt, docs/manual/java/guide/advanced/Akka.md, docs/manual/java/guide/advanced/code/build-update-akka.sbt, docs/manual/scala/guide/advanced/Akka.md, docs/manual/scala/guide/advanced/code/build-update-akka.sbt, project/Dependencies.scala, project/Tasks.scala
Similar to https://github.com/playframework/playframework/pull/9444.
=> Add Akka and Play versions to LagomVersion

docs/manual/java/guide/cluster/index.toc, docs/manual/scala/guide/cluster/DomainModelling.md, docs/manual/scala/guide/cluster/index.toc
This PR has a few minor improvements and some re-phrasings
=> Minor docs improvements and re-phrasings

project/Dependencies.scala
=> Adds explicit deps to use snapshot artifacts on nightly jobs

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md, docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md, docs/manual/scala/guide/cluster/ReadSideRDBMS.md, docs/manual/scala/guide/cluster/ReadSideSlick.md
=> Switch to new Slick domain

docs/manual/scala/guide/cluster/MigratingToAkkaPersistenceTyped.md
Fixes #xxxx
Fix small typo in MigratingToAkkaPersistenceTyped document
=> Fix typos in Akka Persistence Typed Migration Guide

.travis.yml
Particularly the Jabba/AdoptOpenJDK one, so it functions.
=> [1.4] .travis.yml: Backport fixes

docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md, docs/manual/java/guide/cluster/code/docs/home/persistence/ShoppingCartEntity.java, docs/manual/java/guide/cluster/code/docs/home/persistence/ShoppingCartServiceImpl.java, docs/manual/java/guide/cluster/index.toc, docs/manual/scala/guide/cluster/MigratingToAkkaPersistenceTyped.md, docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShoppingCart.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShoppingCartLoader.scala
This PR is also including the changes in #2431 and #2441
=> Documentation for Akka Persistence Typed (java)

dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartLoader.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-akka-persistence-typed/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-api/src/main/scala/com/example/shoppingcart/api/ShoppingCartService.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartEntity.scala, dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/shopping-cart-lagom-persistence/src/main/scala/com/example/shoppingcart/impl/ShoppingCartServiceImpl.scala, docs/manual/scala/guide/cluster/MigratingToAkkaPersistenceTyped.md
* Also changes the model in scripted tests to get closer to main guide
Supersedes #2456
=> Migration guide fixes for Scala API

docs/manual/java/guide/cluster/Serialization.md, docs/manual/scala/guide/cluster/SerializationPlayJson.md, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/AddOrder.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/AddPost.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/ItemAdded.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/OrderAdded.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/Registry.scala, docs/manual/scala/guide/cluster/code/docs/home/scaladsl/serialization/RegistryWithCompression.scala
=> Prefer using events as play-JSON samples

bin/test-code-style, project/Dependencies.scala, project/plugins.sbt
Fixes #2434
Also add & configure sbt-akka-version-check.
=> Fix akka version coherence using snapshots

project/Dependencies.scala
This already exists in `master` and `1.6.x`
=> Bumps Netty

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/registry/impl/ServiceRegistryActor.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/InternalRouterSpec.scala, dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/registry/impl/ServiceRegistryImplSpec.scala
=> Fix lookup of external https services

build.sbt, project/Dependencies.scala
* Play v2.7.4
* Play Json v2.7.4
* Akka v2.5.26
* Akka Http v10.1.11
* Play WS v2.0.8
* Jackson v2.9.10
* Jackson Databind v2.9.10.1
=> [1.5.x] Updates for 1.5.5 release

docs/manual/common/concepts/ESAdvantage.md
This broke https://travis-ci.com/lagom/lagom/jobs/263431157.  It's not a
500 any more, but a 301 to that new location, so need to change it.
=> Fix an MSDN link

docs/project/plugins.sbt, project/plugins.sbt
=> [1.6.x]: Update sbt-scalafmt to 2.3.0

build.sbt, docs/project/plugins.sbt, project/plugins.sbt
* sbt-header v5.3.1
* sbt-sonatype v3.9 plus swtich to sonatypeBundleRelease
* sbt-release v1.0.12
* sbt-bintray v0.5.5
* sbt-dependency-graph v0.9.2
* sbt-whitesource v0.1.18
* sbt-lightbend-markdown v1.8.0
=> Update sbt plugins

docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md, docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md
=> Link to akka persistence typed testing

docs/manual/java/guide/cluster/Projections.md, docs/manual/java/releases/Highlights15.md, docs/manual/java/releases/Highlights16.md, docs/manual/java/releases/index.toc, docs/manual/scala/guide/cluster/Projections.md, docs/manual/scala/releases/Highlights15.md, docs/manual/scala/releases/Highlights16.md, docs/manual/scala/releases/index.toc
=> What's new in Lagom 1.6?

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
https://github.com/playframework/playframework/pull/9511 moved some SQL-content around. Links got a bit scrambled.
=> Fix broken link

build.sbt, docs/build.sbt, docs/project/build.properties, project/Dependencies.scala, project/build.properties
Bring fixes from Play 2.6.24 and 2.6.15.
=> [1.4.x]: Use Play 2.6.25

docs/manual/java/guide/cluster/ReadSideCassandra.md
(Undoes b3a7762039fc5debf1fed55a5203f0d71b00252c.)
=> Datastax URLs are archived again..

.circleci/config.yml, .travis.yml, build.sbt, project/CrossJava.scala, project/Doc.scala, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/ServiceCall.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/security/UserAgentHeaderFilter.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/MessageHeader.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/MessageProtocol.java, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/ServiceCall.scala
lagom port of https://github.com/playframework/playframework/pull/9923
=> Default Travis to Java 11 and support Java 8

project/Dependencies.scala
Related https://travis-ci.com/lagom/lagom/jobs/273684155#L1242
=> Explicit dependency for CRON builds using Akka snapshot versions

docs/manual/common/guide/devmode/KafkaServer.md
Fixe typo in the first sentence of the JVM options paragraph.
Fixes #xxxx
=> Fixed typo in KafkaServer.md

bin/local-pr-validation.sh
It's a continuation of https://github.com/lagom/lagom/pull/2581
=> Fix commands for using scalafmt plugin

akka-service-locator/core/src/main/resources/reference.conf, akka-service-locator/core/src/main/scala/com/lightbend/lagom/internal/client/ServiceNameMapper.scala, akka-service-locator/core/src/test/scala/com/lightbend/lagom/internal/client/ServiceNameMapperSpec.scala, docs/manual/common/guide/production/code/akka-discovery-config-examples.conf, docs/manual/java/guide/production/AkkaDiscoveryIntegration.md, docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
=> Allow per service port name and protocol overrides

persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala, service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/TopicProducerActor.scala
(small improvement, nothing fancy)
=> Replace the deprecated .fromFuture() with .future()

docs/manual/java/guide/broker/MessageBrokerApi.md, docs/manual/scala/guide/broker/MessageBrokerApi.md
Small improvement to help discover the `Projections` API
=> Cross-link topic production with Projections docs

docs/manual/scala/gettingstarted/UnderstandHelloScala.md
=> Fix urls in docs/manual

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
(Has been removed in Play master.)
=> LagomPlugin: inline PlaySettings.manageClasspath

dev/maven-plugin/src/maven-test/start-all-2.12/hellostream-impl/pom.xml, dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-impl/pom.xml
Fixes #1968 
To disable netty gateway during maven test
=> Issue-1968 | Disable netty http gateway in the maven tests

service/javadsl/kafka/server/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslRegisterTopicProducers.scala, service/scaladsl/kafka/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslRegisterTopicProducers.scala
Fixes #2646 
Throw NPE when passing null instances to topic producer
=> Throw NPE when passing null instances to topic producer

project/Dependencies.scala
Backport #2663
Fixes 
```
[error] java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:19)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:341)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:315)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:176)
[error] 	at …
```
=> Update play-file-watch to 1.1.12 (bp #2663) (1.6.X)

project/Dependencies.scala, service/core/client/src/main/scala/com/lightbend/lagom/internal/client/CircuitBreakersPanelInternal.scala, service/javadsl/client/src/test/java/com/lightbend/lagom/internal/javadsl/client/CircuitBreakersPanelImplTest.java
=> #2660 Exception whitelist doesn't work on CircuitBreakersPanel (Javadsl). The failure metric of circuit breakers is incorrect.

persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala, persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraPersistenceSpec.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala, project/Dependencies.scala
Not fixing a specific test failure but some improvements to the tests:
* logback test dependency for cluster-core
* speed up Cassandra read-side tests
=> Test improvements

docs/manual/java/gettingstarted/JavaPrereqs.md
Fixes CI link validation error
=> Backport of fix for http link redirecting to https

docs/manual/java/releases/Migration15.md, docs/manual/scala/releases/Migration15.md
=> Document Lagom 1.5.3 build breaking change

project/Dependencies.scala
Refs https://github.com/lightbend/scala-team/issues/139#issuecomment-590230696
=> Enforce some akka deps for cron/snapshot builds

docs/manual/java/gettingstarted/GettingStartedSbt.md, docs/manual/scala/gettingstarted/IntroGetStarted.md
Refs https://github.com/lagom/lagom-scala.g8/issues/78
=> Removes reference to non-existent lagom-version

docs/manual/java/guide/production/ProductionOverview.md, docs/manual/scala/guide/production/ProductionOverview.md
=> [1.5 backport] docs: fix links to etcd site

bin/test-documentation
(cherry picked from commit 255b1bd68b81b51dd7d84ba9da7b0e6de20c3ac4)
=> docs: disable link checking for 1.6.x

bin/test-documentation
=> docs: disable link checking for 1.5.x

.mergify.yml
=> Add Mergify action for backporting to 1.6.x by label `status:needs-backport`

service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala
Fixes #2796 
_NOTE:_ Need backport to `1.6.X`
=> #2796 Different behavior in `maybeLogException`

projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala
=> TestProbe should ignore all but tagName001 messages

cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/MultiNodeExpect.scala, projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala
=> Configure 'ignoreMsg' before starting projections

docs/manual/scala/gettingstarted/UnderstandHelloScala.md
Fixes inverted `[]()` in links.
=> Minor link syntax fix in doc

project/Dependencies.scala
=> Downgrade Cassandra driver to plugin's version

build.sbt, persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala, persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala, persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala, persistence-jdbc/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala, persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala, persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickClusteredPersistentEntitySpec.scala, persistence/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, persistence/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala, project/Dependencies.scala
=> [1.6.x] Fixed ports for DB multi-jvm tests (bp 2863)

project/Dependencies.scala
=> Downgrade Cassandra driver to plugin's version (bp #2884)

persistence/core/src/main/resources/reference.conf
Refs https://discuss.lightbend.com/t/states-are-not-being-snapshotted/6633
=> Adds note wrt settings scope

.travis.yml
As seen in https://github.com/playframework/playframework/pull/10330/files
Refs https://github.com/lagom/lagom/issues/2777
=> Download Jabba from stable link. Cache the correct folder

service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
=> Fix master akka 2.6.7 compile error

docs/manual/java/releases/Migration16.md, docs/manual/scala/releases/Migration16.md
Fixes #2927
⚠️ Need forward to `master`
=> #2927 Document Jackson-CBOR issues upgrading to 1.6.3

project/Dependencies.scala
=> Update akka-http, akka-http-core, ... to 10.1.12 (bp #2872)

bin/local-pr-validation.sh
=> Add checkAkkaModuleVersions to local-pr-validation script

service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
This reverts commit 9dd29c5aaec07dc6c60eac78fdc6ba07c6e0544a.
To test if https://github.com/akka/akka/pull/29341 had the desired effect
Fixes #xxxx
=> Revert "Fix compile error"

build.sbt
=> build: allow publishLocal for sbt-scripted-library

build.sbt, persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala, testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala, testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala
This reverts commit 4a0891883fda5c69031ab52c908eebed50b1769f.
References #2947
All credit goes to @ihostage.
=> Deal with SlickProvider being more lazy (than before)

docs/manual/scala/guide/cluster/PersistentEntity.md, persistence/scaladsl/src/main/mima-filters/1.6.3.backwards.excludes, persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala, persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala, testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriver.scala
* missing in scaladsl
* added thenPersistAndRun and thenPersistAllAndRun
Refs #1309
=> Add after persist callback with updated state parameter, #1309

persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/PersistentEntityActor.scala, persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntity.scala, persistence/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/TestEntity.java, persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractPersistentEntityActorSpec.scala, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala, testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriver.scala
Corresponding to scaladsl https://github.com/lagom/lagom/pull/2985
Refs #3002
Refs #3003 (the missing docs)
=> add onUnhandledCommand in javadsl.PersistentEntity, #3002

.travis.yml
Manual backport of #2908 
References #2777
=> [1.5.x] Download from a stable link. Cache the binary

bin/scriptLib
=> Run cron builds against latest released Akka version

bin/scriptLib
This reverts commit e8291a6e
This reverts commit 3062eae5
Fixes #3056
=> #3056 - compilation error TestTopicFactory

docs/manual/java/gettingstarted/UnderstandHello.md
Fixes wrong use of paranthesis, which renders the page strangely.
Fix rendering.
Found broken markup tags.
No
=> Fix markup in UnderstandHello.md

.mergify.yml
=> Labeling for Scala Steward PR's

persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/AwaitPersistenceInit.scala
=> don't run awaitPersistenceInit for JDBC

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TooManyRequests.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportErrorCode.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportException.java, service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/Unauthorized.java, service/javadsl/api/src/test/scala/com/lightbend/lagom/javadsl/api/transport/TransportExceptionSpec.scala, service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala, service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/Exceptions.scala, service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ExceptionsSpec.scala
Adding to API some useful HTTP codes and related exceptions.
=> Add `Unauthorized` and `TooManyRequests` codes and exceptions

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
Fixes handling of AssertionError from zinc compilation.
Same as https://github.com/playframework/playframework/pull/10458 
Related https://github.com/sbt/sbt/issues/5911
=> sbt-plugin: handle AssertionError from zinc compilation

.travis.yml
Refs https://github.com/lagom/lagom/pull/3078
=> Travis: always flush and rehydrate the cache

persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java, persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRef.scala
Adds a little bit more context when sending command to entity fails. Most common case is `AskTimeoutException`, but will cover other kind of exceptions as well. 
Note, the exception stack trace itself is not being logged.
=> log command type and entity id on ask exception

bin/scriptLib
Set the `first-time-bucket=yesterday` for CI tests on Cron schedule.
Refs https://github.com/lagom/lagom/issues/3027#issuecomment-704808821
=> CI: Scripted test in Cron: set first-time-bucket

docs/manual/scala/guide/build/UpgradingAkkaPlay.md, docs/manual/scala/guide/build/index.toc
=> Document how to upgrade akka/play

dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-javadsl/src/main/resources/application.conf, dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-scaladsl/src/main/resources/application.conf
Refs #3027 
Speed up projections. See https://github.com/lagom/lagom/issues/3027#issuecomment-704808821
=> [#3027] Bump first-time-bucket value

build.sbt, project/plugins.sbt
Inspired by supporting BOM for Akka and Play.
=> Maven BOM for Lagom

.github/workflows/pull-requests.yml
Only so we can "activate" actions on this repo.
=> Basic github actions workflow

.scala-steward.conf
=> Update scalasteward settings

persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala, project/plugins.sbt
=> eagerly init SlickProvider

.github/workflows/dependency-scanning.yml
=> Dependency scanning workflow: fetch full history

project/Dependencies.scala, project/Doc.scala
=> Scala 2.12.18, Scala 2.13.11

project/build.properties
Last release in the sbt 1.3 line.
sbt 1.4 changed the symbolic API significantly and requires more attention.
=> sbt 1.3.13 (was 1.3.3)

README.md
* [ x] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [ x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x ] Have you updated the documentation?
This PR adds a deprecation notice the the project readme along with alternative suggestions.
=> Update README.md to include deprecation notice
