docs/manual/guide/production/ConductR.md

There was a problem where it wanted to download the snapshots of Lagom. It will now use the version in accordance with the Lagom plugin. The documentation w.r.t. to the updated plugin has been changed accordingly.

Updated lagom bundle

---

build.sbt

I think following root jar is empty and unnecessary.
http://repo1.maven.org/maven2/com/lightbend/lagom/lagom_2.10/1.0.0-M1/
There are same settings in playframework and akka.
- https://github.com/akka/akka/blob/v2.4.2/project/AkkaBuild.scala#L397-L401
- https://github.com/playframework/interplay/blob/1.1.2/src/main/scala/interplay/PlayBuildBase.scala#L258-L260

disable publish settings of root project

---

docs/build.sbt
docs/project/plugins.sbt
docs/theme/src/main/scala/lagom/LagomMarkdownTheme.scala
docs/theme/src/main/twirl/lagom/documentation.scala.html

This puts a link at the bottom of the page to the original markdown source for the page, to encourage people that find errors to fix them.  Also the upgrade to lightbend-markdown 1.3.0 fixes the issue in the navigation where the home section is called "HOME.HTML".

Added docs source URL

---

samples/chirper/project/plugins.sbt

I think the sbt-plugin in the chirper sample has the wrong version number.

Use correct version of sbt-plugin in chirper

---

.github/PULL_REQUEST_TEMPLATE.md
WorkingWithGit.md

Pull request template pointed to Play Framework for "working with git" and mentioned Typesafe CLA instead of Lightbend
Adds WorkingWithGit.md to base directory, changes names and references to Lagom / Lightbend.
Sooner the better...

Make template lagom specific

---

README.md

It appears not everyone can easily locate the link to the Gitter chat in the
README, hence I thought about adding a gitter badge at the top to improve
discoverability. As I was doing this, I've also added a travis badge.
Furthermore, I've added a link to the contributors gitter channel.

Added gitter and build badges in README

---

build.sbt

Fixes #26
Fix 100% CPUs usage when executing `runAll`.
The Netty 4.0.33 dependencies have to be excluded one-by-one because exclusion
rules do not work with maven dependency resolution.

Excluding netty 4.0.33 one-by-one to fix 100% CPUs usage.

---

docs/manual/guide/production/ConductR.md

Changes `sbt-lagom-bundle` in docs to 1.0.3
Also one additional sentence is added to the ConductR doc to explain on which IP address and port the running Lagom bundle is accessible.

Bump sbt-lagom-bundle to 1.0.3

---

docs/manual/guide/production/ConductR.md

Fixed typos on ConductR Documentation page.

Fixed typos on ConductR Documentation page

---

dev/cassandra-registration/src/main/scala/com/lightbend/lagom/internal/server/CassandraModule.scala
dev/play-integration/src/main/scala/com/lightbend/lagom/play/LagomPlayModule.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all/b/src-b/main/java/api/FooService.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all/c/src-c/main/java/api/FooService.java
dev/service-locator/src/main/java/com/lightbend/lagom/discovery/impl/ServiceRegistryImpl.java
dev/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceRegistryActor.scala
dev/service-locator/src/main/scala/com/lightbend/lagom/discovery/UnmanagedServices.scala
dev/service-locator/src/test/scala/com/lightbend/lagom/discovery/impl/ServiceRegistryImplSpec.scala
dev/service-registry-client/src/main/java/com/lightbend/lagom/internal/registry/AbstractRegisteredService.java
dev/service-registry-client/src/main/java/com/lightbend/lagom/internal/registry/RegisteredService.java
dev/service-registry-client/src/main/java/com/lightbend/lagom/internal/registry/ServiceRegistry.java
dev/service-registry-client/src/main/java/com/lightbend/lagom/internal/registry/ServiceRegistryService.java
dev/service-registry-client/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryModule.scala
persistence/src/main/java/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraContactPoint.java
persistence/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraConfig.scala
persistence/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistenceModule.scala
persistence/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraConfig.scala
server/src/main/scala/com/lightbend/lagom/internal/server/ServerModule.scala
testkit/src/main/scala/com/lightbend/lagom/internal/testkit/TestServiceLocator.scala
testkit/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala

This PR is based on the feedback provided by @patriknw on https://github.com/lagom/lagom/pull/53.
In a nutshell, it makes `CassandraConfig` part of the Java API. Because of that, a couple more refactoring were needed:
* Java API classes should not leak Scala types such as `Pair` and `Set`, and
* `URI` should be used instead of plain `String`.
Refer to the commit messages for more details.

Moved CassandraConfig to be part of the Java API

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt

As explained in the related ticket, adding the `Defaults.baseClasspaths`
settings to the `DevRuntime` ivy configuration, was preventing the update cache
to properly work, and effectively cause full dependency resolution to be
triggered every time the `runAll` task was evaluated.
The fix implemented in this commit is to simply scope dependencies needed only
during development to the `DevRuntime` configuration, instead of adding tasks to
the configuration.

Avoid redefining sbt update task for dev runtime configs. Fix #74

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala

The content of the sbt key `lagomServiceLocatorHostname` was actually not a
hostname. Renaming it `lagomServiceLocatorUrl` makes sense.

Renamed sbt key lagomServiceLocatorHostname to lagomServiceLocatorUrl

---

api/src/main/scala/com/lightbend/lagom/internal/api/Path.scala
service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockService.java
service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockServiceImpl.java
service-integration-tests/src/test/scala/com/lightbend/lagom/it/MockServiceSpec.scala

Query parameters weren't being added to client requests, this ensures they are.

Ensure query params get added to client requests

---

docs/manual/guide/production/ConductR.md

Corrected ConductR sbt plugin name in documentation
review by @markusjura

Corrected ConductR sbt plugin name in documentation

---

api/src/main/java/com/lightbend/lagom/javadsl/api/Service.java
api/src/main/scala/com/lightbend/lagom/internal/api/ScalaSig.scala
api/src/main/scala/com/lightbend/lagom/internal/api/ServiceReader.scala
api/src/test/scala/com/lightbend/lagom/api/mock/ScalaMockService.scala
api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala

Lagom can now consume Service declaration in the form of a Scala trait, which
was not possible before this commit.
This commit only intends to improve usability of Scala with the Lagom Java API.

Added support for declaring services using a Scala trait

---

api/src/main/java/com/lightbend/lagom/javadsl/api/ConfigurationServiceLocator.java
api/src/test/scala/com/lightbend/lagom/javadsl/api/ConfigurationServiceLocatorSpec.scala
build.sbt
client/src/main/scala/com/lightbend/lagom/internal/client/WebSocketClient.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/Servers.scala
dev/service-locator/src/main/java/com/lightbend/lagom/discovery/impl/ServiceRegistryModule.java
dev/service-registry-client/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryModule.scala
docs/manual/guide/advanced/IntegratingNonLagom.md
docs/manual/guide/advanced/code/docs/advanced/IntegratingNonLagom.java
docs/manual/guide/advanced/index.toc
docs/manual/guide/production/Overview.md
docs/manual/guide/production/code/docs/production/ConfigurationServiceLocatorModule.java
integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java

This allows running Lagom clients external to Lagom, for example, from a JEE app.
Additionally, I created a configuration based service locator and documented it.

Added LagomClientFactory for external clients

---

api/src/main/java/com/lightbend/lagom/javadsl/api/deser/ExceptionSerializer.java
api/src/main/java/com/lightbend/lagom/javadsl/api/deser/RawExceptionMessage.java
docs/manual/guide/services/ServiceErrorHandling.md
docs/manual/guide/services/index.toc
integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
jackson/src/main/java/com/lightbend/lagom/javadsl/jackson/JacksonExceptionSerializer.java
server/src/main/scala/com/lightbend/lagom/internal/server/ServerBuilder.scala
service-integration-tests/src/test/scala/com/lightbend/lagom/it/ErrorHandlingSpec.scala

Fixes #107
Also:
* Added tests for this
* Fixed a bug when exceptions serialized to WebSocket close frames exceed the maximum control frame payload length
* Documented error handling and exception serializers

Added full details to exceptions when in dev mode

---

docs/manual/guide/cluster/code/docs/home/persistence/Post2.java

Not related to an issue
It removes duplicated "when" in a documentation sample code
"when" was written twice

Remove duplicated "when" in documentation sample

---

docs/manual/guide/production/ConductR.md

Update ConductR documentation with latest sbt-conductr 2.1.4 version.

Doc: Bump sbt-conductr to 2.1.4

---

docs/manual/guide/production/ConductR.md

The install command makes deploying a Lagom project to ConductR a breeze. The changes here describe how.
Requires https://github.com/typesafehub/sbt-conductr/pull/165 to be merged and 2.1.7 to be released.

Describe the install command

---

docs/manual/gettingstarted/Installation.md

Subsumes #120, which we couldn't merge because the PR's author didn't sign our CLA.

Corrected activator version in installation doc

---

persistence/src/main/java/com/lightbend/lagom/javadsl/persistence/Offset.java
persistence/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistenceModule.scala
persistence/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntityRegistry.scala

The current PersistentEntityRegistry API is specific to Cassandra, since it uses UUID for offsets, where Akka persistence only requires the use of Long.
This change moves the UUID version of the method to a new CassandraPeristentEntityRegistry trait, deprecates the existing method, and creates a new version of the method that uses Long offsets.
In order to keep the change binary compatible, the new method switches the order of parameters around. That's not entirely ideal, since it probably makes more sence to have the `startFrom` parameter second. However, I couldn't think of a better way, I think `eventStream` is the best name. I'm open to suggestions if someone can think of a better name or strategy to maintain binary compatibility.

Make default persistent entity offset Long

---

persistence/src/main/java/com/lightbend/lagom/internal/persistence/protobuf/msg/PersistenceMessages.java
persistence/src/main/protobuf/PersistenceMessages.proto
persistence/src/main/resources/reference.conf
persistence/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterDistribution.scala
persistence/src/main/scala/com/lightbend/lagom/internal/persistence/protobuf/PersistenceMessageSerializer.scala
persistence/src/test/scala/com/lightbend/lagom/internal/persistence/protobuf/PersistenceMessageSerializerSpec.scala
project/Protobuf.scala

This will be used by sharded read side processing to distribute the aggregate tags over the cluster.
It could be a useful utility to include in akka-cluster-sharding.
A few things that could be changed that I didn't do:
* We could ensure that the entity actors don't need to handle the `EnsureActive` message by creating the user supplied props in a our own entity actor.
* We could have the scheduled ping managed by one system actor instead of one per cluster distribution.

Added cluster distribution extension

---

dev/service-locator/src/main/java/com/lightbend/lagom/discovery/impl/ServiceRegistryModule.java
dev/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceLocatorServer.scala
dev/service-locator/src/main/scala/com/lightbend/lagom/gateway/ServiceGateway.scala

* Ensured the exception states which of the service locator and gateway didn't start, and what port it was running on.
* Ensure that when the service gateway fails to bind to the port, the exception is not wrapped in a guice creation exception, which adds a lot of noise.

Improved service locator/gateway error reporting

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala

Fixes #183.
Note I haven't added a test for this, since scripted tests are expensive, and I don't imagine this is going to regress anytime soon. I did reproduce locally, and then test that my fix fixed the problem.

Use project name to build the port map

---

build.sbt
jackson/src/main/java/com/lightbend/lagom/javadsl/jackson/JacksonSerializerFactory.java
jackson/src/main/scala/com/lightbend/lagom/internal/jackson/JacksonJsonSerializer.scala
jackson/src/main/scala/com/lightbend/lagom/internal/jackson/JacksonObjectMapperProvider.scala
service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockService.java
service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/MockServiceImpl.java
service-integration-tests/src/test/scala/com/lightbend/lagom/it/ErrorHandlingSpec.scala
service-integration-tests/src/test/scala/com/lightbend/lagom/it/MockServiceSpec.scala

Jackson is updated to 2.7.8 and Immutables is updated to 2.3.2.
These versions use an explicit mode on the `@JsonCreator` annotation.
This lets us consolidate on a single object mapper instance and remove all of the code that was previously used to select the correct one.
Fixes #172

Remove Jackson object provider hack

---

docs/build.sbt

Not applicable I assume
Don't know if there are any, happy to add (or change) them if there are.
N/A
This way it skips a step, making it 1 click to edit rather than 2.
I mentioned to @SethTisue that the ENSIME website (https://ensime.github.io/) has an [EDIT] button on each page, and he mentioned that the Lagom docs does as well, except it's a 2 click process.
* #15 introduced docs source URL to Lagom
* typesafehub/lightbend-markdown@9d49952d6c9eea0a97e5ec5abf9e0d74aa6ebef0 introduced docs source URLs to the plugin

Change docs source URL to edit

---

persistence/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/TestEntity.java
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
persistence/scaladsl/src/test/scala/docs/home/scaladsl/persistence/Post.scala
testkit/src/test/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriverCompatSpec.scala

* State/Behavior is passed as parameter to the functions
instead of having an accessor in the PersistentEntity.
* The reply type was lost in previous implementation.
It's difficult becuase the CommandContext can't be
passed in because the ReplyType is not known until after
pattern matching. Therefore I added the currentCommand
parameter to the reply method.
* Rewrote the TestEntity, it shows several advanced things,
such as "become" (change command handlers)
* Converted the BlogPost sample from the docs
* Removed BehaviorBuilder, Behavior is enough. Composing
behaviors is possible.

Improve PersistentEntity, #1

---

build.sbt
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceTest.java
dev/maven-plugin/src/maven-test/start-all/helloworld-impl/src/test/java/sample/helloworld/impl/HelloServiceTest.java
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
persistence-cassandra/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/testkit/TestUtil.scala
persistence-cassandra/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence-cassandra/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
persistence-cassandra/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/testkit/TestUtil.scala
service-integration-tests/src/test/java/com/lightbend/lagom/it/mocks/PersistenceServiceTest.java
testkit/src/main/scala/com/lightbend/lagom/internal/testkit/TestServiceLocator.scala
testkit/src/main/scala/com/lightbend/lagom/internal/testkit/TestTopicFactory.scala
testkit/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/src/test/java/com/lightbend/lagom/javadsl/testkit/TestServerTest.java
testkit/src/test/java/com/lightbend/lagom/javadsl/testkit/TestTopicService.java

Fixes #171
* Added support to the testkit for testing topics (doesn't use Kafka, we could add something that uses Kafka in future if we find it's needed, but for now it just plumbs the sinks/sources directly together through the message serializer).
* Removed dependence on persistence-cassandra from testkit. The testkit still allows to setup Cassandra, and will run it and shut it down for you, but because there's no longer a direct dependency in persistence-cassandra, you can also use the testkit with JDBC. There's no specific support for JDBC, but this can be added in future if for example we decide we want to support running H2 automatically for you.

Testkit changes

---

build.sbt

This mitigates a memory leak in the metrics library used by Kafka.

Fork the kafka-broker tests

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
persistence/scaladsl/src/test/scala/docs/home/scaladsl/persistence/Post.scala

* Use a partial function from State => Actions as
the selection of command and event handlers for a
given state.
* This is similar to what Fun.CQRS does
* Makes it easier to understand (read) the different
states that the entity has. Better for FSM like entities.
* Another advantage is that no special treatment is needed
during recovery to restore the behavior from the snapshot
state.

define comand and event handlers by state, #1

---

build.sbt

This allows IntelliJ IDEA's sbt project import to see the settings and apply them to the project.

Move compile options to common

---

build.sbt

Fixes #215?
I'm not sure specifically why this fixes the `KafkaApiSpec`, but it has passed 5/5 retried attempts here: https://travis-ci.org/lagom/lagom/jobs/170009375

Update akka-stream-kafka to 0.13

---

docs/manual/index.toc
docs/manual/releases/Migration12.md
docs/manual/releases/index.toc

Will need backport to the 1.2.x branch.

Lagom 1.2 migration guide

---

build.sbt

Fixes no ticket
The Lagom SPI is pure Java, and a pure Java implementation of it should not have to worry about different Scala versions.

Make lagom-spi be a java only artefact

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/AggregateEventTag.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
persistence/scaladsl/src/test/scala/docs/home/scaladsl/persistence/Post.scala

@jroper It's possible to use ClassTag for the PersistentEntityRegistry by using abstract type members in `PersistentEntity`. One drawback to be aware of is that there is no clear compilation error if one forgets to override the type members. See 0127520
```scala
override type Command = Post.BlogCommand
override type Event = Post.BlogEvent
override type State = Post.BlogState
```
There is one more challenge, which I have not solved yet. `ReadSide.register`. There we have the additional relationship `Event <: AggregateEvent[Event]`

ClassTag instead of Class parameter, #1

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRef.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/docs/home/scaladsl/persistence/Post.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriver.scala

- The return type from PersistentEntityRef.ask was inferred to
Future[Nothing]
- Add type member in ReplyType and use that in ask
- To make the CommandContext.reply method use the right type
I changed the definition of the command handlers to be per
command class, which also has several other benefits:
- no need to pass the command as parameter to reply
- defining handler per class is more natural than chaining
one single partial function
- easier to read (understand) the command handler definitions
when the types are enforced

infer right reply type in entityRef.ask, #1

---

README.md
docs/manual/gettingstarted/Installation.md
docs/manual/guide/production/ConductR.md

Pulled these documentation updates from long-ago `master`.
I believe they're all relevant to Lagom 1.0.0, but they don't appear in the 1.0.x docs on the site.
Note that the merge target is a new 1.0.x branch.

1.0.x documentation updates

---

service/javadsl/client/src/main/scala/com/lightbend/lagom/internal/client/CircuitBreakers.scala
service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java

This breaks its dependency on the `ActorSystem` configuration.
`LagomClientFactory` does not pass the full `Configuration` to the `ActorSystem` it creates (only the "akka" config) so previously, "lagom.circuit-breaker" config settings were not being picked up correctly.

Inject Configuration into CircuitBreakerConfig

---

project/Doc.scala

Fixes #246
Should be cherry-picked to 1.2.x before release.

Add new 1.2.x packages to groups

---

persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRegistry.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/docs/home/scaladsl/persistence/Post.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriver.scala

This PR is based on https://github.com/lagom/lagom/pull/233, so ignore the first commit here.
It's possible to use ClassTag for the PersistentEntityRegistry by using abstract type members in PersistentEntity. One drawback to be aware of is that there is no clear compilation error if one forgets to override the type members.
``` scala
override type Command = Post.BlogCommand
override type Event = Post.BlogEvent
override type State = Post.BlogState
```

use ClassTag in PersistentEntityRegistry.refFor, #1

---

build.sbt
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
docs/build.sbt
docs/manual/java/guide/logging/Logging.md
docs/manual/java/guide/logging/SettingsLogger.md
docs/manual/java/guide/logging/code/build-log.sbt
docs/manual/java/guide/logging/code/build-log2.sbt
docs/manual/java/guide/logging/code/docs/logging/Log4j2Example.java
docs/manual/java/guide/logging/code/log4j2-lagom-default.xml
docs/manual/java/guide/logging/code/log4j2-lagom-dev.xml
log4j2/src/main/resources/log4j2-lagom-default.xml
log4j2/src/main/resources/log4j2-lagom-dev.xml
log4j2/src/main/resources/logger-configurator.properties
log4j2/src/main/scala/com/lightbend/lagom/internal/log4j2/Log4j2LoggerConfigurator.scala

Fixes #255
This PR adds a Log4j 2 module for easy configuration of Log4j 2 as an alternative to Logback. As mentioned in #255, Log4j 2 is much faster than Logback in production logging environments amongst many other features.
I based all this on the lagom-logback module and documentation. Thanks to some added slf4j dependencies, slightly less configuration is necessary than I initially thought (e.g., adding log4j-jul to support `java.util.logging` is already provided in Lagom by jul-to-slf4j.
This adds an additional module, lagom-log4j2, which can be used instead
of lagom-logback for default logging configuration.
This relates to issue #255.

Add Log4j2 support

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
dev/maven-plugin/src/main/java/com/lightbend/lagom/maven/LagomAbstractMojo.java
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ConfigureMojo.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/RenameConductRBundleMojo.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
docs/manual/common/gettingstarted/Installation.md

* Added maven enforcer plugin to archetype to enforce at least Maven version 3.2.1.
* Added static check to mojos that, when the class is loaded, checks that the version of Maven is at least 3.2.1. This check only fails with Maven 3.1.x, prior versions don't initialise the class when loading it and fail before the check can be done.
* Improved documentation to make it clear minimum Maven version must be 3.2.1.

Improve maven incompatible version handling

---

build.sbt

Fixes #285
Sets more direct Jackson dependencies, so that they appear closer to the root of the dependency tree, causing Maven to prefer Jackson 2.7.8 over other versions pulled in by transitive dependencies.
Using a dependency range instead caused problems with sbt/ivy resolution that I was unable to fix.
This fix is for the 1.2.x branch and should be released with 1.2.1. Due to the restructuring of subprojects on master, a slightly different change will be needed there. I'll submit a separate PR later on.

Add more explicit Jackson dependencies

---

docs/manual/guide/services/Test.md
docs/manual/guide/services/code/docs/services/test/EnablePersistence.java
testkit/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala

This backports #291 (required some path review)

Docs: Cassandra and cluster are disabled by default. (1.2.x)

---

docs/manual/java/guide/services/ServiceDescriptors.md
docs/manual/scala/guide/services/ServiceDescriptors.md
docs/manual/scala/guide/services/code/ServiceDescriptors.scala
docs/manual/scala/guide/services/index.toc
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/Service.java
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/Service.scala

Also comprehensively scaladoc'd the `Service` class.
This documentation is heavily based on the Java ServiceDescriptors documentation.

Created ServiceDescriptors Scala documentation

---

service/javadsl/api/src/main/scala/com/lightbend/lagom/javadsl/api/ScalaServiceSupport.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/Service.scala

Improved the hygiene of the macros by using fully qualified references to `_root_.scala.Predef.classOf`.
See @retronym's comment [here](https://github.com/lagom/lagom/commit/0c9895695ee358362dab646153196a4748aea1b4#commitcomment-20129494).

Macro hygiene

---

docs/project/plugins.sbt

This fixes a bug where Ligtbend markdown was using the theme configured
for running the docs in development, rather than the bare theme when
generating the docs for the website, the result being that the
documentation pages are double decorated.

Upgrade Lightbend markdown

---

build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-server-disabled-but-defaults-config-still-injected/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/project/build.properties
docs/project/build.properties
project/Doc.scala
project/SbtMavenPlugin.scala
project/build.properties
project/plugins.sbt

Fixes #316
Also fixes all of the deprecation warnings other than one that uses `triggeredBy` (see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+using+%2C++or)

Update sbt to 0.13.13

---

persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/STMultiNodeSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/STMultiNodeSpec.scala
pubsub/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/pubsub/STMultiNodeSpec.scala
pubsub/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/pubsub/STMultiNodeSpec.scala
pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/ScaladslMockServiceSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

Just some style fixes I noticed while working on specs:
- Add parentheses to defs and calls (as these are methods with side effects)
- Call super.beforeAll() at the beginning of overridden beforeAll()
- Call super.afterAll() at the end of overridden afterAll()
- Avoid procedure syntax (use `: Unit =` in defs)

Ensure consistent use of before/afterAll in specs

---

persistence-jpa/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/Retry.scala

Forgot this in my previous pull request (#342)

Add private[lagom] to the Retry companion object

---

build.sbt

Fixes #364 (well, not sure, will see how it goes in CI)
This patch restores the runnability of scripted tests but it brings back a deprecation warning on sbt.

Restore execution of scripted tests.

---

persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntityRegistry.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRegistry.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala

There was a change in Lagom 1.3 to use the new Akka Offset type for journal queries.
This introduced a bug when resuming JDBC read side processors: rather than starting with the first unseen event, it's re-processing the last seen event.
This is caused by the way that akka-persistence-jdbc is handling offset in queries: it treats the offset as an _inclusive_ bound https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalQueries.scala#L50
In released versions of Lagom, this is accounted for by incrementing sequence offsets before making the query, but in Lagom 1.3 this was removed.
Here is the specific change https://github.com/lagom/lagom/commit/58c900eda2ed66552bb93653e3769d44db850e43#diff-b00d9e70042b9ecf936fb5cc01bb8d1fL123 …

[1.3.0-M1] Fix off-by-one error in the JDBC event journal query

---

docs/manual/common/concepts/Technologies.md

The following sentence looks a little old, and may not be relevant anymore. I'm reading the documentation from start to finish at the moment, and this feels a little out of place and dated:
"The first version of Lagom provides a Java API for writing microservices.  Before long, a subsequent version will add a Scala API."

Propose to remove old sentence

---

docs/manual/java/gettingstarted/GettingStartedSbt.md

This is the Java equivalent to the change in #374.

Fix a small typo in the Java getting started guide

---

persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImpl.java
persistence-jpa/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/jpa/TestEntityJpaReadSide.java
persistence-jpa/javadsl/src/test/resources/META-INF/persistence.xml
persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImplSpec.scala

This solves a problem that I found on Thursday when creating the schema from a `globalPrepare` hook rather than configuring Hibernate/JPA to do it automatically (which is not multi-node friendly).
What I originally thought was a thread visibility bug in Hibernate's JPA implementation turned out to actually be caused by different context class loaders on different Slick DB I/O threads. I couldn't quite work out _why_ different Slick threads have different context class loaders, but I suspect that it has to do with when the threads are spawned. It doesn't look like Slick tries to manage the context class loader in any way.
This solves the problem by wrapping any block passed to `JpaSession.withTransaction` with logic to propagate the context class loader to the DB I/O thread for the …

Set the context class loader for JPA transactions

---

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceRegistryActor.scala

In Dev mode, every Service registration attempt will trace (on log level) name, acl's and URI.

Adds a debug trace on the Dev mode Service Registry regsitrations

---

persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImpl.java
persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImpl.java
persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/jpa/JpaPersistenceModule.java
persistence-jpa/javadsl/src/main/resources/reference.conf

This publishes it in the API documentation so people know that it can be disabled.

Move JpaPersistenceModule to the public package

---

service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/ExceptionSerializer.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/Exceptions.scala

This adds documentation to transport exceptions and their serialization/deserialization.  It also makes it simple to allow deserialization of custom transport exceptions by providing a method to override.
See https://groups.google.com/d/msg/lagom-framework/scpwZygHkCE/YtgMTAz8GgAJ for context.

Documents and improves transport exceptions

---

build.sbt
service/scaladsl/api/src/main/scala/com/lightbend/lagom/internal/scaladsl/api/broker/TopicFactory.scala
service/scaladsl/kafka/server/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/LagomKafkaComponents.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationSpec.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/TestTopicComponents.scala

Fixes #414.
When no topic publisher is mixed into an application cake, this ensures that the application won't start.

Added check that a topic publisher is present

---

docs/manual/guide/services/Test.md

Fixes a small typo in the documentation

pluralize test -> tests

---

build.sbt

The api-tools project was bringing in a dependency on server-javadsl,
which prevented it from working with Scala projects. This fixes the
scope so that it's only depending on it in Test.

Remove server-javadsl dependency from api-tools

---

docs/manual/java/guide/cluster/PersistentEntity.md
docs/manual/scala/guide/cluster/PersistentEntity.md

online auction uses the read-only command for precisely the example I gave - bid arriving after auction closed. Until I saw that I had fixed read-only in my mind as being just for queries.

slight expansion of docs on read-only command

---

docs/manual/guide/devmode/detailedTopics/CassandraServer.md

While creating lagom maven project you should use lagom version 1.2.2 or above if you want to connect to an externally running Cassandra instance.

[MINOR] Update CassandraServer.md

---

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStore.scala
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala

Fixes #449
Should also be back ported to 1.2.x.

Allow disabling JDBC offset table auto-creation

---

docs/manual/scala/guide/build/LagomBuild.md
docs/manual/scala/guide/services/code/ServiceClients.scala

I signed the Lightbend CLA online
Fixed mentioning Java source when it should be Scala sources
Fixes error message on 1.3.x/scala/ServiceClients.html "Unable to find label circuit-breaker in source file code/ServiceClients.scala"
Fixes Documentation issues

Fixed mentioning Java source i.s.o Scala sources and missing reference to code sample

---

dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/util/PropertiesLoader.scala
dev/maven-plugin/src/main/maven/plugin.xml
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
docs/manual/common/guide/devmode/KafkaServer.md
docs/manual/common/guide/devmode/code/build-kafka-opts.sbt

Fixes #403.
I updated the docs and removed the checks to try and force it to be a relative path - in neither sbt nor Maven should relative paths ever be used, paths should always be absolute, explicitly building off other paths (basedir/baseDirectory).

Loaded Kafka properties file from the filesystem

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/a/src/main/java/com/example/A.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/a/src/main/java/com/example/AImpl.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/a/src/main/java/com/example/AModule.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/a/src/main/resources/application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/project/plugins.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/test
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/a/src/main/resources/application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/a/src/main/scala/com/example/A.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/project/plugins.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/test
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
docs/manual/java/guide/build/MultipleBuilds.md
docs/manual/java/guide/build/code/multiple-builds.sbt
docs/manual/scala/guide/build/MultipleBuilds.md
docs/manual/scala/guide/build/code/multiple-builds.sbt

Fixes #426.
Java projects needed to have the Java dev mode dependencies added, but there was no way in the existing API to tell if an external project was a Java project or a Scala project, so I deprecated the existing method and created lagomExternalJavadslProject and lagomExternalScaladslProject methods.
Scripted tests for both the javadsl and scaladsl cases have been created.

Fixed lagomExternalProject

---

docs/manual/java/index.toc
docs/manual/java/releases/Migration13.md
docs/manual/scala/index.toc
docs/manual/scala/releases/Migration13.md
docs/manual/scala/releases/index.toc

Finished the Java 1.3 migration guide.
Added a Scala 1.3 migration guide, which is notes to help for migrating from a Java Lagom 1.2 app to a Scala Lagom 1.3 app.

Finished migration guides

---

docs/manual/common/guide/production/code/conductr.sbt

Update documentation to `sbt-conductr` 2.2.4. This version is supporting Lagom 1.3.0.

Update documentation to sbt-conductr 2.2.4

---

docs/manual/java/guide/production/ConductRSbt.md

The page http://www.lagomframework.com/documentation/1.3.x/java/ConductRSbt.html explains which sbt commands are available when adding the plugin `sbt-conductr`.
So far the command `cassandra-configuration:dist` was not listed there. Because we are using this command later on the page I thought it makes sense to list it there as well.
I’ve also modified the text of the other respective bullet points.

Document cassandra-configuration:dist command

---

docs/manual/java/releases/Migration13.md
docs/manual/scala/releases/Migration13.md

Fixes typos and makes small wording changes to https://github.com/lagom/lagom/pull/503
Some of these are typo fixes that should be uncontroversial, others are spelling changes to US standard (which I think is what we use in most places) and others are rewordings that I thought make things clearer, but please feel free to disagree. 😄 
Will need to be backported to the 1.3.x branch after merging.

Minor fixes to the 1.3 migration guide

---

docs/manual/java/guide/production/ConductRSbt.md
docs/manual/scala/guide/production/ConductR.md

Ported to Scala from #508.
Also fixes a small typo in the Java version.
Should be backported to 1.3.x.

Port cassandra-configuration:dist command doc to Scala

---

build.sbt
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
dev/maven-plugin/src/main/maven/plugin.xml
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
service/core/kafka/client/src/main/resources/reference.conf
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaConfig.scala
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaSubscriberActor.scala
service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/Producer.scala
service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaTopicFactory.java
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaTopic.scala
service/javadsl/kafka/server/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslRegisterTopicProducers.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/KafkaTopicFactory.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaTopic.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/LagomKafkaClientComponents.scala
service/scaladsl/kafka/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslRegisterTopicProducers.scala
service/scaladsl/kafka/server/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/LagomKafkaComponents.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

The service locator is looked up every time a connection to Kafka is made - I think this is what we want, since generally connections to Kafka are long lived, and in the case that a Kafka node dies and is restarted somewhere else, typically the stream will fail, then when it reconnects, it will need to look up from the service locator again to find out where another node is.
I modified the Kafka tests so that it will use this.
Passing configuration explicitly is still supported, by setting lagom.broker.kafka.service-name to an empty string.
Fixes #511.

Changed Kafka support to lookup Kafka from the service locator

---

service/scaladsl/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslClientMacroImpl.scala
service/scaladsl/client/src/test/scala/com/lightbend/lagom/scaladsl/client/ServiceClientSpec.scala

Issue is not registered in the bug tracking. 
Long story short, if I have method with multiple primitive params registered as a service call and I'm trying to create and use client for it, classcastexception is thrown. It happens during serialization params into path. 
Root cause is implicit numeric widening. 
```
scala> Seq(1L, 2)
res0: Seq[Long] = List(1, 2)
// All numbers have been widened to be long
scala> val anySeq: Seq[Any] = Seq(1L, 2)
anySeq: Seq[Any] = List(1, 2)
scala> anySeq(1).getClass
res1: Class[_] = class java.lang.Long
// type annotation on val doesn't help 
```
I fixed that by adding explicit type annotation to Seq.apply method in macro. Same principle demonstrated in Scala console:
```
scala> val fixedSeq = Seq[Any](1L, 2)
fixedSeq: Seq[Any] = List(1, 2)
scala> …
```

Fix issue with primitives in path

---

docs/manual/common/guide/production/code/conductr.sbt

Upgrade to sbt-conductr 2.3.0-rc.1. This version is only compatible with Lagom 1.3.x, not Lagom 1.1.x or 1.2.x.
Please cherry pick to branch 1.3.x.

Upgrade to sbt-conductr 2.3.0-RC1

---

docs/manual/guide/production/ConductRSbt.md

Upgrade to sbt-conductr 2.2.5. This version is only compatible with Lagom 1.1.x and 1.2.x, not with Lagom 1.3.x.
Please cherry pick to branch 1.1.x.

Upgrade to sbt-conductr 2.2.5

---

docs/.jvmopts

I was starting to see OutOfMemoryError when running the docs validation locally.

Increase the sbt heap in the docs subproject

---

testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/ProducerStubTest.java
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ProducerStubSpec.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/services/FakeServices.scala

Fixes #539
Test was not considering race conditions between message deliver and message polling.
Test was not considering messages from different topics can be reordered.

Test assertions only realize eventually. Messages may reorder (multi topic)

---

service/scaladsl/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslServiceClientInvoker.scala
service/scaladsl/client/src/test/scala/com/lightbend/lagom/internal/scaladsl/client/ScaladslServiceResolverSpec.scala
service/scaladsl/client/src/test/scala/com/lightbend/lagom/scaladsl/client/ServiceClientSpec.scala
service/scaladsl/client/src/test/scala/com/lightbend/lagom/scaladsl/client/TestServiceClient.scala

* adds missing feature in `ScaladslServiceResolver` to ensure all method calls have a CB setup
* adds test for added feature
* extracts `TestServiceClient` for reuse in added test.
Fixes #532

Sets circuit breaking to described settings or defaults but never None

---

docs/manual/common/guide/production/code/conductr.sbt
docs/manual/java/guide/production/ConductR.md
docs/manual/java/guide/production/ConductRMaven.md
docs/manual/java/guide/production/ConductRSbt.md
docs/manual/scala/guide/production/ConductR.md

For a Lagom system, it is not necessary anymore, to create a custom Cassandra bundle configuration with `cassandra-configuration:dist` to deploy Cassandra on ConductR.
This PR is updating the documentation accordingly. Additionally, the PR is updating:
- The ConductR documentation links to 2.0.x
- The **Run it all** section to the latest [ConductR developer page](https://www.lightbend.com/product/conductr/developer) version
- sbt-conductr version
Fixes https://github.com/lagom/lagom/issues/555.
**Please cherry pick this commit only to 1.3.x**

Doc: Remove cassandra configuration

---

docs/manual/guide/production/ConductR.md
docs/manual/guide/production/ConductRMaven.md
docs/manual/guide/production/ConductRSbt.md

For a Lagom system, it is not necessary anymore, to create a custom Cassandra bundle configuration with `cassandra-configuration:dist` to deploy Cassandra on ConductR.
This PR is updating the documentation accordingly. Additionally, the PR is updating:
- The ConductR documentation links to 2.0.x
- The **Run it all** section to the latest [ConductR developer page](https://www.lightbend.com/product/conductr/developer) version
- sbt-conductr version
**Please cherry pick this commit only to 1.1.x.**

Doc: Remove cassandra configuration (1.2.x)

---

service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationSpec.scala

Fixes #564 
Both `context.playContext.initialConfiguration` and `Configuration.load(environment)` include `akka.cluster.seed-nodes` and both set it to `SimpleConfigList([])` so for this particular issue `additionalConfiguration.configuration` must be listed last.
But user-defined configuration (by means of `application.conf`) is only available on `context.playContext.initialConfiguration` and `Configuration.load(environment)`. So a Component exploiting `additionalConfiguration` could override user-defined config values. I think that's unlikely.
I found that the [Java bundle-lib](https://github.com/typesafehub/conductr-lib/blob/7c5ccf670abf96bbba31901b56e77c219a5af48b/lagom1-java-conductr-bundle-lib/src/main/scala/com/typesafe/conductr/bundlelib/lagom/javadsl/ConductRApplicationLoader.scala …

Moves additionalConfiguration to last so it has precedence

---

build.sbt
project/Dependencies.scala

Refactored the dependencies into a separate file. This is an initial step before #528 is done so that reviewing that becomes simpler.
Often projects will pull out Seqs of dependencies, rather than Setting[Seq]. I've extracted the dependencies as Setting[Seq], as this will make it very easy to introduce more complex things in future, like when we cross build with Scala 2.12, it will be very straight forward to make the dependencies dynamic based on Scala version, no changes to build.sbt will be needed, just the dependency setting in Dependencies.scala.

Refactored dependencies into separate file

---

play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializer.scala
play-json/src/test/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializerSpec.scala

This fixes runtime exception of missing play-json serializer for versioned event with suffix `#<version number>`
- Removes versioning from manifest name to contain the same key as configured registry
- Handle missing pattern matching when migration current version is not greater than the event's version
https://groups.google.com/forum/#!topic/lagom-framework/SQnLtf-nVz8

Remove version from manifest to get serialiser from the registry

---

project/Dependencies.scala

Fixes https://github.com/lagom/lagom/issues/583 and https://github.com/lagom/lagom/issues/589
I bumped Netty to match the version that Play pulls in

Bump play version and move akka-testkit off compile scope

---

docs/manual/java/guide/cluster/PubSub.md
docs/manual/scala/guide/cluster/PubSub.md

PR #595 improved the docs by stating an alternative to PubSub when at-least-once delivery is required. That PR, though, only edited the java/ branch of docs. While reviewing the scala docs I noticed the section edited already suggested falling back to broker API in other situations and included a warning of the side-effects of falling back from PubSub to Broker API.
This needs backporting to `1.3.x` and `1.2.x` branches.

Fix docs: port to scala, add disclaimer, remove kafka ref.

---

bin/test-code-style
build.sbt
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ClassLoaders.scala
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/MavenFacade.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
project/Dependencies.scala

This change ensures the following:
* Every Lagom library depends on the same version of every dependency, so there's now no chance that using two different Lagom libraries together will cause a problem in one of them due to a different version of a transitive dependency being used.
* The libraries on our classpath when we run tests match the classpath that users will see when they depend on our libraries (assuming they don't make any other changes to it).
* If we do an upgrade that upgrades a transitive dependency, we will know, and can verify that the upgrade won't cause any problems.
While the list of libraries does look very large, it's important to realise that this is a list of dependencies used by all Lagom libraries, both at compile/runtime and in test.

Created dependency whitelist validation

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/resources/application.conf

This will help to ensure that projects won't be affected by changes to
the default keyspace configuration.
See #578
Should be backported to 1.3.x.

Configure the Cassandra keyspace in the archetype

---

LICENSE
README.md

GitHub currently doesn't recognize the LICENSE file:
https://cloud.githubusercontent.com/assets/731773/18727946/1aa7b2fa-8019-11e6-84bd-178f93bcd8ee.png
GitHub now also display useful information about the license (if recognized):
https://github.com/blog/2335-open-source-license-descriptions-and-metadata
Also IMHO the sentence in the README ist just redundant (and not part of what the APPENDIX in the license says).

Use GitHub's provided LICENSE file

---

docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogService.scala
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/JdbcBlogApplicationLoader.scala

Shows example on how to load the persistence components for JDBC, where
the code is linked from the docs and put in a separate file.
Fixes #xxxx
This PR updates the documents so that it is clear what code must be updated when using the JDBC store.
Could not find this piece of code in the documentation and this seemed the most logical place.

Example code for LagomApplicationLoader RDBMS config

---

docs/manual/common/guide/devmode/CassandraServer.md
docs/manual/java/guide/cluster/PersistentEntityCassandra.md
docs/manual/java/guide/devmode/code/build-cassandra-opts-lang.sbt
docs/manual/scala/guide/cluster/PersistentEntityCassandra.md
docs/manual/scala/guide/devmode/code/build-cassandra-opts-lang.sbt

- Describe keyspace configuration in the Cassandra persistent entity documentation
- Deprecate keyspace configuration in the build
See #578
Should be backported to 1.3.x

Document Cassandra keyspace configuration changes

---

persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraKeyspaceConfig.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraSession.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraSession.scala

This lets users know that relying on the default is deprecated, and that
they should configure keyspaces explicitly in application.conf.
See #578
This should be backported to 1.3.x.

Warn on implicit keyspace config

---

persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSide.scala

Update Scala doc in JdbcReadside.scala to remove references to the Cassandra Readside builder, which can be misleading

Remove reference to Cassandra in the JdbcReadside

---

persistence-cassandra/core/src/main/resources/reference.conf
project/Dependencies.scala

This also required introducing new session configuration settings to the read-side reference.conf. To make this easier, other settings were also reordered to match their position in the cassandra-journal configuration. Comments were also updated.

Update Akka Persistence Cassandra to 0.24

---

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
persistence-jdbc/core/src/main/resources/reference.conf

This was accidentally left out of #642

Use new Slick 3.2 DB profile classes in configuration defaults and examples

---

docs/manual/java/gettingstarted/GettingStartedMaven.md
docs/manual/java/gettingstarted/GettingStartedSbt.md
docs/manual/java/guide/build/IntellijSbtJava.md
docs/manual/scala/gettingstarted/IntroGetStarted.md
docs/manual/scala/guide/build/IntellijSbt.md

It instills confidence if the user knows it will take a bit of time for both the initial project setup and runAll. Also, in the IntelliJ instructions, when creating a Run configuration, the step should say to select "SBT Task". Fixes #653

Fixes to getting started procedures. 

---

api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/ServiceLoaders.scala
dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
docs/manual/scala/guide/services/ServiceClients.md
docs/manual/scala/guide/services/code/ServiceClients.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/ServiceLocator.scala
service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceClient.scala
service/scaladsl/client/src/main/scala/com/lightbend/lagom/scaladsl/client/ServiceLocators.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomServer.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/status/MetricsService.scala

This is related to #635 and #580. 
This PR is just some ideas to try and make MetricsProvider enabled and setup to use the default impl in scaladsl so it's easier for users. This is not meant to be merged yet.
If merged, this should be backported to `1.3.x`.

[WIP] Enable Metrics delivery by default in scaladsl

---

docs/manual/scala/guide/cluster/PersistentEntity.md

This PR fixes a typo in the documentation for PersistentEntity.

remove an extra 'the' in persistententity-doc

---

dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceManager.scala

The name of this artifact changed when the scaladsl was introduced, but the Maven plugin was never fixed to support it.

Ensure maven plugin adds right dependency for Play integration

---

build.sbt
persistence-cassandra/core/src/main/resources/test-embedded-cassandra.yaml
project/Dependencies.scala

Fixes #664 and #435.
Also includes a fix for non-standard ports in a Cassandra cluster (akka/akka-persistence-cassandra#187).

Update Akka Persistence Cassandra to 0.26

---

docs/manual/java/gettingstarted/GettingStartedSbt.md
docs/manual/scala/gettingstarted/IntroGetStarted.md

Changing the transport when using `sbt new` requires 0.13.15 which has a 
more strict syntax when parsing arguments requiring reordering.
Fixes #683
Needs backporting to `1.3.x`

Add support for HTTPS on seed-based project creation

---

service/javadsl/broker/src/main/java/com/lightbend/lagom/javadsl/broker/TopicProducer.java
service/scaladsl/broker/src/main/scala/com/lightbend/lagom/scaladsl/broker/TopicProducer.scala

Very often when creating a broker topic from tagged event-stream the same 
idiom repeats: `TopicProducer.taggedStreamWithOffset(MyEvent.Tag.allTags.toList)`.
With this change we'd get rid of the last bit so that an `AggregateEventShards` an be passed 
as an argument: `TopicProducer.taggedStreamWithOffset(MyEvent.Tag)`

Introduce a convenience method on TopicProducer for tagged streams

---

docs/manual/common/guide/devmode/CassandraServer.md
docs/manual/java/guide/cluster/PersistentEntityCassandra.md
docs/manual/java/guide/production/ProductionOverview.md
docs/manual/scala/guide/cluster/PersistentEntityCassandra.md
docs/manual/scala/guide/production/ProductionOverview.md

* specify settings are for devmode only
* document how to setup a static list of contact-points

Improves docs on Cassandra setup

---

persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/ServiceLocatorHolder.scala
persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/ServiceLocatorSessionProvider.scala
persistence-cassandra/core/src/test/scala/com/lightbend/lagom/internal/persistence/cassandra/ServiceLocatorHolderSpec.scala
persistence-cassandra/core/src/test/scala/com/lightbend/lagom/internal/persistence/cassandra/ServiceLocatorSessionProviderSpec.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraConfigProvider.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceModule.scala

This is a rewrite of #410. Thanks @tommpy
Please note #410 also introduced a change on logger timeout I didn't port since 
it was deemed unnecessary and the implemented solution needed reviewing anyway.
This PR needs backporting to `1.3.x`

Refactor the service locator holder to expose a future to avoid polling

---

service/core/kafka/client/src/main/resources/reference.conf

Add the possibility to override the Kafka service name with the environment variable `KAFKA_SERVICE_NAME`. This is a common scenario in the context of ConductR on DC/OS on which the service name needs to be overwritten to `_node-0._tcp.kafka.mesos`.
As described at https://tech-hub.lightbend.com/guides/dcos-microservices, the default approach within ConductR is to provide a custom bundle configuration in which the environment variable `KAFKA_SERVICE_NAME` is set and therefore the Kafka service name is overwritten.
This makes it also consistent with Cassandra, in which the default service name can be overwritten with the env `CASSANDRA_SERVICE_NAME`: https://github.com/lagom/lagom/blob/master/persistence-cassandra/core/src/main/resources/play/reference-overrides.conf#L41

Kafka service name override

---

docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md

This came out of a support request, and might be helpful to others migrating Lagom projects to the required Cassandra keyspace configuration.
It loops through all children of the current directory ending in "-impl" and appends the recommended configuration, using the directory name to determine the config prefix and keyspace name (translating hyphens to underscores for the keyspace). By default, it retains the keyspace name that is used in development by default (including "_impl" in the keyspace name), but has a comment explaining how to remove the "_impl" suffix.
This doesn't attempt to detect any existing keyspace configuration, so it won't work perfectly on all possible config files, but it should be helpful for people trying to do a quick migration.

Add a script to help configure Cassandra keyspaces

---

service/core/kafka/client/src/main/resources/reference.conf
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaConfig.scala
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaSubscriberActor.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

This allows at least once Kakfa consumers to batch messages, by ensuring that the zip stage of zipping the user flow with the offset doesn't backpressure on the unzip stage through the offset side of the flow when the user buffer is batching or otherwise processing messages in parallel.

Allow Kafka consumers to batch messages

---

jackson/src/main/resources/reference.conf

This fixes issue #748 and uses concatenation so that classloader order won't matter if another reference.conf is appending to the jackson-modules
Fixes #748
This allows other dependencies to be loaded that have a reference.conf that append to `lagom.serialization.json.jackson-modules`. Without this change some reference.conf files will be ignored depending the class loader order.
This was discussed in the lagom Gitter channel

Update jackson reference.conf to use concatenation

---

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ConsoleHelper.scala
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/test
docs/manual/common/guide/devmode/DevEnvironment.md
docs/manual/common/guide/devmode/code/dev-environment.sbt

Fixes #762
Note that this only includes support for sbt. Support for Maven is much more difficult, because in Maven, you can't just arbitrarily add code to your build file to download, configure and run some process. We can probably come up with a solution, possibly by allowing some scripts to be specified to be run as part of runAll startup/shutdown, but I think it requires a lot more thinking than the sbt solution, which is why I haven't attempted it here.

Added the ability add custom infrastructure services

---

persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/testkit/TestUtil.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/testkit/TestUtil.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala

Fixes #756
Edits `TestUtils` in both scaladsl and javadsl to ensure `contact-points` for all keyspaces are `127.0.0.1`.
I noticed in both API the `ServiceTest` was invoking `CassandraLauncher` without specifying the port. The code was correct (because `CassandraLauncher` is an `object`) but confusing and replaced to make it explicit.

Avoid relying on default contact-point settings

---

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/deser/PathParamSerializers.java
service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/deser/PathParamSerializer.scala
service/scaladsl/api/src/test/scala/com/lightbend/lagom/scaladsl/api/ServiceSupportSpec.scala

Add a default PathParamSerializer for Double.
It add a default PathParamSerializer for Double.
Double is a common used type in JSON.
None

Add a PathParamSerializer for Double

---

persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/NamedEntity.scala

Nothing
IMHO, `Actions.empty` function should be public because when we want to create an empty actions set, `Actions()` doesn't look like "scala like" and is not explicit enough.
When we want to create a empty List in Scala we do `List.empty`, so why not for `Actions` ?
Explained above
None

[Proposal] public Actions.empty

---

project/Dependencies.scala

This is the version that's used everywhere in Lagom other than in the transitive dependency of Cassandra. This change forces it to use that version in Cassandra, too.
This fixes a license issue: the version used by Cassandra by default is licensed under the LGPL. This uses a version licensed under Apache v2.
cc: @eed3si9n
Needs backport to 1.3.x.

Update jboss-logging to 3.3.0.Final

---

.travis-jvmopts
.travis.yml
dev/kafka-server/src/main/scala/com/lightbend/lagom/internal/kafka/KafkaLocalServer.scala
project/Dependencies.scala
service/javadsl/kafka/server/src/test/resources/logback.xml
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

Fixes #797
~I had to upgrade a few transitive dependencies in the whitelist so I suspect something could break.~
After further investigation this PR bumps `akka-persistence-cassandra` (APC) to `0.29` but it excludes the cassandra driver that APC will bring in transitively. That exclusion is required because the version of the cassandra driver APC depends on bumps Guava and Netty. While Guava doesn't seem to be causing issues, the Netty bump does cause issues with other code in Lagom (See comments in #797).

Bumps APC version to 0.29

---

project/Dependencies.scala

This makes it a little bit easier to understand how to fix the problems when running validateDependencies.
Recommend backporting to make things easier for us when backporting other changes.

Log project names with dependency problems

---

docs/build.sbt
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java

I noticed the test 3rd and 4th phases were not awaiting the command response and suspect that could be a cause for flakiness. I really can't tell because I can't reproduce the errror. This code change only addresses one of the two causes of the `CqrsIntegrationTest` flakyness: last assertion times out because it starts the await too early.
This PR also bumps the dependency version of play and akka to match those on master.
Fixes #461 (?)

Adds awaits on the test and bumps versions to match _root_ build.sbt

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/__service1ClassName__Service.java
docs/manual/java/guide/broker/MessageBrokerApi.md
docs/manual/java/guide/broker/code/docs/javadsl/mb/BlogPostService.java
docs/manual/java/guide/broker/code/docs/javadsl/mb/HelloService.java
docs/manual/scala/guide/broker/MessageBrokerApi.md
docs/manual/scala/guide/broker/code/docs/scaladsl/mb/BlogPostService.scala
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/Descriptor.java
service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/none/PublisherService.java
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/TestTopicService.java
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/AlphaUpstreamService.java
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/BetaUpstreamService.java
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/PublishService.java

Fixes #769
Deprecates the `Descriptor#publishing` API in favor of the more consistent `Descriptor#withTopics` API.

deprecate Descriptor#publishing 

---

api-tools/src/test/scala/com/lightbend/lagom/api/tools/tests/scaladsl/ServiceLoaders.scala
api-tools/src/test/scala/com/lightbend/lagom/internal/api/tools/ServiceDetectorSpec.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala

Overriding describeServices was deprecated in Lagom 1.3.2, but the internal implementation still uses it for backward compatibility.
The default implementation returned `Nil`, which resulted in no services discovered when only overriding `describeService` and not `describeServices`.
Fixes #829
Note that this is just a minimal fix to make it work again. There are several other follow-up actions described in #829 that will be submitted as separate pull requests.

Fix support for overriding describeService

---

build.sbt

Previous attempts were not correct but we couldn't detect that because PRs in Travis don't have access to `secure` env vars.
See also https://github.com/lagom/lagom/pull/820#issuecomment-310989790

Travis injects values using env vars, not system props.

---

build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/project/build.properties
docs/build.sbt
docs/project/build.properties
project/build.properties

Fixes #666 
This is going to be the first in a series of cascading PRs for almost every project in the Lagom project.

bump sbt version to 0.13.15 and removes deprecated syntax.

---

docs/build.sbt
project/Dependencies.scala
project/plugins.sbt
service/core/client/src/main/scala/com/lightbend/lagom/internal/client/ClientServiceCallInvoker.scala

This includes few changes in the dependency whitelist.
Most notably, changes in jackson since play-core depends on jackson 2.8.9 and play-json depends on 2.8.8. Because play-json is now an independent project those versions may diverge (as they have in this case).
I get some deserialization errors locally so I don't espect this build to pass but I wanted to push this ASAP.

Bumps play to 2.6 GA

---

service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala

Because Scala before 2.12 does not have a way to warn at compile time, this implements a runtime check when the service starts
Fixes #834

Warn when describeServices is overridden

---

docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/JdbcBlogApplicationLoader.scala
docs/manual/scala/guide/production/ConductR.md
docs/manual/scala/guide/production/code/ConductR.scala
docs/manual/scala/guide/services/DependencyInjection.md
docs/manual/scala/guide/services/code/ServiceImplementation.scala

Fixes #835
**DO NOT** backport before 1.3.6 is released, please. Docs changes on the stable branch get deployed daily, but until 1.3.6, `describeService` does not actually work correctly due to #829.
It's safe to merge to `master`, since we are not deploying that to the web site.

Update docs to use describeService

---

docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md

Adds a section wrt underlying stack upgrade and possible side effects.
The migration guides differ slightly because the javadsl users have more to take care of (lagom 12 to lagom 13 to lagom 14, play.Configuration deprecation,...).
Also includes the details wrt `describeService` in the scaladsl version. See #849

Improve Migration Guides with play/Akka upgrade

---

docs/manual/java/gettingstarted/GettingStartedSbt.md
docs/manual/scala/gettingstarted/IntroGetStarted.md

Added note in the sbt new command to fix problem on Windows machines that says: invalid system property 'sbt.version'
https://github.com/sbt/sbt/issues/2695

Note on sbt new command

---

build.sbt
project/Dependencies.scala

Upgrading play and akka had the side effect of reducing the number of transitive dependencies. The whitelist was too extensive and noisy.
This PR adds a new sbt task that helps cleaning up unnecessary items from the whitelist: `pruneWhitelist`.
This is not a magic task as it runs once per project but it doesn't consolidate results. ATM the usage is a bit more manual:
```
$ sbt pruneWhitelist > tmpfile 
$ cat tmpfile | awk -F\:   '{print $(NF-1) ":" $NF}'| sort | uniq -c | sort -n | grep 52 
```
`52` is a magic number equivalent to the number of projects in the `sbt` build. What the previous command does is list all the unnecessary dependencies per `sbt` project. Then it uses some `bash` sorcery to list all those dependencies which are listed as unnecessary 52 times thus unnecessary …

Cleans whitelist removing unnecessary dependencies

---

docs/manual/java/guide/services/code/docs/services/test/ServiceTestModule.java
service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/JavadslErrorHandlingSpec.scala
service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/LagomServiceRouter.java
service/javadsl/server/src/main/java/com/lightbend/lagom/javadsl/server/ServiceGuiceSupport.java
service/javadsl/server/src/main/resources/play/reference-overrides.conf
service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomServer.scala

If you want to use a custom router that delegates to the Lagom router, or in my case, if you're writing a Play app but you want to embed a Lagom service implementation into it, then in order to take advantage of type based dependency injection, you need to be able to refer to the Lagom service router by type. This introduces a type for the Lagom service router in both the Java and Scala APIs, so that they can be injected by type into another Play router.

Strongly type the Lagom service router

---

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
dev/maven-plugin/src/main/maven/plugin.xml
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServerMojos.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/service-registry/service-locator/src/main/resources/application.conf
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceLocatorServer.scala
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/discovery/ServiceRegistryActor.scala
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala
project/Dependencies.scala

By default, it uses the existing Netty gateway, but you can set:
```
lagomServiceGatewayImpl in ThisBuild := "akka-http"
```
And it will switch to an akka-http one. This should be able to be backported to Lagom 1.3.x.

Implemented akka-http service gateway

---

.editorconfig

This adds an .editorconfig file to control mainly the indentation.
Java files in Lagom are supposed to be indented with 4 spaces while Scala files and configurations with 2 spaces. 
Most IDE do support EditorConfig and will take this in consideration.

EditorConfig file

---

docs/manual/java/guide/build/LagomBuild.md

These characters are not needed to be escaped. Writing <plugins> directly is neither erroneous nor it does makes the formatting incorrect.
Fixes #xxxx

Changed the \< and \> to < and > respectively.

---

persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraReadSideHandler.scala
persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraReadSideHandler.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcReadSideImpl.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcReadSideImpl.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/slick/SlickReadSideImpl.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickReadSideSpec.scala
persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImpl.java
persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImplSpec.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala

Saves offset for unhandled events

---

play-json/src/main/resources/reference.conf
play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/JsonSerializer.scala
play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializer.scala
play-json/src/test/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializerSpec.scala

Fixes #502
Brings feature parity to scaladsl. The approach is the same: a user configuring a serializer may choose (with class granularity) if compression should be applied. Compression will only be applied when a `compress-larger-than`threshold is reached (defaults to 1Kb).

Adds JsonSerializer.compressed to conditionally compress when payload is too big

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/test
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala

Fixes #929 
As @jroper has introduced the new `lagomInfrastructureServices` and all `*Enable` flag will be checked in it, there needs no `startInfrastructure` task any more. It will start all tasks of kafka, cassandra, service locator no matter what `*Enable` flag has been set.
Issue #929 point out the problem.

Remove old infrastructure tasks.

---

jackson/src/main/scala/com/lightbend/lagom/internal/jackson/JacksonJsonSerializer.scala
jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java
jackson/src/test/java/com/lightbend/lagom/serialization/TestEventMigration.java

This PR does for the java version (using jackson) what PR #588 does for the scala api (using play json)
With the current implementation, we need to add a line to our application.conf for each version of an event, eg:
"com.lightbend.lagom.serialization.Event1" = "com.lightbend.lagom.serialization.TestEventMigration"
"com.lightbend.lagom.serialization.Event1#2" = "com.lightbend.lagom.serialization.TestEventMigration"
"com.lightbend.lagom.serialization.Event1#3" = "com.lightbend.lagom.serialization.TestEventMigration"
Otherwise, events of versions > 1 are not migrated.
This was fixed for the scala api in PR 588, and I applied similar changes to the JacksonJsonSerializer for the java api.
The test illustrates the issue: an instance of event1 of version 2 was not migrated, resulting in a …

Look up a migration using only the class name instead of the manifest

---

docs/manual/common/guide/devmode/DevEnvironment.md
docs/manual/common/guide/devmode/code/build-service-locator.sbt
docs/manual/common/guide/devmode/index.toc
docs/manual/java/guide/devmode/ServiceLocator.md
docs/manual/scala/guide/devmode/ServiceLocator.md

Fixes #953 for `master`.
When backporting, the following need a review:
- wording on the section `Default gateway implementation` 
- sample code and docs on `build-service-locator.sbt`

Documents Service Gateway DevEnv settings (including impl choice).

---

cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala

Fixes #971 
This includes two changes:
- use `Runtime.halt` when shutdown is already in progress but takes too long
- ensure `System.exit` is invoked only once to avoid deadlock.
PS: Invoking `System.exit()` from a `Thread` that's registered as a JVM Shutdown Hook causes a deadlock.

Improves cluster termination to avoid deadlock

---

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala

Adds property to configuration in `LagomReloadableDevServerStart`
This was verified with: `hello-scala.g8`, `hello-java.g8` and `maven-archetype`. It removes the warning in all cases. 
Only affects 1.4.x because the warning and property was only added in Akka 2.5.x. Branch 1.3.x use Akka 2.4.19. 
(fixes #906)

Sets akka.cluster.jmx.multi-mbeans-in-same-jvm = on in Dev mode 

---

project/Dependencies.scala

This version contains a security fix.
`master` is already using 3.4.10, so this pull request targets 1.3.x.
Fixes #980.

[1.3.x] Update ZooKeeper to 3.4.10

---

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md
persistence-jdbc/core/src/main/resources/play/reference-overrides.conf
persistence-jdbc/core/src/main/resources/reference.conf
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/javadsl/src/multi-jvm/resources/reference.conf
persistence-jdbc/javadsl/src/test/resources/reference.conf
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/scaladsl/src/multi-jvm/resources/reference.conf
persistence-jdbc/scaladsl/src/test/resources/reference.conf
persistence-jpa/javadsl/src/test/resources/reference.conf
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
project/Dependencies.scala

This PR upgrades Lagom to the upcoming akka-persistence-jdbc v3.0.0 (not yet released)
A few issues will be fixed once we can merge this PR:
- upgrades Slick to 3.2.1 (#918)
- promotes the usage of `slick.profile` instead of deprecated `slick.driver` (#764)

upgrades akka-persistence-jdbc to 3.0.0

---

bin/scriptLib

These add a lot of noise to the build logs in Travis, and don't provide much value.

Silence "Resolving" messages in the build

---

build.sbt
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/GreetingMessage.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/__service1ClassName__Event.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-api/src/main/java/__packageInPathFormat__/__service1Name__/api/__service1ClassName__Service.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Command.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Entity.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Event.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__Module.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceImpl.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__State.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/resources/application.conf
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__EntityTest.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceTest.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-api/src/main/java/__packageInPathFormat__/__service2Name__/api/__service2ClassName__Service.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Module.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Repository.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__ServiceImpl.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/java/__packageInPathFormat__/__service2Name__/impl/__service2ClassName__Subscriber.java
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/resources/application.conf
dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/it/__service2ClassName__IT.java

These files are templates used to create code owned by Lagom users, so they should not be populated with a Lightbend copyright notice.
Fixes #976.

Remove copyright from files in Maven archetype

---

persistence/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/TestEntity.java
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriver.scala
testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriverSpec.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriver.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriverSpec.scala

Handle null in PersistentEntityTestDriver
Previously, this would throw a NullPointerException if an entity had a
null state.
Fixes #951
Note that the indentation of `TestEntity.java` was previously using the two-space Scala indentation style instead of the four-space Java style. I reformatted the existing file in a separate commit. You might find it easier to review commit 4c9f886 by itself.

Handle null state in persistent entity test driver

---

cluster/core/src/main/resources/reference.conf
cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala

Iterates over changes introduced on #974.
This PR introduces a simpler implementation that aims to achieve the same goals than #974:
- shutdown cleanly on SIGTERM
- shutdown cleanly with non-zero exit status on cluster node downing
- avoid deadlocking
- system.halt when a 10s delay passes without actor system termination
This is WIP. I'd like to review the shutdown process/setup in upper layers (lagom/play). For example:
- get rid (or make configurable) of [this Infinite](https://github.com/playframework/playframework/blob/2.5.15/framework/src/play/src/main/scala/play/api/Play.scala#L128)
- review the [default timeout](https://github.com/playframework/playframework/blob/2.6.3/framework/src/play/src/main/resources/reference.conf#L853-L854) in Lagom for the …

Simplifies the actor system termination and JVM shutdown

---

build.sbt
project/Dependencies.scala

This uses the new version of play-file-watch with a custom WatchService for macOS instead of using JNotify.
We've decided not to update it on the Play stable version until it's been tested a bit. Though I do not expect any problems, I think it makes sense to test in the milestones for Lagom where it is less risky but will still see some actual users.

Update play-file-watch to 1.1.0

---

persistence/core/src/main/resources/reference.conf
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala

My primary motivation for implementing this is that I have a use case with a very custom sharding distribution setup (the cluster is divided into multiple failure groups, with fast failover between them when timeouts occur), and so I'm instantiating persistent entity actors as direct children of my own sharded actors, rather than letting Lagom manage them. Because of this, I want/need my own actors to handle passivation, and so need to disable passivation of the persistent entity actors.

Allow no passivation to be configured

---

persistence-jdbc/javadsl/src/multi-jvm/resources/reference.conf
persistence-jdbc/scaladsl/src/multi-jvm/resources/reference.conf
persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterDistribution.scala
persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterStartupTask.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideImpl.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala

Fixes part of  #1006. 
This PR addresses the problem where a `ReadSideActor` that was just restarted by the BackoffSupervisor would not start consuming from the eventStream because it doesn't know the tag it was assigned. The tag assignment comes from `ClusterDistribution` every 30 seconds.
This PR wraps the stream inside `ReadSideActor` in a `RestartSource`.

ReadSide should honour BackoffSupervision.

---

project/Dependencies.scala

Fixes #1008 
This is WIP as it currently crashes the dependency validation on slf4j and javassist.
I also got a flaky test on my machine on an [integration test](https://github.com/lagom/lagom/blob/c43d8a780475b010d20e0411babe38b389a71162/service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/JavadslErrorHandlingSpec.scala#L187-L191).

Bumps play version to 2.5.17

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/.gitignore

Solves #1013
This `.gitignore` is copied from lagom-scala.g8 but includes also `*.iml` which seems to be created on IntelliJ.

Adds .gitignore on maven archetype

---

docs/manual/java/guide/services/ServiceDescriptors.md
docs/manual/scala/guide/services/ServiceDescriptors.md

Improved the documentation to remove ambiquity in call description

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/integration-tests/src/test/java/__packageInPathFormat__/it/__service2ClassName__IT.java
dev/maven-plugin/src/main/maven/plugin.xml
dev/maven-plugin/src/maven-test/external-project/integration-test/src/test/java/sample/integration/ExternalProjectIT.java
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/test
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/test
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/test
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/project/Build.scala
docs/manual/common/guide/devmode/DevEnvironment.md
docs/manual/java/gettingstarted/GettingStartedMaven.md
docs/manual/java/gettingstarted/GettingStartedSbt.md
docs/manual/java/guide/advanced/code/docs/advanced/IntegratingNonLagom.java
docs/manual/java/guide/devmode/ServiceLocator.md
docs/manual/scala/gettingstarted/IntroGetStarted.md
docs/manual/scala/guide/advanced/IntegratingNonLagom.md
docs/manual/scala/guide/devmode/ServiceLocator.md
service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java

Issue #460
Changing the default value of port of the service locator from `8000` to `9008`, 
..because `8000` conflicts w/ the default value for JDWP debug mechanism.

Changing the default port for service locator 8000 -> 9008

---

docs/manual/scala/guide/services/ServiceDescriptors.md

This a small change to PR #1019. 
It aligns the scala documentation to the java documentation.  I couldn't push to original @PallaviSingh1992 branch, so merged his PR and I'm sending this small patch now.

align scala documentation with java one

---

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala

Change to execute to avoid syntax error on callable statements.  Stricter drivers enforce { ? = call .... } format which break the previous code.
Fixes #1023

Change to execute to avoid syntax error

---

build.sbt
docs/build.sbt
project/Dependencies.scala

I also removed the previous update to the play-file-watch version because we decided to update that with the sbt 1.0 update in Play, so it should automatically be updated in Lagom when we add sbt 1.0 support.

Update Play to 2.6.6

---

persistence/core/src/main/resources/reference.conf
persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterStartupTaskSerializer.scala
persistence/core/src/test/scala/com/lightbend/lagom/internal/persistence/cluster/ClusterStartupTaskSerializerSpec.scala

Fixes #933.
This is a backport of #1043, with the modification that the serializer is not enabled (so that rolling upgrades can be done safely on the 1.3.x branch without any config changes from the user).

Added serializer for ClusterStartupTaskActor.Execute

---

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/MessageProtocol.java
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/MessageProtocol.scala

fixes #1018
`MessageProtocol.isText` now returns true also in the case if the
contentType is `"text/plain"`
Btw. better way would be deciding based on the "Opcode" of each message https://tools.ietf.org/html/rfc6455#page-29

FF issue with websocket binary frames

---

docs/manual/java/guide/cluster/ReadSideCassandra.md
docs/manual/java/guide/cluster/ReadSideJDBC.md
docs/manual/java/guide/cluster/ReadSideJPA.md
docs/manual/scala/guide/cluster/ReadSideCassandra.md
docs/manual/scala/guide/cluster/ReadSideJDBC.md
docs/manual/scala/guide/cluster/ReadSideSlick.md

Fixes #996 
Added to the persistent read-sides documentation for CassandraReadSide, JdbcReadSide, etc the missing section about registering read-side processors
It seemed pretty straight forward
no

Document ReadSide.register in the Cassandra/RDBMS read-side documentation

---

project/Dependencies.scala

This upgrade fixes the following issue in the cassandra persistence library: https://github.com/akka/akka-persistence-cassandra/issues/237
There is only one problem with the upgrade of the library: https://github.com/akka/akka-persistence-cassandra/issues/230
So an upgrade from the previous version to this one in a production system can go wrong and unless auto-create tables is off.
Upgrades the persistence cassandra to the latest bugfix release
https://github.com/akka/akka-persistence-cassandra/issues/237

Upgraded akka persistence cassandra version to 0.57

---

service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStreamedServiceRouterSpec.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStrictServiceRouterSpec.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/mocks/MockFilters.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/mocks/MockServices.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/testkit/FakeRequest.scala

This is a backport of #1030.
When a new request arrives, the ServiceRouter in Lagom builds a Play Action on the fly. That Action closes over the request.headers as received over the wire before the request is filtered.
The side-effect of that is that when using Play filters in a Lagom service, if the play filter modifies the headers then the modifications are not available on the Lagom code. Other modifications on the request are available on the Lagom code because the Action build on the fly by the ServiceRouter distinguishes between request and headers.
This PR ignores the headers received in favour of parsing the headers only when they are needed.

Service Router actions should use filtered request (1.3.x)

---

docs/build.sbt
docs/manual/java/guide/broker/MessageBrokerApi.md
docs/manual/java/guide/broker/code/docs/javadsl/mb/AnotherServiceImpl.java
docs/manual/scala/guide/broker/MessageBrokerApi.md
docs/manual/scala/guide/broker/code/docs/scaladsl/mb/AnotherServiceImpl.scala
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaSubscriberActor.scala
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/broker/Message.java
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/broker/MetadataKey.java
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/broker/Subscriber.java
service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaMetadataKeys.java
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaTopic.scala
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/KafkaMetadataKeys.java
service/javadsl/kafka/client/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriberSpec.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/broker/MessageMetadata.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/broker/Subscriber.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/broker/Topic.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaTopic.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/scaladsl/broker/kafka/KafkaMetadataKeys.scala
service/scaladsl/kafka/client/src/test/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriberSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/InternalSubscriberStub.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/testkit/TopicStub.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/internal/testkit/TestTopicFactory.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ProducerStubFactory.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ProducerStubFactory.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/TestTopicComponents.scala

Supersedes #930.
This provides an abstraction for accessing message metadata. Metadata keys are strongly typed (like topic properties). The message key is considered a generic key rather than being Kafka specific, so is defined in the Lagom api project. It has been designed such that we can support message keys other than String in future (though String is still only supported by Lagom, that's a separate thing to this).
Other Kafka specific properties that have been added are offset, partition, topic, and headers - the headers use the immutable Headers type from the Kafka consumer API.
While this change only supports accessing metadata from the consumer side, a similar approach could be added in future to produce custom metadata on the producer side.
Documentation to come.

Allow subscribers to access message metadata

---

persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriver.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriverSpec.scala

* [ ✔️] Have you read through the [contributor guidelines](https://github.com/lagom/lagom/tree/master/CONTRIBUTING.md)?
* [ ✔️] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ✔️] Have you [squashed your commits](https://github.com/lagom/lagom/tree/master/WorkingWithGit.md)?
* [ N/A ] Have you added copyright headers to new files?
* [ N/A ] Have you updated the documentation?
* [ ✔️ ] Have you added tests for any changed functionality?
Fixes #xxxx
N/A
Currently, when you test a PersistentEntity with the PersistentEntityTestDriver and the PersistentEntity does not handle an event, The PersistentEntityTestDriver captures an UnhandledEvent(Tuple2[Event, State]) which gives the following message:
> No event handler registered for class scala.Tuple2
What does …

Fix unhandled event issue message in PersistentEntityTestDriver

---

docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
project/Dependencies.scala

This PR is not yet ready because akka-persistence-jdbc version 3.0.1 is not yet published. 
It also includes a notice on the migration guide related to the new column index.
Fixes #1038

Akka Persistence JDBC update

---

build.sbt
docs/manual/scala/releases/Migration14.md

Fixes #1082
Setup MiMA for the scaladsl lagom projects
Some projects failed binary compatibility checks. Hence, I excluded some classes. Some appear to have moved packages, others appear to have incompatible method types. How should those be addressed?

Setup MiMa for scaladsl projects

---

.travis.yml
bin/scriptLib
bin/test-2.11
bin/test-2.12

Fixes #1002.
Using the same strategy we are using in Play. This configures Travis build to run tests for Scala 2.11 and 2.12 in different jobs.
https://github.com/playframework/playframework/pull/7873

Split test execution for Scala 2.11 and 2.12

---

service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceCallResolver.scala
service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala
service/javadsl/api/src/main/scala/com/lightbend/lagom/javadsl/api/IllegalPathParameterException.java
service/javadsl/api/src/test/java/com/lightbend/lagom/api/mock/InvalidPathParameterService.java
service/javadsl/api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala

1. Added a wrapping exception for IllegalArgumentException with a detailed error message
2. changed "ID" to "path parameter" in IllegalArgumentException error message
Fixes #1084 
Provides more information for certain run time exceptions in a lagom based java service

Improves error messages in path param serializer resolution

---

persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/JndiConfigurator.scala
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/SlickProvider.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModule.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala

This PR removes the need to inject a DbApi in SlickProvider. 
Fixes #1120

Introduces a JndiConfigurator that is run before SlickProvider creation

---

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala

Fixes #941 
It prints out a warning about potential errors due to slow Lagom startup
LagomReloadableDevServer is shared both by Maven Runner and Sbt runner. It is invoked by the Reloader, in build-tool-support, which itself is invoked by the Maven and SBT plugin.

Added a check to warn about slow startup problems

---

dev/service-registry/service-locator/src/main/resources/application.conf
docs/build.sbt
project/Dependencies.scala

This upgrade is required by https://github.com/lagom/lagom/pull/1054, https://github.com/lagom/lagom/pull/1109, #1133, #1131 and https://github.com/lagom/lagom/pull/1068.
This PR fixes #1108 
This PR impacts https://github.com/lagom/lagom/pull/1125 which may need a review to remove obsolete overrides.

Bumps Akka 2.5.8, AkkaHttp 10.0.11 and Play 2.6.9

---

project/Dependencies.scala

This removes the transitive dependency on the LGPL-licensed jnotify library.

Update play-file-watch to 1.1.7

---

docs/manual/common/guide/devmode/RunningServices.md

This is a minor documentation fix. 
While helping a user in Gitter I realised that the `sbt` instructions were not clear. At first, I even didn't see it was there. This PR add the instruction in a code block so, it becomes visually obvious.

minor documentation fix to align mvn and sbt instructions

---

docs/manual/common/guide/production/code/conductr.sbt
docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md

Fixes #1138
- Update documentation for ConductR to the most recent, 1.4-compatible versions.
- Add a section to the migration guides about updating ConductR.

Update ConductR guides

---

.editorconfig

This is what most of the XML files in the repo currently use, but the `.editorconfig` configuration was using the default of two spaces.

Set four-space indent for XML files

---

build.sbt
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/test/java/__packageInPathFormat__/__service1Name__/impl/__service1ClassName__ServiceTest.java
dev/maven-plugin/src/maven-test/start-all-2.11/helloworld-impl/src/test/java/sample/helloworld/impl/HelloServiceTest.java
dev/maven-plugin/src/maven-test/start-all-2.12/helloworld-impl/src/test/java/sample/helloworld/impl/HelloServiceTest.java
docs/manual/java/guide/services/Test.md
docs/manual/java/guide/services/code/docs/services/test/EnablePersistence.java
docs/manual/java/guide/services/code/docs/services/test/EnablePersistenceCassandra.java
docs/manual/java/guide/services/code/docs/services/test/EnablePersistenceCluster.java
docs/manual/java/guide/services/code/docs/services/test/EnablePersistenceJdbc.java
docs/manual/scala/guide/services/TestingServices.md
docs/manual/scala/guide/services/code/TestingServices.scala
service/javadsl/integration-tests/src/test/java/com/lightbend/lagom/it/mocks/PersistenceServiceTest.java
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala

This PR adds the possibility to configure `ServiceTest` to be used for JDBC test. 
Fixes: #304

Added support for JDBC testing in ServiceTest

---

docs/build.sbt
project/Dependencies.scala

Originally I just meant to update to the new releases of Play and Akka, but I reviewed a few others while I was in there.
Please backport to 1.4.x.

Update dependencies for 1.4.0

---

build.sbt
project/Dependencies.scala

We were overriding these incorrectly, with an unintended effect of adding a log4j2 dependency that is not needed and not used.
Fixes #1162.

Fix Kafka server dependencies

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala

This allows users to override JVM options for forked tests by setting:
```
javaOptions in Test := Seq(/* ... */)
```
Please backport to 1.4.x.

Use javaOptions when creating test groups

---

docs/manual/scala/releases/Migration14.md

- Play JSON changes
- LagomServiceClientComponents requires LagomConfigComponent

Add missing items to the 1.4 migration guide

---

docs/manual/java/guide/build/LagomBuild.md
docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md

- plugin version was still pointing to 1.4.0-R1
- Lagom 1.4.0 seems not to work with Sbt 0.13.15 (or prior). Users must update to 0.13.16

Some migration guide fixes

---

docs/manual/common/guide/production/code/conductr.sbt
docs/manual/java/releases/Migration14.md
docs/manual/scala/releases/Migration14.md

These are the latest versions depending on the final release of Lagom 1.4.0.
The previous versions are believed to work with 1.4.0 final, but this brings the dependencies in line.

Update ConductR lib/sbt versions

---

project/Dependencies.scala

These were only used to match the whitelist, but these modules no longer have transitive dependencies on netty-transport-native-epoll. As a result, this had the undesired effect of adding a dependency on netty-transport-native-epoll where it otherwise wouldn't have one.
Please backport to 1.4.x after merging.

Remove netty-transport-native-epoll dependencies

---

build.sbt
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-server-disabled-but-defaults-config-still-injected/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
docs/build.sbt
docs/manual/java/guide/build/code/lagom-build.sbt
docs/manual/java/guide/build/code/multiple-builds.sbt
docs/manual/scala/guide/build/code/lagom-build.sbt
docs/manual/scala/guide/build/code/multiple-builds.sbt
project/Dependencies.scala

This is minor Scala version upgrade. `master` and `1.4.x` are using 2.11.12 already, but `1.3.x` was lagging behind.
Fixes #1149

Upgrades to scala 2.11.12

---

.travis.yml
bin/scriptLib
bin/test-code-style
build.sbt
project/Whitesource.scala
project/plugins.sbt
project/whitesource.sbt

- Detect the current branch based on an environment variable (Travis CI) or using git.
- Determine the Whitesource project name from the branch and version number, so we won't have to update the configuration whenever a stable branch is created.
- Build all branches in CI (required to test this change).
- Run Whitesource update with full info-level logging (which includes useful output).
- Only update Whitesource when the WHITESOURCE_PASSWORD encrypted environment variable is set (i.e., not for pull requests).
- Update to the latest sbt-whitesource plugin, which includes support for reading WHITESOURCE_PASSWORD from the environment directly.
- Stop using project tokens, which are not required when the project name is provided.
- Update "*-stable" projects in Whitesource for final release …

Improve Whitesource automation

---

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractPersistentEntityActorSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala

Originally committed to 1.3.x in 979a2368a04a311636464258f76712c5de14f714 using the `expectNoMessage` name that is available in Akka 2.5.
This broke the build until the test changes were reverted in 8ae144a969f46597bd593a0aacac3f2a7d448e3e.
This restores the tests, but changed to use the Akka 2.4 method name: `expectNoMsg`
Thanks, @lutzh for the tip. References #1210.

[1.3.x] Restore tests from #1210

---

build.sbt
project/Whitesource.scala
project/plugins.sbt

This was added in #1218 (a1714f9) but conflicts with git worktree.
https://github.com/sbt/sbt/issues/2323
The use of sbt-git was only a convenience for running Whitesource update locally without specifying the CURRENT_BRANCH environment variable. Since worktree is a more important convenience, I'm reverting this part of the change.
Should be backported to 1.4.x and 1.3.x.

Remove sbt-git plugin

---

project/Dependencies.scala

This updates the bundled Cassandra server to 3.11.2, fixing an incompatibility with recent JDK 8 versions:
https://issues.apache.org/jira/browse/CASSANDRA-14173
Fixes #1204
If you want to see the before/after, you can test this by creating a new Lagom project (e.g., with `sbt new lagom/lagom-scala.g8`) and running `sbt runAll` with `java version "1.8.0_162"` (I use [jEnv](http://www.jenv.be/) to switch between multiple installed JDKs).
Using Lagom 1.4.0, you'll see errors reported when it launches Cassandra:
```
[info] Starting Cassandra
.Exception (java.lang.AbstractMethodError) encountered during startup: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFi …
```

Update Akka Persistence Cassandra to 0.60

---

docs/manual/common/guide/build/JVMMemoryOnDev.md

In the Maven section, the value for MaxMetaspaceSize is set as `-XX:MaxMetaspaceSize=1024M`, but the description says "...a thread stack of 2M and maximum Metaspace size of 2014M".
Fixes #xxxx

Wrong description for MaxMetaspaceSize

---

docs/manual/java/guide/services/ServiceClients.md
docs/manual/scala/guide/services/ScalaComponents.md
docs/manual/scala/guide/services/ServiceClients.md

fixes #1241 (remove docs to metrics service endpoints and promote multi-service servers)
I'd remove `MetricsService` in a separate PR.

Removes docs wrt the metrics service and its endpoints

---

testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala

Issue #1185 was fixed in #1257, so this can be simplified to match the Java version.
This removes the workaround added in #1186.
Backport to 1.4.x isn't really required, but might as well.

Remove unnecessary workarounds in ServiceTestSpec

---

build.sbt

This is my attempt to fix the failure on Travis CI when building release tags (for example https://travis-ci.org/lagom/lagom/jobs/349686520)
The problem was caused by the `build-tool-support` and `maven-plugin` modules being published multiple times to the Maven repository in the same build. When building `SNAPSHOT` versions, this is fine, but when building a tag sbt prevents overwriting existing files.
I tested this locally by:
1.  Checking out the `1.4.1` tag and overlaying these changes
2.  Deleting existing artifacts with:
```bash
rm -r ~/.m2/repository/com/lightbend/lagom
```
3.  Running
```bash
sbt clean +publishM2 mavenTest
```

Build Maven plugin and support for Scala 2.12 only

---

bin/test-documentation
docs/build.sbt

Tests are forked, so it needs to be specified in the Java options for the forked test process, not for the sbt process.
Follow up to #1264, hopefully fixes #461.

Move akka.test.single-expect-default setting

---

build.sbt
project/Dependencies.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/CassandraTestServer.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestConfig.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/ServiceTestSpec.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTestSpec.scala

The previous implementation depends on classpath ordering and can result in Cassandra being used when JDBC is intended.
Fixes #1236

Fix Cassandra and JDBC conflicts in TestKit

---

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/broker/Subscriber.java
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/broker/Subscriber.scala

Fixes #1274
Adds documentation to describe that the `flow` that is passed to `Subscriber.atLeastOnce` must handle every event exactly once.
I was not aware of these requirements when using `Subscriber.atLeastOnce` and it leads to a bug where the offset would get further and further behind.
https://github.com/lagom/lagom.github.io/issues/129

Document required behaviour of flow to message broker subscriber

---

persistence-jdbc/core/src/main/resources/reference.conf
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbProvider.scala
persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
persistence/core/src/main/resources/reference.conf
persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/ReadSideConfig.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala

Make sure that read-side processors don't keep waiting forever when fetching offset.

enabled timeout when fetch read-side offset

---

docs/manual/java/guide/build/LagomBuild.md
persistence-jdbc/core/src/main/resources/reference.conf
project/Dependencies.scala

Not yet ready for merge. Awaiting `akka-persistence-jdbc` release.
To backport on 1.4.x only.
Fixes #1250

Upgrades Slick and akka-persistence-jdbc versions

---

testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ReadSideTestDriver.java
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ReadSideTestDriver.scala

Some early work to have fully featured `ReadSideTestDriver`'s in both java and scala. Related to #421.
Untested and undocumented. (this feature is experimental)
As it is, the `ReadSideTestDriver` requires starting the `TestServer` but it may be possible implement a lightweight alternative that only started what's really necessary. In `scala` for example it may be possible to _just_ instantiate a `XxxxReadSidePersistentComponents` (Jdbc or Cassandra) with the ReadSideTestDriver override. Food for thought but definitely not in scope for this PR.

Brings ReadSideTestDriver as developed on online-auction

---

build.sbt

While reviewing https://github.com/lagom/lagom/pull/1292 I noticed an API change that should have broken the build. We forgot to include `1.4.0` on the mima checks in `master`.

Adds  1.4.0 on the mima chain of versions under inspection

---

service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

These specs were saving an offset to the offset store, but this occurred after the test application had already started the topic producer, so this stored offset was never accessed.
Thanks to @idoshamun for raising this in https://discuss.lightbend.com/t/kafka-scaladsl-possible-test-fix/717

Remove redundant code from Kafka specs

---

persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/PersistentEntityActor.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideImpl.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistrySpec.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractPersistentEntityActorSpec.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistenceComponents.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistrySpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/PersistentEntityTestDriverCompatSpec.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriverCompatSpec.scala

** Soliciting feedback; not final. **
Enables the creation of additional named PersistentEntityRegistry and ReadSide instances, that are part of the same actor system, but may still use different plugins for journals, snapshot stores, and persistence queries.
This is necessary for multi-tenant applications where the tenant-specific data should be segregated into distinct databases.
This PR does not address the Akka limitation whereby persistence plugins must be configured ahead of time in the actor system Config, so it is limited to static multi-tenancy.
PersistentEntityRegistry and ReadSide instances must have distinct names, but this isn't currently checked. No additional tests have yet been added. No documentation changes have yet been made.

Additional PersistentEntityRegistry, ReadSide

---

build.sbt
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntity.scala

Fixes #1299
`BehaviorBuilder` only exists for Lagom's Java DSL but was implemented in `scala` as a protected class which made it unreachable for `javadoc` (with Lagom's javadoc settings).
This PR splits `BehaviorBuilder` into a pubic sealed trait `BehaviorBuilder` and  a `private[lagom] final class BehaviorBuilderImpl extends BehaviorBuilder` so javadocs are created and published.
I checked MiMa and there's no alert raised.

Adds javadoc for BehaviorBuilder

---

service/javadsl/kafka/server/src/test/resources/application.conf
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/server/src/test/resources/application.conf
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

While developing the Google Pub/Sub Message Broker, I noticed some bugs and typos in the Kafka implementation tests:
* Fix config keys (`client` was missing).
* Add group id to some of the tests as they were missed.

minor fixes to kafka message broker tests

---

docs/build.sbt
project/Dependencies.scala
service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/MessageSerializers.scala

Fixes #1340
Bumping Akka version to `2.5.12`
Bumping the version is required to be able to leverage new javadsl method signatures from TestKit that now allows to pass `java.time.Duration` parameters instead of `scala.concurrent.duration.Duration`
See https://doc.akka.io/docs/akka/2.5.12/testing.html#tab1

Bumping Akka version to 2.5.12

---

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ClassLoaders.scala
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Reloader.scala

The delegating classloader is a little odd - it makes the application classloader resources available to libraries which are in the parent classloader. However, this means when it loads resources, the resources it loads appear twice on the classpath because it both loads its own, and the parent, which includes its own. This ensures that it doesn't include its own resources in getResources, that it only gets the parent resources.
This bug was introduced when we pulled the code out of Play - Play already had this problem solved (in fact this specifci bug was fixed 6 years ago). Not sure how we reintroduced it, but what I've ensured is that our behaviour is now the same as Play - resources are deduped in the parent loader (I'm not sure that this is actually needed) and the application loader …

Stop application resources from being returned twice from getResources

---

docs/build.sbt
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
docs/src/test/resources/application.conf

This PR takes the task where https://github.com/lagom/lagom/pull/1264 left it:
- use `akka.test.single-expect-default = 14s`globally to tune defaults in Akka's testkit
I also tuned all timeouts to use unambiguous values. Not really necessary but nice testing trick.
Even if this build in travis ends up green, I suggest we keep pressing the relaunch button on `test-documentation` until we're comfortable it is stable.

Final attempt at making CqrsIntegrationTest stable

---

testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala

This made it impossible to use Play's DB API in a non-clustered Lagom
service test.
Fixes #1351

Stop disabling DBModule in tests

---

bin/test-2.12
bin/test-sbt-1.0
build.sbt
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
docs/build.sbt
docs/manual/java/guide/build/code/lagom-build.sbt
docs/manual/java/guide/build/code/multiple-builds.sbt
docs/manual/java/releases/Migration14.md
docs/manual/scala/guide/build/code/lagom-build.sbt
docs/manual/scala/guide/build/code/multiple-builds.sbt
docs/manual/scala/releases/Migration14.md
project/Dependencies.scala
project/Doc.scala

- Requires updating genjavadoc to 0.11.
- This, in turn, requires disabling it in any projects that cross build with Scala 2.10.

Update Scala 2.12 to 2.12.6

---

project/plugins.sbt

This updates the upstream Whitesource agent version transitively, which changes a problematic dependency of its own that was not available from Maven Central.
https://github.com/lightbend/sbt-whitesource/pull/37
https://github.com/whitesource/agents/commit/322de017f39abb86093c0564f6d2b0e65ad55984
This should be backported to 1.4.x and also 1.3.x if it applies cleanly.

Update sbt-whitesource to 0.1.11

---

build.sbt
project/plugins.sbt

https://github.com/lightbend/migration-manager/releases/tag/0.3.0
Update deprecated `excludePackage` call to `exclude[Problem]`.

Update Migration Manager (MiMa) to 0.3.0

---

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala

Use explict timeouts to better control Flakiness of test

---

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala

Related #260 #1366
This PR tries to fix the flakyness of the tests following the hypethesis described in https://github.com/lagom/lagom/issues/260#issuecomment-392463727

Increase default timeouts for expectations and persisten entity asks

---

bin/test-code-style
dev/sbt-scripted-library/src/main/java/api/FooService.java
dev/sbt-scripted-library/src/main/java/impl/FooModule.java
dev/sbt-scripted-library/src/main/java/impl/FooServiceImpl.java
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala

Previously, this relied on an implicit header update running as part of the build, combined with the diff check at the end. This leaves some files out.
I expect the first commit (which adds the check) to fail. Once it does, I'll push another commit with the fixes.

Check copyright headers explicitly

---

docs/build.sbt
project/Dependencies.scala

Also bumps `docs/` version of Akka to same than main (`2.5.13`).
The relevant change is `jackson-databind` being release separately causing a small refactor.

Updates play to 2.6.15

---

docs/manual/java/guide/broker/MessageBrokerApi.md
docs/manual/java/guide/broker/code/docs/javadsl/mb/AnotherServiceImpl.java
docs/manual/java/guide/broker/code/docs/javadsl/mb/FilteredServiceImpl.java
docs/manual/scala/guide/broker/MessageBrokerApi.md
docs/manual/scala/guide/broker/code/docs/scaladsl/mb/AnotherServiceImpl.scala
docs/manual/scala/guide/broker/code/docs/scaladsl/mb/FilteredServiceImpl.scala

Fixes #1294 
- Adds section Message Broker API / Implementing a topic / Filtering events which describes by example how to filter events before they are published.
- Adds section Message Broker API / Subscribe to a topic / Skipping messages which shows two examples of how to skip messages. More importantly it describes what you need to watch out for when skipping messages.
There was some discussion on lagom/lagom.github.io/issues/129 about where the best place was to add this.
I was also discussing this in the [Akka forums](https://discuss.lightbend.com/t/splitting-messages-into-separate-streams-and-maintaining-order/517) to make sure we covered all the caveats and used the correct language. I'm not sure we have really nailed it yet. My goal was to try and keep it simple and yet still …

Document how to skip messages when consuming and publishing events

---

.travis.yml

We have seen a number of flaky builds when trying to install sbt via apt.

Use the standard Travis CI sbt launcher

---

CONTRIBUTING.md

- help:newbie is now "good first issue"
- help:community is now "help wanted"
These new labels match the GitHub conventions.

Update GitHub issue labels in CONTRIBUTING.md

---

build.sbt
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntity.scala

As an inner trait, referencing type variables from the outer scope can cause interoperation problems with Java code.
This is similar to the issue described in: https://github.com/lagom/lagom/issues/396
Fixed in: https://github.com/lagom/lagom/pull/405
The change to make `BehaviorBuilder` a trait in the first place was introduced in https://github.com/lagom/lagom/pull/1302.

Change BehaviorBuilder to an abstract class

---

build.sbt

Lagom already has a whitelist which dependencies are added, so the evictions warnings are just adding noise to the build.
1. https://github.com/playframework/playframework/issues/7832
2. https://github.com/sbt/sbt/issues/1636

Silence sbt eviction warnings

---

build.sbt
service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala
service/scaladsl/integration-tests/src/test/scala/com/lightbend/lagom/scaladsl/it/ScaladslErrorHandlingSpec.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomServer.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStreamedServiceRouterSpec.scala
service/scaladsl/server/src/test/scala/com/lightbend/lagom/scaladsl/server/ScaladslStrictServiceRouterSpec.scala

This removes access to the global state through BodyParsers. Now a PlayBodyParsers is injected or accessed through compile-time dependencies.

Remove body parsers deprecations

---

build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/a/impl/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/b/impl/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/c/src-c/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/bar/impl/src/main/java/impl/Module.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/foo/impl/src/main/java/impl/Module.java
dev/sbt-scripted-library/src/main/java/impl/FooModule.java
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/ConfigurationServiceLocator.java
service/javadsl/client/src/main/java/com/lightbend/lagom/javadsl/client/ConfigurationServiceLocator.java
service/javadsl/integration-tests/src/test/scala/com/lightbend/lagom/it/ServiceSupport.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala

Remove all places where `play.Configuration` is used.
This includes calls to `play.Application.configuration`. Additionally, removed calls to `play.Application.getFile` since it was deprecated too.

Remove APIs that depends on deprecated play.Configuration

---

docs/manual/java/gettingstarted/JavaPrereqs.md
docs/manual/java/guide/build/EclipseMavenInt.md
docs/manual/java/guide/build/EclipseMavenNew.md
docs/manual/java/guide/build/IntellijMaven.md
docs/manual/java/guide/build/IntellijSbtJava.md
docs/manual/scala/gettingstarted/Installation.md
docs/manual/scala/guide/build/IntellijSbt.md

Lagom only supports Java 8, not 9 or 10 currently.

Remove "or higher" from JDK requirements

---

.github/PULL_REQUEST_TEMPLATE.md
WorkingWithGit.md
bin/test-code-style

Ever since GitHub started offering a button to automatically squash and merge, we have stopped requiring pull request authors to squash their commits themselves. In fact, we encourage them to update pull requests with new commits to make it easier to review changes.

Stop requiring squashed commits

---

persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala

This PR is a spin-off from https://github.com/lagom/lagom/pull/1409 and it should be cherry-pickable on 1.4.x.
I'm marking it as WIP, because I still need to add test to prove that the `ReadSideActor` is re-running the `globalPrepare` after restarting.

Read side actor restart

---

docs/build.sbt
docs/manual/java/guide/advanced/code/docs/home/actor/WorkerService2Impl.java
docs/manual/java/guide/advanced/code/docs/home/actor/WorkerServiceImpl.java
docs/manual/java/guide/services/code/docs/services/MessageSerializers.java
docs/manual/java/guide/services/code/docs/services/ServiceImplementation.java
docs/manual/java/guide/services/code/docs/services/test/ServiceTestModule.java
docs/manual/java/guide/services/code/docs/services/test/StubDependencies.java
docs/manual/scala/guide/advanced/code/Akka.scala
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/CassandraBlogEventProcessor.scala
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/PostSpec.scala
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
docs/src/test/scala/docs/home/actor/ActorServiceSpec.scala

It does not fix all the deprecated warnings in documentation samples, but most of them. So there is still some work to do related to #401.
Update documentation sample code to avoid deprecated APIs.

Remove warnings from docs

---

docs/manual/scala/guide/services/code/ServiceClients.scala

In https://github.com/lagom/lagom/pull/1419#issuecomment-401623005, @erip pointed out that this snippet is no longer referenced.
The snippet inclusion was removed in #1246.

Remove unused metrics-service snippet

---

build.sbt
dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala

This appears to fix the deadlock, but it's not clear whether there might be other undesirable consequences. We'll have to do some manual testing (including with the Netty server).
Review with whitespace changes hidden.
#1405 (Update Play to 2.7.0-M1)

Restore sbt 1.1.6

---

project/Dependencies.scala

https://akka.io/blog/news/2018/07/13/akka-2.5.14-released
(Rather than cherry-picking this, I'll open a separate pull request for 1.4.x so that the full set of tests can run before merging to that branch.)

Update Akka to 2.5.14

---

docs/build.sbt
project/Dependencies.scala

https://akka.io/blog/news/2018/07/13/akka-2.5.14-released
(Backport of #1445. Rather than cherry-picking this, I opened a separate pull request for 1.4.x so that the full set of tests can run before merging to this branch.)

[1.4.x] Update Akka to 2.5.14

---

docs/build.sbt

fail if any deprecated APIs are used in docs.

---

build.sbt
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala
dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClient.scala
dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscovery.scala
dev/service-registry/client-core/src/main/scala/com/lightbend/lagom/internal/registry/ServiceRegistryClient.scala
dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/AbstractLoggingServiceRegistryClientSpec.scala
dev/service-registry/client-core/src/test/scala/com/lightbend/lagom/internal/registry/DevModeSimpleServiceDiscoverySpec.scala
dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/JavaServiceRegistryClient.scala
dev/service-registry/client-javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistry.java
dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryModule.scala
dev/service-registry/client-javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/registry/ServiceRegistryServiceLocator.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ScalaServiceRegistryClient.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistry.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistryServiceLocator.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
project/Dependencies.scala
service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java

Fixes #1426
The [Akka Management](https://developer.lightbend.com/docs/akka-management/current/) library recently introduced a new component for [Service Discovery](https://developer.lightbend.com/docs/akka-management/current/discovery.html). This is used as the basis of [Akka Cluster Bootstrap](https://developer.lightbend.com/docs/akka-management/current/bootstrap.html), to help service nodes locate each other when forming a cluster, but is intended to be used in many other contexts in the future, including typical service-to-service communication scenarios (such as in [Akka gRPC](https://github.com/akka/akka-grpc), see https://github.com/akka/akka-grpc/issues/137).
We hope to make Akka Service Discovery into the fundamental service discovery API for all of the Lightbend Reactive …

Provide Akka Discovery support in dev mode

---

bin/test-code-style
dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/DynamicProjectAdder.scala
dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/LagomImportCompat.scala
dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/LagomPluginCompat.scala
dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/run/RunSupportCompat.scala

I noticed after a local `sbt +publishLocal` that some files didn't get the extra blank line in the `sbt-header` update (#1459).
This is because these are files that are only built when cross-building the sbt 1.0 version of the plugin, but our style check in Travis CI only builds the first Scala version for each module.
I expect the build to fail on the first commit. Once I confirm that it fails as expected, I'll push another commit with the fix.

Cross build style/header checks

---

bin/test-code-style

Related to https://github.com/lagom/lagom/pull/1482.
The comments explain why it's three `sbt` invocations instead fo one.

Adds some comments on Travis scripts

---

bin/test-code-style
build.sbt

We can use mimaReportBinaryIssues since lightbend/migration-manager#163 is now solved.
Related to #1482.

Use mimaReportBinaryIssues task instead of custom command

---

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala

Related to #1378
I stumbled upon this code and noticed this `bind` was ignoring `config.host`.
cc @erip

Bind Netty service gateway to the configured host (not 0.0.0.0)

---

project/Protobuf.scala
project/plugins.sbt

In part, done in preparation of #1455. 
~~Specifically, lagom.Protobuf is redundant an will be using removed API's when moving to sbt 1.x. To mitigate both of these, this PR replaces all functionality with an official SBT plugin.~~
sbt-site has made private some APIs required by `lagom.Protobuf`. This PR eliminates the dependency on sbt-site, which was used exclusively for those APIs and adds the functions.

Remove sbt-site plugin in preparation of sbt 1.x

---

build.sbt
dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/registry/ServiceRegistration.scala
dev/service-registry/devmode-scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/devmode/LagomDevModeComponents.scala
dev/service-registry/registration-javadsl/src/main/scala/com/lightbend/lagom/internal/server/ServiceRegistrationModule.scala
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/NettyServiceGateway.scala
dev/service-registry/service-locator/src/test/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGatewaySpec.scala
service/scaladsl/server/src/main/scala/com/lightbend/lagom/scaladsl/server/LagomApplicationLoader.scala

I had worked on this few weeks ago but needed CS merged and 2.7.0-Mx. 
Its' mostly dogfooding so devmode components use Coordinated Shutdown instead of `ApplicationLifecycle`.
Related to #1379

Extends the usage of CS in Lagom-core (mostly dev mode)

---

build.sbt

In https://github.com/lagom/lagom/pull/1463 we bumped `sbt-sonatype` from `0.5.0` to `2.3`. This introduced a bug
because since [2.0.0-M1](https://github.com/xerial/sbt-sonatype/blob/master/ReleaseNotes.md) the `sbt-sonatype` plugin
no longer overrides `publishTo` and it requires users to set an explicit value.

Adds sbt-sonatype settings after upgrading to version 2.0+

---

service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/TransportException.java

Added another constructor with message in TransportMessage.java to suffice RuntimeException constructor
This PR adds another constructor to ```TransportException.java``` which takes ```message```, ```Throwable``` exception and ```TransportErrorCode```.
After discussing it with @TimMoore on contributor channel on Lagom Gitter. Here is the conversation:
> Piyush Goyal @piyushGoyal2 Jun 20 09:03
Lagom version 1.4.x /Java Version. There is no support for custom error message to be passed to RunTimeException(message, Throwable) constructor. TransportException has only one constructor which takes TransportErrorCode and Throwable and it passes cause.getMessage() as the message to RuntimeException constructor. The message field in the constructor of RuntimeException was created to pass a custom …

Add a TransportException constructor with message and cause

---

build.sbt
docs/manual/java/releases/Migration15.md
docs/manual/scala/releases/Migration15.md
project/plugins.sbt

In #1494 we ensured all projects had `publishTo` information but we didn't ensure the value was correct.
The fix here explicitly disables `Bintray` plugin, enables `Sonatype` and sets the correct `publishTo` value for a few projects.

Explicitly disables Bintray and sets up Sonatype on dev mode projects

---

build.sbt
project/LagomPublish.scala

Related to #1496 (#1497, #1494, #1493).
Some settings like `publishTo` are only exercised during a release. On top of that, these settings often rely on default values set on `AutoPlugin`s. The third cause of confusion is having multiple plugins that may set these default values (`Sonatype` vs `Bintray`).
This PR introduces a task that asserts the correct value for each of the Lagom projects is set and the value is coherent with the rules presented in https://github.com/lagom/lagom/issues/1496#issuecomment-408398508.
On a separate PR we can add a Travis task to invoke this validation on every Travis execution.
The task runs on the current sbt state. This state differs when the current build is a `SNAPSHOT` version or a release version. A future improvement would be to make the validation …

Adds sbt task to validate `publishTo` settings

---

.travis.yml

This will help to reduce the number of errors due to Travis failing to download sbt dependencies.
We are having a bunch of errors on our builds that are not related to pull-request changes. Most of them are happening because Travis is failing to download sbt launcher:
```
Downloading sbt launcher for 0.13.17:
From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/sbt-launch.jar
To  /home/travis/.sbt/launchers/0.13.17/sbt-launch.jar
Download failed. Obtain the jar manually and place it at /home/travis/.sbt/launchers/0.13.17/sbt-launch.jar
```
It is possible the problem is on Bintray side. By caching `~/.sbt` and `~/.ivy2` we should reduce the change of failure since sbt launcher and its dependencies are cached. …

Cache entire .sbt directory on Travis builds

---

dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/DynamicProjectAdder.scala

This PR reverts a change we introduced in PR #1500 to make it compatible with sbt 1.2.0. 
This change makes Lagom compatible with sbt < 1.2.0 and >= 1.2.1, but not compatible with 1.2.0.

reverts Load.reapply change introduced in #1500

---

dev/maven-plugin/src/main/maven/plugin.xml
dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven/ServiceMojos.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/run/RunSupport.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/custom-port-range-for-services/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
docs/manual/java/guide/build/MultipleBuilds.md
docs/manual/java/guide/devmode/ConfiguringServicesInDevelopment.md
docs/manual/java/guide/devmode/code/configuring-devmode-services.sbt
docs/manual/scala/guide/devmode/code/configuring-devmode-services.sbt

This PR adds serviceHttpsPort to mvn plugin and deprecates servicePort in mvn and sbt.
Fixes #1539 
Fixes #1508

Configurable serviceHttpsPort for maven plugin

---

docs/build.sbt
project/Dependencies.scala

Cherrypicking https://github.com/lagom/lagom/pull/1564 into `1.4.x` I got a silly conflict with `project/Dependencies.scala` for the version of `akka-http`.
I prefer creating a separate PR than pushing to `1.4.x` directly.
Related to #1562

[1.4.x] bump akka to 2.5.16

---

dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala

When ssl is enabled this will configure the default truststore for play WS and akka grpc clients.

Setup truststore via ssl-config for all clients to pick up

---

build.sbt
dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLEngineProvider.scala
dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestkitSslSetup.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala

This is related to #1595 but not a fix.
This is a minimal change to make ssl available in lagom's `TestService` that unblocks testing gRPC. The UX for gRPC users is not great but at least this works. Needs massaging and improving.
At the moment I keps the scope scala-only as we discuss and improve the approach.

Adds SSL support for lagom's testkit

---

build.sbt
dev/dev-mode-ssl-support/src/main/scala/com/lightbend/lagom/devmode/ssl/LagomDevModeSSLHolder.scala
dev/reloadable-server/src/main/scala/play/core/server/LagomReloadableDevServerStart.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/TestkitSslSetup.scala
testkit/javadsl/src/main/scala/com/lightbend/lagom/javadsl/testkit/ServiceTest.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/ServiceTest.scala

Also clean up code so SSLHolder encapsulates thhe reuse of an underlying FakeKeyStore. With this code cleanup 
it is getting easier to read the keyStore and the trustStore from separate locations. There's still work to be done though.
Related to https://github.com/lightbend/ssl-config/pull/129 and https://github.com/lightbend/ssl-config/pull/92

Support trustStore password

---

project/Dependencies.scala

0.3.5 defaulted to PKCS12 format for the auto-generated key stores. The ssl-config library doesn't support setting the trustStore password which is required in PKCS12 format to read the trusted certificates. As a consequence generated stores could not be used as truststores.
Related to https://github.com/playframework/playframework/pull/8691

Bumps ssl-config to 0.3.6

---

dev/maven-plugin/src/main/maven/plugin.xml
docs/manual/common/guide/devmode/CassandraServer.md
docs/manual/common/guide/devmode/code/build-cassandra-opts.sbt

Fixes #1622
The default behaviour of deleting cassandra data on startup on dev mode should be aligned to false

Fix documentation and maven config to be aligned to false as default behaviour

---

.travis.yml

Uses Play's approach: group travis jobs into stages with fast stages first. This grouping is by kind of script (same approach than in Play)
I'd like to reconsider into a different approach: run first the jobs for preferred versions (e.g. `test-2.12` + `test-sbt-1.0` + `test-code-style`).

Reorder travis jobs in stages

---

build.sbt

Fixes #1693 (supersedes #1684)
Tunes `scripted` test JVMs: Increases the maximum size for `Metaspace` and reduces the maximum heap size. This is a workaround solution to avoid the head-of-line block on the build pipeline (see #1693 for more details)
The actual issue is a classloader leak in Lagom Dev Mode. Solving that is out of scope at this moment. This solution kicks the can down the road...

Increase max metaspace size. Decrease max heap size (-Xmx)

---

docs/manual/java/releases/Migration15.md

1. Made the change for better understanding and readability.
2. Made the change for the right name of httpsPort in maven - `serviceHttpsPort`.
* 
Fixes #xxxx
Adds the readability to Migration15.md and corrects the httpsPort label for maven projects.

updated readability.

---

docs/manual/scala/releases/Migration15.md

(same as #1696, but for Scala documentation)

Fixes typos in Migration15.md

---

docs/build.sbt
project/Dependencies.scala

Lightbend Orchestration (`reactive-lib`) 1.7.0 evicts `akka-actor` 2.5.19, causing a version conflict between different Akka modules.
https://discuss.lightbend.com/t/cluster-fail-with-error-akka-version-must-be-the-same-across-all-modules-of-akka-that-you-are-using/3396

[1.4.x] Update Akka to 2.5.20

---

.travis.yml

With the migration to travis-ci.com complete we now hhave 8 workers (instead of 5). I think it's more convenient to have fewer, bigger stages. 
This PR merges `validation` and `test` and I'm eager to merge `test-build-tools` too. Opinions?

Merges travis stages

---

testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/TestOverTlsTest.java
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/TestTlsService.java
testkit/javadsl/src/test/java/com/lightbend/lagom/javadsl/testkit/services/tls/TestTlsService.java
testkit/javadsl/src/test/scala/com/lightbend/lagom/javadsl/testkit/TestOverTlsSpec.scala
testkit/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/testkit/TestOverTlsSpec.scala

Fixes #1608
This adds unit tests for the SSL support introduced in testkit.
The implementation for both the scaldsl and the javadsl is currently in scala but I?ll eventually migrate the 
javadsl to java to deuse the code on the docs.

Adds unit tests for SSL testkit API

---

docs/manual/java/releases/Migration15.md
docs/manual/scala/releases/Migration15.md

The  migration 1.5 guide already mentions the version bumps of play, akka and akka-http. This adds a generic mention to otherversion bumps and links to release notes in GH.

Adds mention to release notes wrt other version bumps

---

docs/manual/java/releases/Migration15.md
docs/manual/scala/releases/Migration15.md

Depending on the version of Lagom 1.4.x users migrate from they may have to take care of migration steps introduced between patch version of Lagom 1.4.x.
This PR instructs users to upgrade to `1.4.11` before bumping to `1.5.0`

Adds instructions to bump from lagom 1.4.latest only

---

docs/manual/java/releases/Migration15.md
docs/manual/scala/releases/Migration15.md

Moving away from LBO: produce reference guide content and link from the Migration15.md

Migration from LBO to manual deployment

---

.github/settings.yml

To indicate on PRs that should backport also to the 1.4.x branch.

Add a "status:needs-backport-1.4" label

---

project/Dependencies.scala

Force eviction of `com.google.guava:guava:19.0` in favor of the whitelisted version.

Force eviction of Guava 19.0

---

docs/manual/java/gettingstarted/JavaPrereqs.md
docs/manual/java/releases/Migration15.md
project/Dependencies.scala

I'm not sure what the impact of this bump can be. /cc @jroper
The purpose of this change is to bump some transitive dependencies which are messing up with some 3rd party security analisys (whitesource)

Bumps maven-core to bump transitive deps

---

persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/jpa/JpaPersistenceModule.java
service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
service/javadsl/kafka/client/src/main/java/com/lightbend/lagom/javadsl/broker/kafka/KafkaClientModule.java

There are still some usages of deprecated APIs from Play (mainly `ApplicationLifecycle.stop`), but we can remove them later.

Remove usage of deprecated APIs from Play

---

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala

A salvaged piece of #1796 that should be landable as a standalone change.

Avoid a JDK 11 deprecation

---

cluster/core/src/main/resources/reference.conf
dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/LagomConfig.scala
docs/src/test/scala/com/lightbend/lagom/docs/ServiceSupport.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModuleSpec.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

We need to discuss if we want it on 1.5.0 release or not. Since is a change in behavior, either it gets shipped with 1.5.0 or we postpone it to 1.6.0.
If we choose to have it in 1.5.0, we need to add a notice on the migration guide. Otherwise, we need a documentation section explaining that this needs to be correctly configured in production environments. 
(for now, I'm adding to 1.5.0 milestone)

Shutdown actor system and jvm on unsuccessful cluster join

---

.travis.yml
bin/test-sbt-1.0
docs/manual/java/releases/Highlights15.md
docs/manual/scala/releases/Highlights15.md
project/Dependencies.scala
service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala

Add some dependencies to let all the projects compile on Java 11.  I
believe these are necessary due to deprecations and changes around
Java's 9+ platform module system (JPMS).  Specifically:
* persistence-cassandra-javadsl needs javax.annotation.PostConstruct
which is in the jsr250 jar
* server-javadsl needs the javax annotation api jar
We validate the fixes by running unit tests and scripted tests on Java
11.  Some of the other parts of CI validation (e.g. documentation tests)
aren't possible due to the fact Lagom still uses sbt 0.13 and also there
are still some issues with using sbt 1 on Java 11.
Fixes #1417

Initial fixes for Java 11

---

cluster/core/src/main/resources/reference.conf
docs/manual/java/releases/Migration15.md
docs/manual/scala/releases/Migration15.md

This is also for 1.5.0. Includes a notice on migration guide about the new default settings we introduced in #1811

Document new defaults in clustering formation settings

---

.travis.yml
bin/test-sbt-0.13
bin/test-sbt-1.0
build.sbt

If all is setup properly with scriptedDependencies it shouldn't be
necessary to publish locally as an independent step of running scripted.

Drop unnecessary publishLocal before scripted

---

docs/manual/common/guide/production/LightbendPlatform.md

Found via a [cron](https://travis-ci.com/lagom/lagom/jobs/188106568#L2159) build.
I labeled this as needs-forwardport but I'm not entirely sure. Note this is a PR to `1.5.x`.

Prefer using the actual Location

---

docs/manual/common/guide/production/LightbendPlatform.md

See https://github.com/lagom/lagom/pull/1834#discussion_r269813097
Also fixed for `1.4.x` in #1836 and `master` in #1837, so no back or forward porting is required.

Fix sbt setup link in the Lightbend Platform documentation

---

cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala
docs/build.sbt
project/Dependencies.scala

Bumps Akka to `2.5.22`. It also adopts the new Shutdown reasons and improves the comments wrt how and why shutdown works in case of a cluster event (downing, join nonsuccessful, etc...)
Fixes #1849

Bumps akka to 2.5.22

---

.travis.yml

Firstly this avoids building random branches in the repo (such as
Mergify's backport/forwardport branches).
Disable building the master, 1.5.x and 1.4.x branches.  This avoids that
every merge into those branches kicks off a build.  This isn't necessary
because we use Mergify's ["strict merge workflow"][] which means the PR
is up-to-date with the target branch before it gets merged.  As an
additional safe-guard I've changed the branch protection in GitHub to
require PRs to be up-to-date before merging, also.
["strict merge workflow"]: https://doc.mergify.io/strict-workflow.html

Build only the tags

---

docs/manual/java/guide/services/Test.md
docs/manual/scala/guide/services/TestingServices.md

When testing with mixing persistence configuration this can be a little puzzling. This at least clarify one particular setup.

added some ServiceTest setup clarification when mixing persistence

---

.travis.yml

With the migration to Travis CI.com and the promotion of Java 11 I think it makes more sense to have fewer, beefier stages _and_ also have Java 11 treated as a 1st class citizen.
Moving away from the 5-worker limit in travis-ci.org's released a constraint motivating the creation of stages with a small number of jobs. This PR still splits the job list in two stages but considering the total number of jobs (9) is still smaller than the number of travis workers (13) I think that could be removed and have all jobs just run free.

Fewer stages + Java11 is 1st class

---

build.sbt

Now that 1.5.0, we can have master checking against 1.5.0 and remove all the exceptions. 
If we detect anything that requires an exclusion we can evaluate and do it or not. 
The same must be done on `1.5.x` but there no exclusions are allowed.

set MiMa to check against 1.5.0 only

---

dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/Servers.scala
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala

All other plugins in `LagomPlugin.scala` specify explicitly the `noTrigger` (which is good)

make explicit noTrigger in plugins, minor deprecation fix and typo

---

akka-service-locator/.gitignore
akka-service-locator/core/src/main/scala/com/lightbend/lagom/internal/client/AkkaDiscoveryHelper.scala
akka-service-locator/core/src/main/scala/com/lightbend/lagom/internal/client/ServiceNameMapper.scala
akka-service-locator/core/src/test/scala/com/lightbend/lagom/internal/client/ServiceNameMapperSpec.scala
akka-service-locator/javadsl/src/main/java/com/lightbend/lagom/javadsl/akka/discovery/AkkaDiscoveryServiceLocator.java
akka-service-locator/javadsl/src/main/java/com/lightbend/lagom/javadsl/akka/discovery/AkkaDiscoveryServiceLocatorModule.java
akka-service-locator/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/akka/discovery/AkkaDiscoveryComponents.scala
akka-service-locator/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/akka/discovery/AkkaDiscoveryServiceLocator.scala
build.sbt
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
docs/build.sbt
docs/manual/java/guide/production/AkkaDiscoveryIntegration.md
docs/manual/java/guide/production/ProductionOverview.md
docs/manual/java/guide/production/code/akka-discovery-dependency.sbt
docs/manual/java/guide/production/index.toc
docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
docs/manual/scala/guide/production/ProductionOverview.md
docs/manual/scala/guide/production/code/AkkaDiscoveryIntegration.scala
docs/manual/scala/guide/production/code/akka-discovery-dependency.sbt
docs/manual/scala/guide/production/index.toc
docs/manual/scala/guide/services/ScalaComponents.md
project/Dependencies.scala

This PR brings in the whole history of http://github.com/lagom/lagom-akka-discovery-service-locator which explain the long list of commits.
@lagom/core, when reviewing you should concentrate on the 5 last commits. All the rest is code migrated from http://github.com/lagom/lagom-akka-discovery-service-locator.
The 5 last commits here are very similar to those in #1883, except for the `Production Overview` and `Akka Discovery Integration` pages that are slightly different for 1.4.x
To visualise the changes on a browser you will need to publish locally a new version of lightbend-markdown containing this PR https://github.com/lightbend/lightbend-markdown/pull/12 and update `docs/project/plugins.sbt`

[1.4.x] Integrates akka discovery service locator in Lagom

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala

This is the fix for future releases. The docs on `master` are correct wrt to this, not need to change.

Fix LagomImport links to Akka Discovery ServiceLocator

---

docs/manual/java/guide/production/AkkaDiscoveryIntegration.md
docs/manual/java/guide/production/code/akka-discovery-dependency.sbt
docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
docs/manual/scala/guide/production/code/akka-discovery-dependency.sbt

Minor improvement that guarantees that dependency is kept aligned with Lagom plugin version

[1.5.x] Use LagomVersion.current

---

docs/manual/java/guide/production/AkkaDiscoveryIntegration.md
docs/manual/java/guide/production/code/akka-discovery-dependency.sbt
docs/manual/scala/guide/production/AkkaDiscoveryIntegration.md
docs/manual/scala/guide/production/code/akka-discovery-dependency.sbt

Minor improvement that guarantees that dependency is kept aligned with Lagom plugin version

[1.4.x] Use LagomVersion.current   

---

docs/.jvmopts

https://github.com/lagom/lagom/pull/1886 setup `.jvmopts` on the root build but the OOME we're observing on the nightly machine are on the `docs/` build (I think), so still happen every now and then.
Haven't tested this, yet.

Setup JVM for docs build

---

akka-service-locator/scaladsl/src/test/resources/application.conf
akka-service-locator/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/akka/discovery/AkkaDiscoveryServiceLocatorSpec.scala
build.sbt
project/Dependencies.scala

Originally intended to be added in https://github.com/lagom/lagom-akka-discovery-service-locator/pull/80
This doesn't need to be backported as any further change is expected to happen in `master` and regressions expected to be caught by this test.
There is no Java counterpart because the `ServiceTest` wires its own `ServiceLocator`, making it hard to test it. If we really want it tested in Java we will need to refractor the `ServiceTest` for Java.

Adds AkkaDiscoveryServiceLocatorSpec

---

project/Dependencies.scala

Upgrade to the latest patch release of Alpakka Kafka.
[Release notes](https://doc.akka.io/docs/alpakka-kafka/1.0.3/release-notes/1.0.x.html#1-0-3)

Alpakka Kafka 1.0.3

---

cluster/core/src/main/resources/reference.conf

This can be ported to 1.5.x and get shipped on 1.5.2. It has no impact on rolling updates becaues those serializers are already available since Akka 2.5.8 and Lagom 1.4.x and 1.5.x have them already included.
Resolves #1270

Add protobuf akka serializers

---

docs/build.sbt

```
/home/play/deploy/lagom/docs/build.sbt:69: warning: value format in object JavaFormatterKeys is      deprecated (since 0.4.4): Use javafmt
sourceDirectories in format in Test ++= (unmanagedSourceDirectories in Test).value,
^
/home/play/deploy/lagom/docs/build.sbt:70: warning: value format in object JavaFormatterKeys is      deprecated (since 0.4.4): Use javafmt
sourceDirectories in format in Test ++= (unmanagedResourceDirectories in Test).value,
^
```

Fix compile warning

---

README.md

I found that there is an extra comma in the statement which I found in Grammarly extension of google chrome
)?
Fixes #xxxx
This will correct the punctuation mistake.
Many people are getting much knowledge from this repo it should be perfect
No

Removed extra comma from the README.md

---

docs/manual/common/gettingstarted/LagomExamples.md
docs/manual/common/guide/production/LightbendPlatform.md
docs/manual/java/guide/cluster/PersistentEntity.md
docs/manual/scala/guide/cluster/PersistentEntity.md

Fixes #1921
There's a few left over.  First the ones in the 1.5 migration guide, which are fine to point to the
archived recipes, but there are also a few others.

Change most live references to lagom-recipes to lagom-samples

---

dev/maven-plugin/src/maven-test/java-archetype-2.12/pom.xml

As the java-archetype project is POM I thought it might not be necessary, but https://travis-ci.com/lagom/lagom/jobs/201351645 proved me wrong.

Add Akka snapshots repo to java-archetype maven test too

---

bin/scriptLib
dev/reloadable-server/src/main/resources/play/reference-overrides.conf
docs/build.sbt
docs/manual/java/releases/Migration15.md
docs/manual/java/releases/Migration16.md
docs/manual/java/releases/index.toc
docs/manual/scala/releases/Migration16.md
docs/manual/scala/releases/index.toc
docs/src/test/scala/docs/home/actor/ActorServiceSpec.scala
persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala
project/Dependencies.scala
pubsub/javadsl/src/test/java/com/lightbend/lagom/javadsl/pubsub/PubSubTest.java
pubsub/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/pubsub/PubSubSpec.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

Also, use Akka 2.6 snapshots in our nightly builds, and since Akka 2.6 does not support Scala 2.11, dropping it for Lagom as well.
Let's not merge without having some migration guide already.

Use Akka 2.6.0-M1

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml

Using lagom/lagom-java.g8 on Java 11 I got multiple runtime errors caused by an old version of lombok. Bumping to latest version `1.18.8` gets the job done.
See https://github.com/lagom/lagom-java.g8/pull/54

Use a Java 11 friendly lombok version

---

build.sbt
persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcReadSideSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickReadSideSpec.scala
persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaReadSideImplSpec.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/PersistentEntityRegistry.scala
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRegistry.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala

* [ Not Applicable] Have you added copyright headers to new files?
* [ Not Applicable] Have you updated the documentation?
* [ Not Applicable] Have you added tests for any changed functionality?
Fixes #1768
This PR contains code change where we have removed the one deprecated method from existing code.
To clean the code where we have removed the one deprecated method from existing code.

Removed gracefulShutdown depricated method from code

---

project/plugins.sbt

This hopefully fixes a problem with sbt-sonatype where multiple staging repositories are created when releasing Lagom.

Update sbt-sonatype to version 2.5

---

.travis.yml
bin/test-maven
build.sbt

POM file for maven-plugin was lacking `/project/scm` and `/project/developers` tag. This fixes the problem and adds a validation on Travis.

Fix maven-plugin pom file generation

---

build.sbt
project/plugins.sbt
version.sbt

Just a quick trial to see how Lagom will behave with dynver. 
That will probably not work when releasing in vegemite. We may want to test this branch in vegemite eventually.
Another issue is that we are not prefixing the tags with a `v`, so to have it really working we will have to retroactively add prefixed tags. Unless there is a way to tweak dynver to now require a `v`.

Start using dynver

---

docs/manual/java/guide/cluster/Serialization.md
docs/manual/java/releases/Migration16.md
docs/manual/scala/guide/cluster/Serialization.md
docs/manual/scala/releases/Migration16.md
jackson/src/main/resources/reference.conf
jackson/src/test/java/com/lightbend/lagom/serialization/JacksonJsonSerializerTest.java
play-json/src/main/resources/reference.conf
play-json/src/test/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializerSpec.scala

After testing the impact of GZipping JSON messages (see https://github.com/akka/akka/pull/27067) the default to run compression should be increased.

Increase compression threshold

---

dev/archetypes/maven-java/src/main/resources/archetype-resources/__service1Name__-impl/src/main/resources/application.conf
dev/archetypes/maven-java/src/main/resources/archetype-resources/__service2Name__-impl/src/main/resources/application.conf
docs/manual/java/releases/Migration16.md
docs/manual/scala/releases/Migration16.md
persistence/core/src/main/resources/play/reference-overrides.conf

Remove and doc unnecessary overrides (now added by default)

---

.scalafmt.conf
dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/DynamicProjectAdder.scala
docs/.scalafmt.conf
persistence/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/AggregateEventTag.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/AggregateEventTag.scala

Apparently, [`version`](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ScalafmtConfig.scala#L14-L15) is used on the IntelliJ-sbt integration but [Travis just failed trying to download 2.0.0-RC5](https://travis-ci.com/lagom/lagom/jobs/211168033#L1839):
```
saving stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[error] failed to resolve Scalafmt version '2.0.0-RC5': /home/travis/build/lagom/lagom/docs/.scalafmt.conf
[error] (Test / scalafmt) failed to …
```

Bump scalafmt version (lib, not sbt plugin)

---

build.sbt
dev/reloadable-server/src/main/resources/play/reference-overrides.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/a/api/src/main/scala/api/FooService.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/a/impl/src/main/resources/application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/a/impl/src/main/scala/impl/FooLoader.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/a/impl/src/main/scala/impl/FooServiceImpl.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/b/api/src/main/scala/api/BarService.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/b/impl/src/main/resources/application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/b/impl/src/main/scala/impl/BarLoader.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/b/impl/src/main/scala/impl/BarServiceImpl.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/changes/a-application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/changes/b-application.conf
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/project/Build.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/project/build.properties
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/project/plugins.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/test
docs/manual/java/releases/Migration16.md
docs/manual/scala/releases/Migration16.md
persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/PersistenceTestConfig.scala

This PR adds back the default settings for remote classic. Needed when opting-out from Artery.
Fixes #1969 
Fixes #1986

Adds defaults settings for remote classic

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala

(This PR requires merging/reviewing https://github.com/lagom/lagom/pull/2012 first)
`ReadSideImpl` includes an extra role verification which prevents `ClusterDistribution` from running when a node doesn't have the correct roles. This causes the behavior:
- the node doesn't host any read-side shard. (which is what it was meant for)
- the node doesn't participate in the `EnsureActive` gossip.
Considering https://github.com/akka/akka/pull/24669 is now the default behavior I find it safer to start `ClusterDistribution` always. The new behavior will be:
- the node doesn't host any read-side shard. (same behavior)
- the node *does* participate in the `EnsureActive` gossip. (improvement)

All nodes participate in gossip

---

service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/Producer.scala
service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/TaggedOffsetProducerActor.scala

Refs #1006
This only shuffles code around. Extracts the Actor into a separate file so both ReadSide and Producer
have a similar structure:
- a class using `ClusterDistribution`
- an actor handling the stream the consumes the tagged stream
This refactor is in preparation for #1744

Extract ProducerActor into separate file

---

persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideImpl.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala

- remove role checking (see #2012)
- remove failfast constructor check
- reuse variable streamName
- adopt xxxFactory naming for props factory method
Fixes #2031

Sync ReadSideImpl.scala implementations

---

.travis.yml

(cherry picked from commit 7b5935d5f2a25ff4db5fe73905c57263247f26c7)
1.5 backport of #2059

[1.5] Enable branch builds

---

.travis.yml

(cherry picked from commit 7b5935d5f2a25ff4db5fe73905c57263247f26c7)
1.4 backport of #2059

[1.4] Enable branch builds

---

build.sbt

sbt-plugin and dev-environment projects were using 2.12.7 instead of 2.12.8.
<sub>
So Metals doctor will be happy with Lagom. :-)
</sub>

Consistent Scala version across all projects

---

persistence/javadsl/src/main/protobuf/PersistenceMessages.proto
persistence/scaladsl/src/main/protobuf/PersistenceMessages.proto
project/Protobuf.scala

There is no need to check the patch version since they are supposed to be compatible. Also explicitly set the syntax expected for proto files.

Only consider minor version when checking protoc version

---

projection/core/src/main/resources/reference.conf
projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionMessageSerializer.scala
projection/core/src/test/scala/com/lightbend/lagom/internal/projection/ProjectionMessagesSerializerSpec.scala

Follow up to #2143.
The test was initially creating an instance of `ProjectionMessagesSerializer` but this does not reveal errors such as wrong configuration or a message not extending marker traits.

Refactor ProjectionMessagesSerializer spec to correctly find the serializer

---

dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/distribution/test

By declaring the root and its aggregates we workaround sbt's
extraProjects bug, which means we can revert the previous workaround of
using lagomProj/stage and playProj/stage.
See https://github.com/sbt/sbt/issues/4947

Workaround extraProjects bug by declaring the root

---

.travis.yml
bin/test-multi-jvm-2.1x
build.sbt

Since multi-jvm tests are where most of the flakiness lives, we can
isolate them from regular tests, which will also make it easier to
re-run jobs when they fail without the need to run everything again.

Isolate multi-jvm tests in their own jobs

---

docs/build.sbt
project/Dependencies.scala

https://github.com/akka/akka/pull/27331 backports to Akka 2.5.x some serialisers introduced into Akka 2.6. That backport allows rolling upgrades between Akka 2.5. and Akka 2.6.
The backport was introduced in Akka 2.5.24 but Akka 2.5.25 is already out and introduces necessary fixes for Lagom (Cluster Singletons).

Bump Akka to 2.5.25

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistenceComponents.scala

Fixes #2192 
A leftover from a previous implementation caused the overwrite to invalidate the `val` so the field in the DI cake was abstract.

Removes (invalid) overwrite

---

projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala
projection/core/src/test/scala/com/lightbend/lagom/internal/cluster/projections/ProjectionStateSpec.scala

Followup to https://github.com/lagom/lagom/pull/2144
I think the `observedStatus` reported for workers we've never heard of should be `Stopped` (since we've never heard from them, probably meaning they never existed).

Initial status default values differ for request and observed status

---

CODE_OF_CONDUCT.md

This will cause this repo to use the default (new) version at https://github.com/lagom/.github/blob/master/CODE_OF_CONDUCT.md

Delete previous CODE_OF_CONDUCT.md

---

.circleci/config.yml
projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala

After reviewing https://github.com/lagom/lagom/issues/2124#issuecomment-521659228 and https://github.com/lagom/lagom/issues/2130#issuecomment-521657624 I think both 
```scala
case UpdateSuccess => 
case UpdateFailure =>
```
are noop. 
In this PR I add comments on the sources and implement small cleanups. 
Fixes #2124

Comment on each UpdateSuccess/UpdateFailure case

---

build.sbt

This prevents the library from pulling in extra dependencies, including cluster.
Fixes #2148 (the follow-up issue described in the comments).

Scope TestKit dependency to Test

---

build.sbt

In `master` we changed the order in which we publish to bintray. We now only publish it after we successfully publish in Maven. 
However, when I cherry picked that change from `master`, I made a mistake. I let the bintray release happen after we change the version. Hence the error I got...
```
[error] java.lang.RuntimeException: failed to release lagom/lagom-sbt-plugin@1.5.4-SNAPSHOT: {"message":"Version '1.5.4-SNAPSHOT' was not found"}
[error]         at scala.sys.package$.error(package.scala:26)
```
This PR fix this.
In the meantime I was able to only publish the 1.5.3 plugin to bintray (manually). 
FYI, in master we don't set the next version because we are using dynver.

release to bintray before changing version

---

docs/manual/java/guide/broker/KafkaClient.md
docs/manual/scala/guide/broker/KafkaClient.md
project/Dependencies.scala

Make it easier to discover the correct configuration of Alpakka Kafka when using Lagom.
I was in contact with a Lagom user who was looking for the security configuration which is described in the Alpakka Kafka docs.

Docs: improve links to Alpakka Kafka

---

persistence/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/AbstractReadSideSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractReadSideSpec.scala
projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala
projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistryActor.scala
projection/core/src/main/scala/com/lightbend/lagom/internal/projection/WorkerCoordinator.scala
projection/core/src/main/scala/com/lightbend/lagom/projection/State.scala
projection/core/src/multi-jvm/resources/logback.xml
projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala
projection/core/src/test/scala/com/lightbend/lagom/internal/cluster/projections/ProjectionStateSpec.scala

Fixes #2213 
This PR supersedes https://github.com/lagom/lagom/pull/2219 following a solution that's a lot simpler and more robust: eagerly tracking the projection names and it's tagNames. It also uses a poor man's stashing for early-requests (main purpose of this fix).

Support requestedStatus before projections register

---

dev/service-registry/service-locator/src/main/scala/com/lightbend/lagom/gateway/AkkaHttpServiceGateway.scala
service/core/api/src/main/scala/com/lightbend/lagom/internal/api/HeaderUtils.scala
service/core/client/src/main/scala/com/lightbend/lagom/internal/client/ClientServiceCallInvoker.scala
service/core/client/src/main/scala/com/lightbend/lagom/internal/client/WebSocketClient.scala
service/core/server/src/main/scala/com/lightbend/lagom/internal/server/ServiceRouter.scala
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/MessageHeader.java
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/RequestHeader.java
service/javadsl/api/src/main/java/com/lightbend/lagom/javadsl/api/transport/ResponseHeader.java
service/javadsl/client/src/main/scala/com/lightbend/lagom/internal/javadsl/client/JavadslServiceApiBridge.scala
service/scaladsl/api/src/main/scala/com/lightbend/lagom/scaladsl/api/transport/MessageHeader.scala

This PR doesn't fix any bugs.
This PR moves all instances of header name normalization into a reusable util method. Basically, all calls like:
```scala
name.toLowerCase(Locale.ENGLISH)
```
are replaced with:
```scala
HeaderUtils.normalize(name)
```
The primary purpose of this PR is to isolate header name normalization into a common method so that it can be easily replaced in [lagom.js](https://github.com/mliarakos/lagom-js). In Scala.js header normalization must happen differently because the `Locale` class isn't available. Using a util method makes it easier to replace this behavior and reduces the amount of Lagom code that needs to be duplicated and modified in the Scala.js implementation.
The secondary purpose is to refactor this common operation into a standard implementation with a …

Header normalization util method

---

akka-service-locator/core/src/main/resources/play/reference-overrides.conf
akka-service-locator/core/src/main/resources/reference.conf

When set in reference.conf, it may or may not override the defaults set in akka-discovery, depending on classpath ordering.
Fixes #2239.

Override default discovery method

---

persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/TolerateFailuresWhenRunningContinuousIntegration.scala

We still have some flaky tests for persistence-cassandra-*, as documented
in #2080. Those are the most common flaky tests so we can ignore them for
now when running on Travis or Circle. They won't be ignored locally, however.
We also won't ignore failures on cron/scheduled builds since they are a
safeguard and don't disrupt the contribution flow.

Tolerate multi-jvm failures when running tests on CI

---

cluster/core/src/main/resources/reference.conf

These are now defined in Akka by default since 2.6.0-M5.
Removes redundant configuration.
- https://github.com/akka/akka/pull/27256
- https://github.com/akka/akka/issues/26684

Remove additional serialization bindings

---

build.sbt

Redoing https://github.com/lagom/lagom/pull/2260 from a branch in `upstream` so we can test it before merging.

Prefer sonatypeBundleRelease

---

service/core/kafka/client/src/main/resources/play/reference-overrides.conf

This would be a new default in Lagom 1.6 that users may explicitly opt-out of.
Note, [Lagom `1.5.x` already uses Kafka `2.1.x`](https://github.com/lagom/lagom/blob/1.5.x/project/Dependencies.scala#L46) but we're not overwriting the default there. 
https://blog.softwaremill.com/does-kafka-really-guarantee-the-order-of-messages-3ca849fd19d2
https://www.youtube.com/watch?v=BxH5ixyfzTA&t=1085
ping @ennru

Default to only 1 max inflight request per connection

---

dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-remote-in-dev/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cassandra-overrides-default-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/external-project-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/http-backend-switch/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/injected-configs/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-javadsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-all-scaladsl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-play-on-conf/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-services/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run-ssl/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/run/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/service-discovery/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/services-intra-communication/build.sbt

This is a minor optimization for the scripts tests. Most of them are starting Cassandra and Kafka while they are not needed. 
This won't have a huge impact on the build time, but there is a small gain. And one or two things less that could fail.

scripted-tests: disable C* and Kafka when possible

---

build.sbt

Defining "sbt.boot.directory" makes the scripted test (re)use the same
user-shared compiler bridge instead of compiling one every time.

Speed-up scripted by reusing user-wide compiler bridges

---

dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-javadsl/src/main/java/com/example/hello/api/HelloService.java
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-javadsl/src/test/resources/logback.xml
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-scaladsl/src/main/scala/com/example/helloworld/api/HelloWorldService.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/hello-scaladsl/src/test/resources/logback.xml
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/project/plugins.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/test

Supersedes #2286 
Removes useless logs with false negatives and includes awaiting ops so the tests doesn't progress until the database is available.

Makes scripted test less verbose more resilient

---

bin/changelog.sh
bin/local-pr-validation.sh
bin/scriptLib
bin/test-2.1x
bin/test-code-style
bin/test-docs-code-only
bin/test-documentation
bin/test-maven
bin/test-multi-jvm-2.1x
bin/test-sbt
project/Dependencies.scala

This typo caused `validateDependencies` and `versionSyncCheck` to not run. We've been on the blind for a while.
This Pr will fail on unrelated issues as those two tasks are rerun for a first time after a while.

Fix typo in bash code

---

docs/manual/java/releases/Migration16.md

Adds migration guide section explaining how to safely setup Jackson serializers during a rolling upgrade.

Adds 2-step migration tuning serializers

---

cluster/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/cluster/typed/ClusterShardingTypedComponents.scala

I noticed that the name of the instance for the typed `ClusterSharding` was set to `clusterShardingTyped`. 
This is not what we want because the Play ClusterSharding components is using `clusterSharding` and one day we want to remove this component from Lagom and  use the one in Play without impacting users. 
Morefore, the adjective 'typed' is not adding much value here. As we adopt Akka Typed more and more, we don't have the need to qualify things. 
And from a user perspective, they need to understand cluster sharding, but the fact that is a typed one is irrelevant for the actual usage. The user only needs to learn they need to register (ie: `init`) on `ClusterSharding` and lookup (ie: `entityRefFor`).

rename injectable instance to 'clusterSharding'

---

project/Dependencies.scala

`CRON` jobs fail because a [Akka's cross-version check is now more strict](https://github.com/akka/akka/issues/27965):
```
[info]   Cause: java.lang.IllegalStateException: 
Detected possible incompatible versions on the classpath. 
Please note that a given Akka version MUST be the same across all modules of 
Akka that you are using, e.g. if you use [2.6-20191010-210113] all other modules 
that are released together MUST be of the same version. Make sure you're using a
compatible set of libraries. Possibly conflicting versions [2.6.0-M7, 
2.6-20191010-210113] in libraries [akka-actor-typed:2.6.0-M7, akka-actor:2.6-20191010-210113, akka-slf4j:2.6-20191010-210113, akka-protobuf-
v3:2.6-20191010-210113, akka-stream:2.6-20191010-210113]
```
This PR is a fix and tests will run but when running …

CRON jobs need to enforce version of Akka Typed

---

cluster/core/src/main/resources/play/reference-overrides.conf
cluster/core/src/main/resources/reference.conf

This should be in reference-overrides.conf since it overrides an Akka setting.

Move shutdown-after-unsuccessful-join-seed-nodes

---

docs/manual/java/guide/cluster/Cluster.md
docs/manual/scala/guide/cluster/Cluster.md

Identical to #2317, except that Akka URLs point to 2.5 documentation rather than 2.6.

[1.5.x] Expand Akka Cluster Bootstrap documentation

---

docs/manual/java/guide/cluster/Cluster.md
docs/manual/scala/guide/cluster/Cluster.md

- Change to numbered steps
- Explicitly mention that dependencies need to be added to the build
- Clarify that the Akka Discovery method used for Akka Cluster Bootstrap
is different than the one used for service-to-service discovery
- Fix typos and formatting issues
- Sync text in Scala version of the guide with the Java version
Thanks to @michael-read for the feedback leading to these changes.

Expand Akka Cluster Bootstrap documentation

---

docs/manual/common/guide/build/JVMMemoryOnDev.md

Fixes #1334.
I haven't really found a documentation page about the `.jvmopts` on the sbt website, but in my opinion it is fine like that as the page already includes an example on how to use the `.jvmopts`
#1334

#1334 remove SBT_OPTS documentation in favor of .jvmopts

---

dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-java/test
dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-scala/test
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala

Make AbstractPersistentEntityRegistry's eventsByTagQuery non-lazy, so
that it doesn't run into a thread starvation issue on environments like
Travis CI.
Then make its queryPluginId a constructor parameter (and non-optional)
so that it doesn't run into initialisation order issues.
Fixes #2357

Fix scripted tests using Akka 2.6

---

persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/AkkaTaggerAdapter.java
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/AkkaTaggerAdapter.scala

As I was rewriting lagom/lagom-scala.g8 and lagom/lagom-java.g8 to use Akka Persistence Typed I kept stumbling upon `EntityContext` on the `Aggregate` code. I think there's some for a second review of the API of `AkkaTaggerAdapter` but I'd like inputs from users on that.
In the meantime, we can mark it as `@ApiMayChange` to stay on the safe side.

Marks AkkaTaggerAdapter as ApiMayChange

---

docs/manual/java/guide/cluster/PersistentEntityCassandra.md
docs/manual/java/guide/cluster/PersistentEntityRDBMS.md
docs/manual/scala/guide/cluster/PersistentEntityCassandra.md
docs/manual/scala/guide/cluster/PersistentEntityRDBMS.md

Refs #2387 
I've reviewd all four flavors of the page but tried to keep the change as small as possible so I haven't renamed the files from `PersistentEntityXyz.md` to something agnostic.
> Note: the scala docs are more evolved than the java docs at this point reason why `index.toc` files for scala and java are out of sync right now. I expect them to sync back as we bring the java ref docs up to speed.

Makes PersistentEntityXyz.md implementation agnostic

---

docs/manual/common/guide/cluster/ChoosingADatabase.md
docs/manual/java/guide/cluster/PersistentEntity.md
docs/manual/java/guide/cluster/index.toc
docs/manual/scala/guide/cluster/PersistentEntity.md
docs/manual/scala/guide/cluster/index.toc
docs/project/plugins.sbt

Refs #2387 
I've extracted the section on choosing a database to `common/` and rewrote the link to `lagom-samples` so it was not implementation specific. All the rest is the same.
Note the scala docs are more evolved than the java docs at this point reason why `index.toc` files for scala and java are out of sync right now. I expect them to sync back as we bring the java ref docs up to speed.

Extracts ChoosingADatabase to 'common/'

---

build.sbt
dev/archetypes/maven-java/src/main/resources/archetype-resources/pom.xml
docs/manual/java/gettingstarted/GettingStartedMaven.md

`maven-enforcer-plugin` unnecessary now.
This check on the plugin level:
https://github.com/lagom/lagom/blob/2c7eb5fb23d47a1667ca9837eedd2be77bf29d3d/build.sbt#L1412-L1416

Remove unnecessary `maven-enforcer-plugin` from maven archetype

---

persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraPersistentEntityRegistry.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/jdbc/JdbcPersistentEntityRegistry.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala

This reverts the material change in #2370, now that it's fixed upstream
with Akka 2.6.0-RC2.
The reason for to revert this is #2414:
CouchbasePersistentEntityRegistry, in the lagom-persistence-couchbase
artifact, which is in the akka-persistence-couchbase repo, depends on
AbstractPersistentEntityRegistry's binary API.  So the change in #2370
broke that.
Sadly this means that eventsByTagQuery goes back to being lazily
evaluated as well as "optional" (but not really).  However, those were
side-effect improvements that we can try and re-introduce later, bearing
in mind this regression.
Fixes #2414

Revert AbstractPersistentEntityRegistry's binary API

---

docs/manual/common/guide/logging/SettingsLogger.md

A `CRON` build failed on `sbt markdownValidateExternalLinks` because the SSL cert for `www.takipi.com` has expired (and I don't expect it to be renewed).

Takipi is now overops

---

build.sbt
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbProvider.scala
persistence-jdbc/core/src/main/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickProvider.scala
persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickDbTestProvider.scala
persistence-jdbc/core/src/test/scala/com/lightbend/lagom/internal/persistence/jdbc/SlickOffsetStoreSpec.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/jdbc/SlickProvider.scala
persistence-jdbc/javadsl/src/main/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceModule.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceComponents.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
persistence-jpa/javadsl/src/main/java/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaSessionImpl.java
persistence-jpa/javadsl/src/test/scala/com/lightbend/lagom/internal/javadsl/persistence/jpa/JpaPersistenceSpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala

As detected in https://github.com/lagom/lagom-samples/issues/121 when shutting down clustered `ProjectionWorker`s the database connection pools and thread pools are already shutdown and the projection worker fails to shutdown cleanly.
The problem is Slick and JPA were registering stop hooks on `ApplicationLifecycle` which are run _before_ the cluster shuts down. That means the actual behavior is (summing up and focusing on relevant bits):
1. shutdown of the system starts
2. `ApplicationLifecycle` runs all stop hooks (JPA and Slick are stoped)
3. cluter sharded actors are stopped. This includes Projection Workers (which use Slick and JPA)
4. Actor System shuts down
The actual solution is to remove the stop hooks for anything that's infrastructure from `ApplicationLifecycle` and, instead, …

DB (Slick/JPA) shutdown must happen after cluster is shut down

---

.jvmopts

Fixes #2432 
The issue in JDK 11 is a race condition so quite hard to reproduce. Still this is not the first time we've observed similar problems.
More info at : https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume

Prevent using TLS 1.3 to avoid issues on Java 11.

---

docs/manual/java/guide/cluster/ReadSideCassandra.md
docs/manual/scala/guide/cluster/ReadSideCassandra.md

Datastax un-`archived/` some content of their docs and added HTTP `301`'s causing our doc validations to [break](https://travis-ci.com/lagom/lagom/jobs/255602584#L1860).

Fix datastax urls

---

docs/manual/java/guide/cluster/Projections.md

Avoid backticks in links, that render as raw backticks.
Make a sentence singular so we can use backtick names, without a trailing 's'.

Tweak projections docs

---

docs/manual/java/guide/cluster/PersistentEntityRDBMS.md

Fixes hyperlink in docs to H2 database.
Documentation update for the latest RC.
Because the link to the H2 database was inconsistent with the link to other relational databases.
Not that I am aware of.

Use consistent link for H2 database

---

persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/AwaitPersistenceInit.scala

Also: after node1 has awaited for persistence of init,
make node2 and node3 await too.
Fixes #2080

C*ClusteredPESpec: Don't keyspace-autocreate

---

project/Dependencies.scala

Related to https://github.com/playframework/playframework/pull/9838
Play-test should not bring in the AkkaHTTP and Netty impls transitively. The internal integration tests for Lagom are run for both Akka HTTP and Netty backends and use `play-test`. At the moment, things work as expected by coincidence because `play-test` depends on both backends. These transitive dependency should be removed.
This PR adds an explicit dependency to both backends and limits it to the `Test` scope.

Play-test should not bring in the AkkaHTTP and Netty impls transitively

---

build.sbt

testkit-scaladsl must not transitively depend on cassandra-persistence

---

docs/manual/java/guide/cluster/ReadSide.md
docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md
docs/manual/java/guide/cluster/code/docs/home/persistence/BlogEvent.java
docs/manual/scala/guide/cluster/ReadSide.md
docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/BlogEvent.scala
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShardedBlogEventTag.scala
docs/manual/scala/guide/cluster/code/docs/home/scaladsl/persistence/ShoppingCart.scala

We must backport it to 1.5.x. Potentially to 1.4.x as well.
Users can run into this issue better to warn about it as much as possible.

Add notice about jdbc plugin tagging limitation

---

bin/test-code-style

This need to be backported to 1.5.x and merged back in master when we do the branch merging of 1.6.x -> master

Don't run validateDependencies (whitelist) in CI

---

project/Dependencies.scala

This removes Play Akka Server dependencies from our modules. 
The only one that we should keep is the `service-locator` and that's normal. 
Users opt-in for the netty server should not get the Play Akka server on their classpath.
I tested it manually with shopping cart (java and scala) and with grpc sample. Both when running unit test as when running in dev-mode. And also switching the server implementation back and forth.
Btw, the grpc sample was quite out of date. I have it updated locally and will PR as soon we have RC3 out.

Avoid direct dependency on Play's Akka server

---

.travis.yml
bin/test-sbt-13x

The key `sbtVersion in pluginCrossBuild` defines the target sbt version
and is the default for `scriptedSbt`, which is the key used when running
scripted.  So by leaving the former set to 1.2.8 (in defineSbtVersion at
the top of build.sbt) but setting scriptedSbt we test that the
1.2.8-targetting build runs on sbt 1.3.
To mitigate the cost on CI times, this will only run in cron builds.

Run scripted tests targeting sbt 1.3

---

.scala-steward.conf

We get very often updates for scalafmt that requires a code reformatting. While is nice to have it each time it's adding some unnecessary overhead.
This PR disable it. We can apply updates from time to time manually when we get to know about any performance improvements or new formatting rule of interest.

Disable scala-steward updates for scalafmt-core

---

docs/manual/java/guide/build/MultipleBuilds.md
docs/manual/scala/guide/build/MultipleBuilds.md

- Describe how to implement a mock service
- Clarify the explanation of binding a client
- Add a note on decoupling services with the Message Broker API
Raised in an internal discussion with Lightbend professional services.

Expand the documentation on multiple builds

---

docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md
docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md

As previously discussed, I'm sending this PR to open a discussion about the usage of the term `Aggregate` in the docs. 
Although I personally prefer it, I now convinced that we should favour the term `Entity` because that's what the Akka API is all about. We get an `EntityRef`, not an `AggregateRef`. 
The guide is still using the term `Aggregate` in a few places, but only we talk about the DDD concept. 
Please, let me know what you think and if we agree on that, I will apply the same changes on the Java counterpart.

Prefer the term 'Entity' over 'Aggregate'

---

docs/manual/scala/guide/cluster/Serialization.md

N/A
Improves grammar and sentence structure in key places on the "Serialization" Scala page.  Improves readability, without changing the content.

[1.5.x] Documentation - "Serialization" page grammar improvements.

---

build.sbt

Mima needs to check against 1.6.0 now. We can also drop checks for other versions now. Moreover, this simplifies some settings as well.

[1.6.x]: Configure mima to check compatibility against 1.6.0

---

docs/manual/scala/guide/cluster/ReadSideCassandra.md

Ugh, forgot the duplicates in the Scala docs..

Datastax URLs are archived again.. (Scala)

---

build.sbt
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala
project/AkkaSnapshotRepositories.scala

Use the system property instead of the TRAVIS_EVENT_TYPE env var as a trigger.
Requires adding to scriptedLaunchOpts, though...

Tweak Akka snapshot handling

---

project/Dependencies.scala

I suspect sbt-akka-version-check is smashing the Compile and Test
dependencies, so the versions don't match.  By adding these dependencies
here, in Compile scope, we're using the akka.version sys prop to set the
version to the nightly version.

Fix Akka nightly version check

---

persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/PersistenceSpec.scala

Copy akka/akka#28355.
This getClass was using Predef.getClass, which is why it's now illegal
(in Scala's 2.13.x HEAD).
Fixes #2579.

Remove use of getClass in constructors

---

docs/manual/java/guide/cluster/Projections.md
docs/manual/scala/guide/cluster/Projections.md

The new Projections API docs should mention that it's marked @ApiMayChange.

Projections API is ApiMayChange

---

.travis.yml

Switch to Coursier's new cache path (XDG).
Also, only cache ~/.ivy2/cache, as ~/.ivy2/local is only meant for local
publishes, and shouldn't persist jobs or builds.

travis: fix coursier/ivy caches

---

bin/scriptLib

Manually backport #2567 to `1.6.x`

Get latest Akka snapshot with dynver-style version

---

project/Dependencies.scala

We need at least Akka 2.5.29 in order to use Akka JDBC 3.5.3.

Upgrade Akka to v2.5.29 and Akka Persistence JDBC to v3.5.3

---

docs/manual/java/gettingstarted/JavaPrereqs.md

Link checker was failing on the osxdaily server redirecting from http to https

Update link to https

---

.travis.yml

This enables builds after merging into 1.6.x.

travis: Declare 1.6.x a main branch

---

persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/cluster/HashCodeMessageExtractor.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/AbstractPersistentEntityRegistry.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/AbstractPersistentEntityRegistry.scala

This is important for users who want to enable `remember-entities` in Akka.
For context:
https://discuss.lightbend.com/t/how-to-use-remember-entities-feature-in-lagom/4396
I use lagom in a production setting and would like to explore enabling this option to avoid elevated response times when rolling out a new deploy.

Handle StartEntity in extractShardId

---

cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusteredMultiNodeUtils.scala

* join node1 to self before others join, because theoretically node2 and node3
may send their join message to node1 before it has joined itself and that
will result in that they will not join
* alternatively we could use joinSeedNodes, which handles retries, but better
to just do it orderly

harden joining in ClusteredMultiNodeUtils

---

cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusterDistributionSpec.scala
cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusteredMultiNodeUtils.scala
cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusteredTeskit.scala
projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala

Fixes #2710
ClusterDistributionSpec fails rather often in Travis tests. The problem is that if the ClusterDistribution is started with a delay on different nodes (which can easily happen on Travis) the shards will not be allocated to all nodes initially. Waiting for rebalance takes too long time with the default rebalance interval.
Solution is to reduce the rebalance interval.
Analyzed logs, and reproduced locally with a sleep delay.

fix flaky ClusterDistributionSpec, #2710

---

docs/manual/java/guide/cluster/UsingAkkaPersistenceTyped.md
docs/manual/scala/guide/cluster/UsingAkkaPersistenceTyped.md

Fix typo in Akka Persistence docs - typedKey to typeKey

---

docs/manual/java/guide/production/ProductionOverview.md
docs/manual/scala/guide/production/ProductionOverview.md

Otherwise, while checking docs in Travis it will fail because coreos.com only
supports TLS 1.3 but Java 8 does not.
(cherry picked from commit b247d9ae512dcdd29316d2e5724a2075da94ab07)
1.6.x backport of #2791

[1.6 backport] docs: fix links to etcd site

---

persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraPersistenceSpec.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
persistence-jdbc/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/jdbc/JdbcPersistenceSpec.scala
persistence-jdbc/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickPersistenceSpec.scala
persistence/core/src/test/scala/com/lightbend/lagom/persistence/ActorSystemSpec.scala
testkit/core/src/main/scala/com/lightbend/lagom/internal/testkit/CassandraTestServer.scala

Avoid port collisions in tests, start CassandraLauncher first

---

cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusterDistributionSpec.scala
cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusteredMultiNodeUtils.scala
cluster/core/src/multi-jvm/scala/com/lightbend/lagom/internal/cluster/ClusteredTeskit.scala
projection/core/src/multi-jvm/scala/com/lightbend/lagom/internal/projection/ProjectionRegistrySpec.scala

We added that fix in `master` but never backported to `1.6.x` where this test was added.

Manual backport #2770 on 1.6.x branch

---

.travis.yml

We had lots of errors recently while downloading the Jabba script. I notice that Lagom is the only project with that problem. Other Akka projects are also using it, but never get issues. 
I suspect that this may be due to the redirect we were using. Let's try if w fixed URL.
Refs: #2777

fix jabba script url

---

.mergify.yml
project/Dependencies.scala

We can't have mergify just update the Kafka client library with a new minor version.
Reverts lagom/lagom#2819

Revert "Update kafka, kafka-clients to 2.5.0"

---

build.sbt
persistence-cassandra/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence-cassandra/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraClusteredPersistentEntitySpec.scala
persistence-jdbc/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala
persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcClusteredPersistentEntitySpec.scala
persistence-jdbc/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/slick/SlickClusteredPersistentEntitySpec.scala
persistence/javadsl/src/multi-jvm/scala/com/lightbend/lagom/javadsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala
persistence/scaladsl/src/multi-jvm/scala/com/lightbend/lagom/scaladsl/persistence/multinode/AbstractClusteredPersistentEntitySpec.scala

References: #2751
multi-jvm tests were a little bit more trick regarding the startup of Cassandra. 
Previously, this was picking a port from sbt task, passing it to configurations, then starting the JVMs and on node 1 starting Cassandra. If could happen that one of the remotes pick the Cassandra port causing conflicts. 
The same could occur when starting H2.

Fixed ports for DB multi-jvm tests

---

.scala-steward.conf

Fix duplicate upgrade Jackson version from Scala Steward.
https://github.com/lagom/lagom/pull/2859 and https://github.com/lagom/lagom/pull/2858 as an example.

Fix duplicate upgrade Jackson version from Scala Steward

---

.travis.yml

Not sure why lagom seems to suffer from jabba download issues more, but this
might help shine some light on it.
Refs #2777
Fixes #xxxx

Split up downloading and installing jabba

---

build.sbt

Fixes #2938 
This avoids the duplicate module problem in #2938 
By switching to the later introduced `publish / skip` sbt-whitesource will not run for those projects as they are not published anyway.

build: use publish/skip to opt out of publishing

---

dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomImport.scala
docs/build.sbt
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
project/Dependencies.scala
project/VersionSyncCheckPlugin.scala
project/plugins.sbt

```
sbt-dependency-graph    -> 0.10.0-RC1 (fix #2961)
Jackson                 -> 2.10.4
Netty                   -> 4.1.50.Final
checker-qual            -> 2.10.0
Guava                   -> 28.2-jre
error_prone_annotations -> 2.3.4
jakarta.xml.bind-api    -> 2.3.3
guice                   -> 4.2.3
ScalaJava8Compat        -> 0.9.1
ssl-config-core         -> 0.4.2
JUnit                   -> 4.13
jakarta.activation-api  -> 1.2.2
agrona                  -> 1.4.1
HikariCP                -> 3.4.5
```
also fixed #2961

Bumps dependencies for release 1.6.3

---

docs/build.sbt
docs/src/test/java/docs/home/persistence/CqrsIntegrationTest.java
project/Dependencies.scala
project/VersionSyncCheckPlugin.scala
project/plugins.sbt

Backport #2962 
```
Netty                   -> 4.1.50.Final
checker-qual            -> 2.10.0
error_prone_annotations -> 2.3.4
jakarta.xml.bind-api    -> 2.3.3
guice                   -> 4.2.3
JUnit                   -> 4.13
jakarta.activation-api  -> 1.2.2
agrona                  -> 1.4.1
HikariCP                -> 3.4.5
```

[master] Bumps dependencies for release 1.6.3 (bp #2962)

---

.scala-steward.conf

Akka and Akka HTTP should be updated conciously.
Jackson should stay on 2.10.x for now.

Scala Steward: exclude Akka libs, pin Jackson

---

project/plugins.sbt

Having diverging sbt-plugins in master and the release branch can be annoying as shown in https://github.com/lagom/lagom/pull/2986
This PR updates the 1.6.x branch to be in better sync.

[1.6.x] bring sbt-plugins in sync with master

---

persistence/scaladsl/src/main/mima-filters/1.6.3.backwards.excludes

This was detected by the backport PR. Don't know why it wasn't found by the original master PR.

additional mima filter for PersistOne, #1309

---

persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/PersistentEntityActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntity.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/AbstractPersistentEntityActorSpec.scala
persistence/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/TestEntity.scala
testkit/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/testkit/PersistentEntityTestDriver.scala

* for custom UnhandledCommand exceptions
Refs #2984
(to be backported to 1.6)

add onUnhandledCommand in PersistentEntity, #2984

---

persistence/core/src/main/resources/reference.conf
persistence/core/src/main/scala/com/lightbend/lagom/internal/persistence/ReadSideConfig.scala
persistence/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/ReadSideActor.scala
persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala

In order to provide metrics over read side processors, it is mandatory to consume events one at a time. 
Power-users implementing their own offset storage and strategy using their own `ReadSideHandler` may implement `handle(): Flow` with grouping (which allows consuming multiple events at once).

Let users disable metrics to process in batches

---

play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/JsonMigration.scala
play-json/src/main/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializer.scala
play-json/src/test/scala/com/lightbend/lagom/scaladsl/playjson/PlayJsonSerializerSpec.scala

Support forward-one migrations.
Refs https://github.com/akka/akka/pull/29514
Needs backporting to `1.6.x`

Improve event migration

---

build.sbt

In zinc 1.4.0, the return type of Analysis.relations changes from File
to VirtualFileRef. There is no good way to make the logic in
macroCompileSettings work after the type signature change so this commit
attempts to reproduce the logic without touching the analysis file. I
verified that ServiceClientMacroErrors was recompiled every time I ran
client-scaladsl/test after this change.
Fixes #xxxx

Make product deletion sbt 1.4.x compatible

---

service/javadsl/api/src/main/scala/com/lightbend/lagom/internal/javadsl/api/ServiceReader.scala
service/javadsl/api/src/test/java/com/lightbend/lagom/api/mock/DefaultMethodWithParamsService.java
service/javadsl/api/src/test/scala/com/lightbend/lagom/internal/api/ServiceReaderSpec.scala

Fixes #3058
See (https://github.com/lagom/lagom/pull/3057) that reproduces this bug

#3058 - service reader fails to read descriptor with default method with parameters

---

.travis.yml

Introduces an initial stage with a single job that will produce an empty cache. Running this job before attempting a retry of a job will ensure the cache exists but it's empty.

Empty Travis' caches on explicit demand

---

docs/manual/scala/guide/cluster/ReadSideSlick.md

* [-] Have you added copyright headers to new files?
* [-] Have you added tests for any changed functionality?
Fixes a small typo in the Slick readside docs (DBIOAciton -> DBIOAction). Apologies if this is too minor, but saw it as I was reading and thought I might as well.

Update ReadSideSlick.md to fix minor typo

---

docs/manual/java/guide/broker/KafkaClient.md
docs/manual/scala/guide/broker/KafkaClient.md
service/core/kafka/client/src/main/resources/reference.conf
service/core/kafka/client/src/main/scala/com/lightbend/lagom/internal/broker/kafka/KafkaConfig.scala
service/core/kafka/server/src/main/scala/com/lightbend/lagom/internal/broker/kafka/TopicProducerActor.scala
service/javadsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaSubscriber.scala
service/javadsl/kafka/server/src/test/resources/application.conf
service/javadsl/kafka/server/src/test/scala/com/lightbend/lagom/internal/javadsl/broker/kafka/JavadslKafkaApiSpec.scala
service/scaladsl/kafka/client/src/main/scala/com/lightbend/lagom/internal/scaladsl/broker/kafka/ScaladslKafkaSubscriber.scala
service/scaladsl/kafka/server/src/test/resources/application.conf
service/scaladsl/kafka/server/src/test/scala/com/lightbend/lagom/scaladsl/kafka/broker/ScaladslKafkaApiSpec.scala

Customization name of Kafka topics.
More than a hundred Kafka instances in our test environments and impossibility sharing one instance for many environments. 😞

Support a mapping of Lagom topic id to real Kafka topic name

---

dev/sbt-plugin/src/main/scala-sbt-1.0/com/lightbend/lagom/sbt/run/RunSupportCompat.scala

This is a manual backport of #3096. 
The code was quite different in 1.6.x. The affected code was moved into `RunSupportCompat`, which surprises me that `master` doesn't have the same structure.

sbt-plugin: handle AssertionError from zinc compilation (bp #3096)

---

project/Dependencies.scala

N/A
Adds the akka-persistence-testkit to the list of dependencies, especially in lagom-maven-dependencies BOM
In response to Include akka-persistence-testkit dependency in lagom-maven-dependencies BOM #3049
Include akka-persistence-testkit dependency in lagom-maven-dependencies BOM #3049

3049: Added akka persistence testkit to dependencies

---

persistence-cassandra/javadsl/src/test/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRefTest.java
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/PersistentEntityRefSpec.scala
persistence/javadsl/src/main/java/com/lightbend/lagom/javadsl/persistence/PersistentEntityRef.java
persistence/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/PersistentEntityRef.scala

Rework of #3121 
Instead of logging, the `AskTimeoutException` is wrapped on a new one containing the entity context.

enrich AskTimeoutException with entity context

---

dev/sbt-plugin/src/sbt-test/sbt-plugin/akka-persistence-typed-migration-java/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/projections-happy-path/build.sbt
docs/manual/java/concepts/code/lagom-immutables.sbt

Just released lombok 1.18.18 adds support for sbt's 1.4 virtual filesystem. I know this project still is on sbt 1.3, just avoiding future headaches.

sbt 1.4 friendly version of Lombok

---

docs/build.sbt
project/Dependencies.scala

This should fix #3180 for now. 
At least we will be able to build again. The nowarn fix is not yet on 2.12.x and we should update as soon as it's released (see https://github.com/scala/bug/issues/12336).
I don't think we use `@nowarn` in Lagom. This is failing because of Akka.

Update Scala versions

---

.travis.yml
bin/test-sbt
dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala
dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/build.sbt
dev/sbt-plugin/src/sbt-test/sbt-plugin/cross-build/test
dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala

This force travis and scripted tests to use Scala 2.12.13 and 2.13.5.
Note, commit 1f5f44b is updating Akka to 2.6.13. This is temporary and will be reverted back to 2.6.10. 
I'm forcing it for now because I don't want to wait for a CRON job.

Ensure usage of Sala 2.12.13 and 2.13.5

---

.jvmopts
build.sbt
docs/.jvmopts

This is a forward port of some changes I added in #3184. 
The build in #3184 was consistently failing with OOM because of the metaspace limit. We didn't observe it in `master` though, but I don't see a reason for having this limit in our builds.

Remove MaxMetaspaceSize limit

---

persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraOffsetStore.scala
persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraReadSideSettings.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraReadSideHandler.scala
persistence-cassandra/javadsl/src/main/scala/com/lightbend/lagom/internal/javadsl/persistence/cassandra/CassandraReadSideImpl.scala
persistence-cassandra/javadsl/src/test/scala/com/lightbend/lagom/javadsl/persistence/cassandra/CassandraReadSideSpec.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraReadSideHandler.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/cassandra/CassandraReadSideImpl.scala
persistence-cassandra/scaladsl/src/main/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraPersistenceComponents.scala
persistence-cassandra/scaladsl/src/test/scala/com/lightbend/lagom/scaladsl/persistence/cassandra/CassandraReadSideSpec.scala

References #3206 
Set the configured consistency level on the read side update batch and offset update (instead of getting the default ONE consistency level for those). Also break read side and offset update into separate actions as a partially failing batch could potentially lead to offset being updated but the actual read side projection updates being lost.

Cassandra read side fault tolerance improvements

---

service/scaladsl/server/src/main/scala/com/lightbend/lagom/internal/scaladsl/server/ScaladslServiceRouter.scala

Current `JavadslServiceRouter`
https://github.com/lagom/lagom/blob/c0c2fdb5d610b8092da840f8c60f9631038418ac/service/javadsl/server/src/main/scala/com/lightbend/lagom/internal/javadsl/server/JavadslServerBuilder.scala#L231-L239

[1.6.x] Sync exception logging level between Scala and Java server implementations

---

docs/manual/java/guide/cluster/PersistentEntityCassandra.md
docs/manual/scala/guide/cluster/PersistentEntityCassandra.md

Fixes lacking documentation awareness of lagom's change from akka-persistence-cassandra-core's `first-time-bucket` usage.
Most of the background is summarized with my [forum post](https://discuss.lightbend.com/t/topic-subscriber-extreme-delay-in-receiving-messages-in-development/8451) highlighting a lacking documentation of the known [akka issue for first-time-buckets](https://github.com/akka/akka-persistence-cassandra/issues/867), attempting to apply the same fix had no bearing on the results. Only after searching throughout did the configuration override within lagom show up as being applicable.
- [akka-persistence-cassandra](https://github.com/akka/akka-persistence-cassandra/issues/867): First time bucket is pre-defined as a starting search since `2016...`

Improve EventTag ReadSide storage with Cassandra documentation

---

docs/manual/common/guide/build/UpgradingAkkaPlay.md

We'll probably not provide the Akka HTTP 10.2 dependency
transitively [until we update to Play 2.9](https://github.com/playframework/playframework/pull/10411),
but since we use no deprecated API's users should be able to update fine.

Hint that upgrading to Akka HTTP 10.2 is fine

---

project/Dependencies.scala

~Let the dev-mode kafka-brokers to use newer log4j version.~
Remove dependency to log4j in dev-mode kafka brokers.

remove explicit dependency on log4j in kafka brokers

---

README.md

After the switch to using GitHub actions instead of Travis.
Link to https://github.com/lagom/lagom/actions/workflows/build-and-test.yml

Show GitHub workflow as CI badge

---

projection/core/src/main/scala/com/lightbend/lagom/internal/projection/ProjectionRegistry.scala

ProjectionRegistry should pass the value of ‘run-on-role’ to ClusterSharding.
During the testing for `run-on-role`, it didn’t work as expected even though set configuration correctly because the return value of 'clusterShardingSettings.withRole' method that has 'runInRole' isn't used below.

fix a bug of run-on-role

---

.github/workflows/build-and-test.yml

Make GitHub actions succeed at installing `xmllint`.
Workflows fail currently https://github.com/lagom/lagom/runs/5702995173?check_suite_focus=true

chore: run apt-get update before installing

---

docs/manual/common/guide/build/UpgradingAkkaPlay.md

Otherwise, running the app will fail because some modules are still on older versions.

docs: make sure more modules are pulled to higher versions
